### PR TITLE
Analog wrapper port name

### PR DESCRIPTION
**Pull request by barbalberto**
Moved analogSensorClient into folder and separated into header and cpp
Implemented new policy for portname using --name option instead of robot+part following issue #113 
It was tested on the red iCub - I did also connection test with custom config file with both new policy / both old policy and mixed configuration and it works, provide the config files are correct in the mixed config.

### CODE REVIEW

**Comment by pattacini** [comment]
What does it mean in terms of current icub port names?
Any example?

**Comment by barbalberto** [comment]
Short answer is: nothing immediatly because old behaviour is preserved, the update to the new policy requires a small change in config file.

With old policy, the port name was build as follow:
streaming port name:  param robot + param part + "analog:o" (last part enforced in code)
rpc port name :            param robot + param part + "analog:o/rpc:i" (last part enforced in code)

new policy is:
streaming port name:  param name  (used as is)
rpc port name :            param name + "/rpc:i"  (last part enforced in code)

If you use ' param robot + param part + "analog:o"  ' as name for the new policy, again it is back compatible, but then you can get rid of the ugly  'analog:o/rpc:i' since this part is now under user control.
You can also make the portname more clear by adding for example the type of data exchanged, like:

name   /icub/left_arm/forceTorque

will open
/icub/left_arm/forceTorque
/icub/left_arm/forceTorque/rpc:i

Of course, in this case you have to change the client accordingly. The clients already used this policy so now they are symmetric.
A warning message will be printed if old policy is used..

**Comment by pattacini** [comment]
many thanks @barbalberto for the resume :)
if in the future we are going to change those port names via the new params, please remember to let the community know, since sometimes there are direct connections to analog ports made in the code (because are somehow deemed to be always available).

**Comment by barbalberto** [comment]
If there are no other comments I'll merge it

**Comment by barbalberto** [comment]
closing this pull request without merging  'cause I've updated the code with more stuff, I'll open a new one later

**Pull request closed without merging**
