### PR TITLE
bindings: Require SWIG 4 or later

### PR DESCRIPTION
**Pull request by drdanz**
Apparently, after #2707 and #2719, YARP bindings no longer compiles with SWIG 3.

### CODE REVIEW

**Comment by traversaro** [comment]
> Apparently, after #2707 and #2719, YARP bindings no longer compiles with SWIG 3.

I can confirm I observed something similar in Ubuntu 18.04 superbuild jobs.

**Comment by drdanz** [comment]
@traversaro I haven't merged this yet, because Ubuntu 18.04 and Debian 10 do not have SWIG 4.
Do you think we can say that bindings are no longer supported on these distros?

**Comment by traversaro** [comment]
> 
> 
> @traversaro I haven't merged this yet, because Ubuntu 18.04 and Debian 10 do not have SWIG 4. Do you think we can say that bindings are no longer supported on these distros?

At the superbuild level, I think it is perfectly fine. If Ubuntu 18.04 users really need YARP Python bindings, they can still use conda. : )

**Comment by drdanz** [comment]
> At the superbuild level, I think it is perfectly fine. If Ubuntu 18.04 users really need YARP Python bindings, they can still use conda instead of apt. : )

Is SWIG4 avaliable on Conda? If that's true, we should probably open a discussion on community, explaining how to install it, like we did for CMake 3.12...

**Comment by traversaro** [comment]
> 
> 
> > At the superbuild level, I think it is perfectly fine. If Ubuntu 18.04 users really need YARP Python bindings, they can still use conda instead of apt. : )
> 
> Is SWIG4 avaliable on Conda? If that's true, we should probably open a discussion on community, explaining how to install it, like we did for CMake 3.12...

Yes conda-forge has SWIG 4.0.2, but I would avoid to suggest to mix conda-provided and apt-provided packages (even if in this case it should be ok as swig is just an executable). In this case I think we can have the community discussion, but just point to the existing resources to install YARP bindings from sources or from binaries on conda.

**Comment by PeterBowman** [comment]
Just for the record and future reference (not sure if this has been mentioned anywhere), SWIG 3 doesn't seem to like C++17-style concatenated namespaces (such as `namespace yarp::os::Whatever {}`) introduced in https://github.com/robotology/yarp/pull/2719.

**Pull request merged**
