### PR TITLE
[OSX] Bundle generation is optional

### PR DESCRIPTION
**Pull request by francesco-romano**
Added also icons and custom Bundle.plist

### CODE REVIEW

**Comment by francesco-romano** [comment]
After this PR will be merged the remaining issues will be summarized in https://github.com/robotology/yarp/issues/580

**Comment by francesco-romano** [comment]
Nobody complained :smile: 
Merging

**Comment by drdanz** [comment]
@francesco-romano sorry, I didn't have time to review it... anyway it looks good!

Just a couple of comments...

1. For some GUIs `yarp_osx_bundle_update_rpath` (and some other commands) are called only `if(YARP_OSX_GENERATE_BUNDLES)`, for other are always called. Is this the wanted behaviour?
2. The other icons are all in <yarp>/data/icons, I think these .icns icons should be there as well.

**Comment by pattacini** [comment]
@francesco-romano 
Can we delete this branch?

**Comment by francesco-romano** [comment]
ok.. I wanted to do other stuff, but I have no time right now..

**Pull request merged**
