### PR TITLE
Open ni2 device clean wip

### PR DESCRIPTION
**Pull request by barbalberto**
This PR changes the OpenNI2 device CMake file in such a way that if NiTE2 library is not found, then the compilation of the skeleton extraction is skipped.

### CODE REVIEW

**Comment by drdanz** [comment]
LGTM, but perhaps @kt10aan or @jgvictores want to have at look at it before merging?

**Comment by kt10aan** [comment]
@drdanz, I have tested  the PR. See https://github.com/robotology/yarp/issues/690

**Comment by drdanz** [comment]
@kt10aan cool thanks! I see in the same issue that also @jgvictores tested it, therefore I'm merging this, if there is some further issue we can fix it later.

**Comment by drdanz** [comment]
@barbalberto merged, thanks!

**Pull request merged**
