### PR TITLE
Restore devices disabled during pre-relicense phase

### PR DESCRIPTION
**Pull request by drdanz**

### CODE REVIEW

**Comment by drdanz** [comment]
There is a problem of circular dependencies when building YARP static... the problem is that the yarpidl_rosmsg tool depends on YARP_OS and YARP_init because it can do stuff that use the yarp::os::Network, but init depends on yarpmod, yarpmod depends on each plugin that is going to be built, and some plugins depend on code generated by yarpidl_rosmsg.

The same problem is actually in YARP_dev.

I think we should consider removing networking abilities from yarpidl_rosmsg

**Comment by barbalberto** [comment]
LGTM
In  your opinion is it possible to break the dependency between init and yarpmod?

**Comment by traversaro** [comment]
This PR is not ready for review, right?

**Comment by drdanz** [comment]
Yes sorry, even thought I don't think I can fix the circular dependency at the moment, I'm now trying to avoid having the message files and the auto-generated code in several different places.

**Comment by drdanz** [comment]
Message files are now in YARP_rosmsg library, fixed issues with windows, fixed issues with math disabled
If it finally builds, it should be ready to be merged...

**Comment by drdanz** [comment]
@traversaro If you want to review the changes this is the right moment since if there are no other unexpected issues, I'm going to merge this in devel as soon as appveyor builds are finished

**Pull request merged**
