### PR TITLE
os: Change layout for src/include file and rename library YARP_os

### PR DESCRIPTION
**Pull request by drdanz**
The rename follows the other libraries convention

There is no way to deprecate CMake targets yet (see https://gitlab.kitware.com/cmake/cmake/issues/17824), therefore we print a warning if the `OS` component is used, and a warnings every time `api.h` is included (unfortunately this does not work with `-isystem`).

### CODE REVIEW

**Comment by drdanz** [comment]
Appveyor failures are unrelated.

**Comment by Nicogene** [comment]
> Is the following configuration error expected while building `icub-main`?
> 
> ```
> CMake Error at CMakeLists.txt:9999 (_yarp_component_path_is_deprecated):
>   Unknown CMake command "_yarp_component_path_is_deprecated".
> Call Stack (most recent call first):
>   CMakeLists.txt:35 (list)
> 
> 
> CMake Error: Error in cmake code at
> Unknown:0:
> A command failed during the invocation of callback "_yarp_component_path_is_deprecated".
> ```
> 
> I would expect only a warning.


I experienced the same error on `macOs`

**Comment by drdanz** [comment]
Sorry, I didn't notice these, I tend to leave behind comments to closed pr and issues... Please feel free to open a new issue and link to the closed PR next time.
Anyway, @Nicogene already fixed this in #2112, thanks.

**Pull request merged**
