### PR TITLE
Release notes

### PR DESCRIPTION
**Pull request by drdanz**
Add release notes for v2.3.65 and v2.3.65.1

Improve format of the changelog page.

The release notes are written using markdown instead of doxygen, so that
they can be copy-pasted in the release page on github.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/777%23issuecomment-221902302%22%2C%20%22https%3A//github.com/robotology/yarp/pull/777%23issuecomment-222082433%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/777%23issuecomment-221902302%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22The%20%5C%22changelog%5C%22%20page%20will%20contain%20only%20a%20link%20to%20the%20release%20notes%20for%20all%20the%20releases.%5Cr%5Cn%40lornat75%20%40pattacini%20Does%20this%20look%20ok%20to%20you%3F%22%2C%20%22created_at%22%3A%20%222016-05-26T15%3A18%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22Looks%20fine%2C%20although%20I%20can%27t%20see%20how%20it%20would%20look%20like%20in%20the%20online%20page.%20The%20main%20thing%20is%20to%20be%20able%20to%20list%20all%20important%20changes%20introduced%20between%20releases.%22%2C%20%22created_at%22%3A%20%222016-05-27T07%3A47%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1403333%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lornat75%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/777#issuecomment-221902302'>General Comment</a></b>
- <a href='https://github.com/drdanz'></a> The "changelog" page will contain only a link to the release notes for all the releases.
@lornat75 @pattacini Does this look ok to you?
- <a href='https://github.com/lornat75'></a> Looks fine, although I can't see how it would look like in the online page. The main thing is to be able to list all important changes introduced between releases.

<a href='https://www.codereviewhub.com/robotology/yarp/pull/777?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/777?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/777'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/777'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by drdanz** [comment]
The "changelog" page will contain only a link to the release notes for all the releases.
@lornat75 @pattacini Does this look ok to you?

**Comment by lornat75** [comment]
Looks fine, although I can't see how it would look like in the online page. The main thing is to be able to list all important changes introduced between releases.

**Comment by drdanz** [comment]
@lornat75 I merged this, as soon as the doxygen documentation is re-generated you can see the result here: http://www.yarp.it/changelog.html
If you don't like it, we can revert the changes...

**Comment by drdanz** [comment]
@lornat75 you can also have a preview here: https://github.com/robotology/yarp/releases/tag/v2.3.65

**Comment by pattacini** [comment]
Looks nice to me :+1:

**Comment by drdanz** [comment]
@pattacini I think it is also worth to add in the CONTRIBUTING.md file that important changes should be added to the release notes, possibly in a separate commit in pull requests. Does this sound ok to you?

**Comment by pattacini** [comment]
@drdanz yep, definitely :+1:

**Comment by lornat75** [comment]
Looks nice, but maybe we have to remove the "YARP 2.3.65" section in the doxygen.

In addition we need a place where to log changes as they are introduced in the code, where is this done?

**Comment by drdanz** [comment]
in the files `doc/release/v2_3_65_1.md` for changes in `master` and `doc/release/v2_3_68.md` for changes in `devel`

**Comment by drdanz** [comment]
@lornat75 I left the section because it appears on the TOC, I was thinking to change it to "YARP 2.3.65 Series" and to include all the "2.3.65.XX" versions in that section.
If you prefer to remove the section instead, it is ok for me... Let me know what you prefer.

**Pull request merged**
