### PR TITLE
[WIP] iNavigation2D interface

### PR DESCRIPTION
**Pull request by randaz81**
wip, 90% complete, under review
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
<a href='https://www.codereviewhub.com/robotology/yarp/pull/835?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/835'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/835'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by drdanz** [comment]
@randaz81 Next time please remove the `[WIP]` tag from the title of the PR before merging, so that it doesn't end up in the commit log.

**Comment by drdanz** [comment]
@randaz81 Also by merging without waiting for the unit tests, you broke the build for macOS and for `YARP_NO_DEPRECATED` please fix it ASAP...

https://travis-ci.org/robotology/yarp/builds/166445319

**Comment by drdanz** [comment]
Actually only the `YARP_NO_DEPRECATED` builds were broken, they should be fixed now

**Comment by randaz81** [comment]
@francesco-romano @traversaro we need your help to check the tests for the macOS builds...

**Pull request merged**
