### PR TITLE
sig/VectorOf: Do not explicitly implement copy/move ctors and assignment operators

### PR DESCRIPTION
**Pull request by drdanz**
Default ones are just fine (rule of zero)

CC: @Nicogene
CC-Issue: #2432

### CODE REVIEW

**Review by Nicogene — APPROVED** [review]

**Comment by drdanz** [comment]
The `bindings::ruby::vector` test is failing with this error:
```
<yarp>/bindings/ruby/tests/test_vector.rb:19:in `initialize': Wrong arguments for overloaded method 'Vector.new'. (ArgumentError)
Possible C/C++ prototypes are:
    Vector.new()
    Vector.new(size_t size)
    Vector.new(size_t s, double const &def)
    Vector.new(size_t s, double const *p)
    Vector.new(std::vector< double,std::allocator< double > > const &values)
        from <yarp>/bindings/ruby/tests/test_vector.rb:19:in `new'
        from <yarp>/bindings/ruby/tests/test_vector.rb:19:in `test_vector'
        from <yarp>/bindings/ruby/tests/test_vector.rb:30:in `<main>'
```

Apparently swig is not generating the method for automatically generated ctor and operators...
Perhaps we should declare them `= default` to make swig happy?
Anyway this sounds like a bug in swig

**Pull request merged**
