### PR TITLE
Fix video generation in yarpdatadumper

### PR DESCRIPTION
**Pull request by pattacini**
This PR addresses and solves #2193.

I've tested it successfully running the following:
- `yarpdev --device test_grabber`
- `yarpdatadumper --type video --connect /grabber`

### CODE REVIEW

**Comment by Nicogene** [comment]
Ah is this bug also in `yarp3.3`?
In that case we should change the target branch

**Comment by alessiav** [comment]
Hi,
thank you! I tried it and it did not work for me.
I probably have some problems with the codec then.
I tried to follow "Codec Installation" of https://www.yarp.it/yarpdatadumper.html", but I had some problems as I don't think it is updated..is it?

**Comment by pattacini** [comment]
@alessiav to make it work I had to install the `ffmpeg` and compile `opencv` with the dependency enabled (`-DWITH_FFMPEG=ON`).

**Comment by pattacini** [comment]
@Nicogene base branch changed accordingly 👍

**Comment by pattacini** [comment]
CI failure seems unrelated.

**Comment by Nicogene** [comment]
Merged, thanks!

**Comment by alessiav** [comment]
Thanks a lot @pattacini @Nicogene !! 👍

**Comment by PeterBowman** [comment]
This change is not compatible with OpenCV 2.4.9.1 (latest `apt` package on Ubuntu 16.04). There is no `cv::VideoWriter::fourcc` function in OpenCV 2.x ([ref](https://docs.opencv.org/ref/2.4/dd/d9e/classcv_1_1VideoWriter.html), cf. [OpenCV 3.x](https://docs.opencv.org/3.4/dd/d9e/classcv_1_1VideoWriter.html)).

```
/home/teo/repos/yarp/src/yarpdatadumper/main.cpp: In member function ‘virtual void DumpThread::run()’:
/home/teo/repos/yarp/src/yarpdatadumper/main.cpp:489:69: error: ‘fourcc’ is not a member of ‘cv::VideoWriter’
                 videoWriter.open(videoFile.c_str(),cv::VideoWriter::fourcc('H','F','Y','U'),
                                                                     ^~~~~~
```

I'm aware that Ubuntu 16.04 and OpenCV 2.x are longer supported according to the [compatibility matrix](http://wiki.icub.org/wiki/YARP_Supported_Distributions). However, there has been some effort towards enabling YARP with OpenCV 2/3/4 (see https://github.com/robotology/yarp/pull/2162#issuecomment-570530908, which is previous to this PR), plus:

https://github.com/robotology/yarp/blob/4f2e8832535ee863bfbc4c073049927f7c548372/cmake/YarpFindDependencies.cmake#L331-L332

The AppVeyor test which was supposed to catch these issues (uses OpenCV 2.4.13) did not compile YARP with OpenCV ([ref](https://ci.appveyor.com/project/robotology/yarp/builds/30610509/job/g36u65q1w362jc1w?fullLog=true#L292)), hence the lack of build errors.

**Pull request merged**
