### PR TITLE
Creation of the .msg file by yarpidl_rosmsg

### PR DESCRIPTION
**Pull request by plinioMoreno**
method RosTypeSearch::fetchFromRos

The command to be issued in that line is "rosmsg show ....", which is a ROS script. Since ROS is not supported for windows (see [here](http://wiki.ros.org/kinetic/Installation)), that part of the code will not work on windows. On windows what you can do is to search for the message on the web, using the [fetchFromWeb](https://github.com/robotology/yarp/blob/master/src/idls/rosmsg/src/RosType.cpp#L564). The other OS where that line can be tested is OS X, but on the ROS side is experimental.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/plinioMoreno%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3798890%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/drdanz%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/805%23issuecomment-227169297%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-06-20T15%3A03%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3798890%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/plinioMoreno%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-06-21T09%3A33%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/805%23issuecomment-227169297%22%2C%20%22https%3A//github.com/robotology/yarp/pull/805%23issuecomment-227389297%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/plinioMoreno'></a><a href='https://github.com/drdanz'></a>

<a href='https://www.codereviewhub.com/robotology/yarp/pull/805?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/805?approve=0'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/805'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/805'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by plinioMoreno** [comment]
:shipit:

**Comment by drdanz** [comment]
:shipit:

**Comment by drdanz** [comment]
Merged manually in order to save you another rebase... :)
For some reason it does not appear here.

Thanks

**Pull request closed without merging**
