### PR TITLE
Bindings: Disable extended analog sensor interfaces in CSharp

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
See https://github.com/robotology/yarp/issues/1770, same fix as in https://github.com/robotology/yarp/pull/1817 (which was for Java)

### CODE REVIEW

**Comment by traversaro** [comment]
Thanks @Tobias-Fischer . Given that 3.1.0 was released with this bug, can you add a line on the fix in https://github.com/robotology/yarp/blob/master/doc/release/v3_1_1.md ? Thanks!

**Comment by Tobias-Fischer** [comment]
@traversaro: Done - I'd recommend squasing commits while merging.

**Comment by traversaro** [comment]
Manually rebased and force pushed because I guess this is how @drdanz prefers.

**Comment by Nicogene** [comment]
Thanks @Tobias-Fischer for the temporary fix! :muscle: 
Now that we have no more releases' deadlines we should investigate what is the origin of the problem and fix it properly

**Pull request merged**
