### PR TITLE
[WIP] Fix quaternion handling functions 

### PR DESCRIPTION
**Pull request by traversaro**
As discussed in https://github.com/robotology/yarp/issues/786 .

### CODE REVIEW

**Comment by traversaro** [comment]
cc @randaz81 @aerydna

**Comment by drdanz** [comment]
@traversaro What's the status of this PR? Is it still "WIP"?

**Comment by traversaro** [comment]
There was a fishy use of a conversion function in tf stuff, @aerydna Was on it

**Comment by aerydna** [comment]
i'll check it(and i hope close it) today

**Comment by aerydna** [comment]
frameTransformClient and his test improved with the new math method.

**Comment by randaz81** [comment]
can we discuss this PR before merge?

**Comment by randaz81** [comment]
Am I wrong or methods such as: rotationmatrix2rpy are missing? 
Or we are going with dcm2rpy instead?
(In this latter case we have not chosen the best API names...)

**Pull request merged**
