### PR TITLE
robotinterface: Allow replacing values from command line

### PR DESCRIPTION
**Pull request by drdanz**
The goal of this patch is to allow us to replace some of the values of the parameters passed to the devices, with arguments passed from the command line. This saves us from having hundreds of identical files, with just one different parameter.
On the other hand we want to avoid the complexity of `xacro` and similar, and we want to have a valid `xml` that can be started even if these parameter are not set, and that are compatible with the old `yarprobotinterface`

As a result, we decided to add a new `extern-name` attribute to the `param` tag (suggestions for a better name are welcome), that contains a global name, that is compared and eventually replaced with a value taken from a `Searchable` that can now be optionally passed to the `getRobotFromFile` and `getRobotFromString` methods.

----

#### `XMLReader`

* The `getRobotFromFile` and `getRobotFromString` now accept a `Searchable` that
  is used to replace params with the attribute `extern-name`.
  The signatures are now:
  ```
      XMLReaderResult getRobotFromFile(const std::string& filename,
                                       const yarp::os::Searchable& config = yarp::os::Property());
      XMLReaderResult getRobotFromString(const std::string& filename,
                                         const yarp::os::Searchable& config = yarp::os::Property());
  ```

* DTD version is now 3.1.

### `yarprobotinterface`

* Arguments taken from the command line are now handled and used to replace
  parameters marked with the attribute `extern-name`.

### CODE REVIEW

**Review by randaz81 — APPROVED** [review]

**Comment by traversaro** [comment]
It seems quite cool, thanks! Do you have any example on how to do overload a parameter via the `yarprobotinterface` command line?

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
In the future (but this is more complex, so for  the moment not need to block this PR) it would be cool to be able to overload parameters without manually specifying the `extern-name` attribute, re-using some already existing identified of the parameter, such as [XPath](https://en.wikipedia.org/wiki/XPath) or something equivalent. On the Ignition/Gazebo/SDF side, there is a lot of work going on a similar topics, see https://github.com/osrf/sdformat/issues/278 for a reference.

**Comment by drdanz** [comment]
There is one test hiddend inside the `src/yarprobotinterface` folder, you can try it running

```
yarprobotinterface --config src/yarprobotinterface/tests/fakeFrameGrabber/grabber.xml --mode line
```

There is also an unit test in `tests/libYARP_robotinterface/RobotinterfaceTest.cpp` that shows how to do it from the library

**Comment by drdanz** [comment]
> In the future (but this is more complex, so for the moment not need to block this PR) it would be cool to be able to overload parameters without manually specifying the `extern-name` attribute, re-using some already existing identified of the parameter, such as [XPath](https://en.wikipedia.org/wiki/XPath) or something equivalent. On the Ignition/Gazebo/SDF side, there is a lot of work going on a similar topics, see [osrf/sdformat#278](https://github.com/osrf/sdformat/issues/278) for a reference.

I agree that using XPath or similar would be cool, but this probably means re-write the whole parsing with a different library, since I doubt that `tinyxml` is able to handle XPath (we already had to fake support for the DTD and for `xi:include`, since they are not supported).
Anyway the 2 options are not mutually exclusive, this could be added in the future.

I think this is somehow different, because in order to replace 2 parameters with the same value, you don't have to pass 2 different paths, you just need to "export" them externally with the same name (but I don't know much about XPath, perhaps you can have wildcards or similar, that would make them equivalent, assuming that you write the path properly)

**Comment by traversaro** [comment]
> Anyway the 2 options are not mutually exclusive, this could be added in the future.
> 
> I think this is somehow different, because in order to replace 2 parameters with the same value, you don't have to pass 2 different paths, you just need to "export" them externally with the same name (but I don't know much about XPath, perhaps you can have wildcards or similar, that would make them equivalent, assuming that you write the path properly)

Yes, I totally agree! 

> I agree that using XPath or similar would be cool, but this probably means re-write the whole parsing with a different library, since I doubt that tinyxml is able to handle XPath (we already had to fake support for the DTD and for xi:include, since they are not supported).

In SDF they are using tinyxml2, and they are doing something similar (even if perhaps they are not doing exactly XPath), I will check it more in detail in the future.

**Pull request merged**
