### PR TITLE
imuBosch: fix unit measure in ThreeAxis interface

### PR DESCRIPTION
**Pull request by Nicogene**
:warning: WAIT #2041  BEFORE MERGING.

### CODE REVIEW

**Comment by prashanthr05** [comment]
Related Issue : https://github.com/robotology/yarp/issues/2038

**Comment by barbalberto** [comment]
@traversaro In the new magnetomiter interface, the documentation states that the unit is Tesla, so this PR adds the convertion factor from uT to T.
In the old interface the measurement unit was not specified, so for back compatibility we didn't add this unit conversion.
I hope old interface will be deprecated in the future, so I think it is good to keep compatibility until it'll go away. Do you agree?

**Comment by traversaro** [comment]
> In the old interface the measurement unit was not specified, so for back compatibility we didn't add this unit conversion.
I hope old interface will be deprecated in the future, so I think it is good to keep compatibility until it'll go away. Do you agree?

I agree. For the old interface `IGenericSensor` interface, the units of measurements (even if not explicitly defined in http://wiki.icub.org/wiki/Inertial_Sensor) were loosely defined by the xsensmtx device, that acted as a sort of "reference implementation". Based on the section 2.4 of http://wiki.icub.org/images/8/82/XsensMtx.pdf, I would expect those units to be `mGauss`, and probably it could  would make sense to use `mGauss` also for this device, but clearly this is something that can be addressed in a separate PR/issue.

**Comment by drdanz** [comment]
Merged, thanks.

**Pull request merged**
