### PR TITLE
[Test] libYARP_OS

### PR DESCRIPTION
**Pull request by claudiofantacci**
Added a test for the _SystemInfo_ class (has 0% coverage according to coveralls.io) of libYARP_OS.
Corrected a typo in the SystemInfo.h doc.

### CODE REVIEW

**Comment by drdanz** [comment]
@claudiofantacci "Merge branch 'master' of https://github.com/robotology/yarp" is a commit that is generated automatically when you `pull` without rebasing and master received some updates. This kind of commits makes the history very messy.

Please rebase over the latest master and squash the two "good" commits into one. If you don't know how to do it just come and ask ;)

**Comment by alecive** [comment]
@drdanz I don't know if this is unsafe in some cases (I don't think so), but @claudiofantacci you might find useful to configure your git client to automatically rebase when pulling. On linux, you have to run the following command:

```
git config --global pull.rebase true
```

**Comment by drdanz** [comment]
@alecive I don't like "magic", I like to know what I'm doing... anyway it might be useful for someone.

@claudiofantacci Thanks, I'll merge as soon as the tests finish running.

**Comment by claudiofantacci** [comment]
@alecive thanks for your suggestion! @drdanz told me that it would be safe to do that, but I prefer not to "force" rebase for every pull and instead to clearly understand when to use it not :-)

**Pull request merged**
