### PR TITLE
Fix https://github.com/robotology/yarp/issues/826

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
See https://github.com/robotology/yarp/issues/826
Main contribution is the proper implementation of getBusInfo, which provides a connection list to ROS. It's not yet implemented for services.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/827%23issuecomment-233025814%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/827%23issuecomment-233025814%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Would%20be%20great%20if%20you%20have%20a%20look%20%40drdanz%20%3A%29%22%2C%20%22created_at%22%3A%20%222016-07-15T18%3A09%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/827#issuecomment-233025814'>General Comment</a></b>
- <a href='https://github.com/Tobias-Fischer'></a> Would be great if you have a look @drdanz :)

<a href='https://www.codereviewhub.com/robotology/yarp/pull/827?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/827?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/827'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/827'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Tobias-Fischer** [comment]
Would be great if you have a look @drdanz :)

**Comment by Tobias-Fischer** [comment]
Closing, rebased version at https://github.com/robotology/yarp/pull/828

**Comment by drdanz** [comment]
@Tobias-Fischer just for information, there was no need to close this pr and open a different one, you could just have rebased the branch and then push --force on the original branch.
Anyway, thanks for working on this, I will review the on Monday...

**Comment by Tobias-Fischer** [comment]
Yes I know @drdanz but it would have taken me twice the time ;). Thanks for reviewing the other PR.

**Pull request closed without merging**
