### PR TITLE
Audio volume

### PR DESCRIPTION
**Pull request by randaz81**
#### yarp::sig
* `yarp::sig::sound` added the following methods:  amplifyChannel(), amplify(), findPeakInChannel(), findPeak(), normalizeChannel(), normalize() 
* `harness_sig`: added tests to check the new methods

#### yarp::dev
* Added the new datatypes `yarp::dev::audioRecorderStatus` and `yarp::dev::audioPlaybackStatus` generated by thrift.
* Added the new class `AudioPlayerDeviceBase`, all playback device drivers now derive from this class.
* Added the new class `AudioRecorerDeviceBase`, all recording device drivers now derive from this class.
* Added the new methods to `setHWGain()`, `setSWGain()` to `IAudioRender` interface.
* Added the new methods to `setHWGain()`, `setSWGain()` to `IAudioGrabberSound` interface.

### Devices
* Added RPC commands to `AudioPlayerWrapper` and `AudioRecorderWrapper`, to control the volume via setHWGain()`, `setSWGain()`
* `AudioPlayerWrapper` and `AudioRecorderWrapper` now broadcast their internal status on a xxx/status:o port
* All playback device drivers, i.e. `audioToFileDevice`, `fakeSpeaker`, `portaudioPlayer` ,now derive from `AudioPlayerDeviceBase`.
* All recording device drivers, i.e. `audioFromFileDevice`,`fakeMicrophone`,`portaadioRecorder`, now derive from `AudioRecorderDeviceBase`.

### CODE REVIEW

**Comment by randaz81** [comment]
\rebase

**Comment by randaz81** [comment]
This PR needs a major revision. 
The volume management logic will be moved from the wrapper to... elsewhere.

**Comment by randaz81** [comment]
The following devices have been tested:
- [ ] audioFromFile
- [ ] audioToFile
- [ ] fakeMicrophone
- [ ] fakeSpeaker
- [ ] portAudioPlayer
- [ ] portAudioRecorder

The PR could be merged only after all of these devices will be tested

**Comment by drdanz** [comment]
Merged, thanks.

**Pull request merged**
