### PR TITLE
fix bug introduced by initialization in yarpdatadumper

### LINKED ISSUE #1496: YARP devel with YARP_USE_OPENCV set to OFF does not compile
With the following error: 
~~~
[ 91%] Built target YARP_OS
[ 91%] Built target YARP_init
[100%] Built target YARP_sig
Scanning dependencies of target yarpdatadumper
[100%] Building CXX object src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/main.cpp.o
/Users/traversaro/src/something-superbuild/isaac/YARP/src/yarpdatadumper/main.cpp:305:9: error: member initializer 't0' does not name a non-static data member or base class
        t0(0.0)
        ^~~~~~~
1 error generated.
make[3]: *** [src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/main.cpp.o] Error 1
make[2]: *** [src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/all] Error 2
make[1]: *** [src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/rule] Error 2
make: *** [yarpdatadumper] Error 2
~~~

### PR DESCRIPTION
**Pull request by damn1**
Fixes #1496

### CODE REVIEW

**Comment by pattacini** [comment]
@damn1 since you're on this, could you please also remove these lines:
https://github.com/robotology/yarp/blob/devel/src/yarpdatadumper/main.cpp#L344-L346

The initialization is done in the constructor.

**Comment by damn1** [comment]
@pattacini right, I didn't notice that section in the first place.

**Comment by Nicogene** [comment]
Problems in java bindings with `TRAVIS_NO_DEPRECATED=TRUE`, is it normal?

**Comment by traversaro** [comment]
It seems something new, but unrelated to this PR : https://travis-ci.org/robotology/yarp/branches . 
Probably related to some Travis update?

**Comment by Nicogene** [comment]
I agree, let's merge it

**Comment by drdanz** [comment]
Merged, thanks.

**Pull request merged**
