### PR TITLE
dev: Move a few interfaces in the files where they belong

### PR DESCRIPTION
**Pull request by drdanz**
This is something that has been annoying me for enough time

### dev

* The `<yarp/dev/PreciselyTimed.h>` include file is deprecated in favour of
  `<yarp/dev/IPreciselyTimed.h>`.

### CODE REVIEW

**Comment by drdanz** [comment]
I added also the interfaces `CalibratorInterfaces`, and the vocabs in `ControlBoardInterfaces`.
In this case the files are not deprecated, they just became smaller version of the `all.h` file... We might consider deprecating them in the future

**Comment by traversaro** [comment]
I have a CI failure, in which icub devel is not compiling against YARP devel, even if `YARP_NO_DEPRECATED` is off, see https://travis-ci.org/robotology/idyntree/jobs/587388948 . Perhaps the deprecated header `<yarp/dev/PreciselyTimed.h>` is not installed properly?

**Comment by drdanz** [comment]
@traversaro Should be fixed by 757cdeb974bc0422f70a6834f8aaf7d0f293ef79

**Comment by traversaro** [comment]
Thanks @drdanz !

**Pull request merged**
