### PR TITLE
rplidar sdk update

### PR DESCRIPTION
**Pull request by randaz81**
* `extern/rplidar` updated to the latest version from https://github.com/Slamtec/rplidar_sdk
* affects yarp device `rplidar2`

### CODE REVIEW

**Review by drdanz — CHANGES_REQUESTED** [review]
Please update the following files:
* `extern/rplidar/README.txt`
* `.reuse/dep5`

Also it is probably worth checking if the new SDK version compiles with Clang and eventually enable it, since at the moment the rpLidar2 device is disabled on Clang (see [here](https://github.com/robotology/yarp/blob/bb647b69e084c295d6d7e31aeb36202abe42ccf9/src/devices/rpLidar2/CMakeLists.txt#L8))

**Comment by drdanz** [comment]
Just for reference, I think that the sdk is used only for the `rpLidar2` device, I don't think that the `rpLidar device uses it...

**Comment by drdanz** [comment]
> Also it is probably worth checking if the new SDK version compiles with Clang and eventually enable it, since at the moment the rpLidar2 device is disabled on Clang (see [here](https://github.com/robotology/yarp/blob/bb647b69e084c295d6d7e31aeb36202abe42ccf9/src/devices/rpLidar2/CMakeLists.txt#L8))

Related issue: https://github.com/Slamtec/rplidar_sdk/issues/14

**Comment by randaz81** [comment]
> Please update the following files:
> 
> * `extern/rplidar/README.txt`
> * `.reuse/dep5`
> 
> Also it is probably worth checking if the new SDK version compiles with Clang and eventually enable it, since at the moment the rpLidar2 device is disabled on Clang (see [here](https://github.com/robotology/yarp/blob/bb647b69e084c295d6d7e31aeb36202abe42ccf9/src/devices/rpLidar2/CMakeLists.txt#L8))

done

**Comment by randaz81** [comment]
> > Also it is probably worth checking if the new SDK version compiles with Clang and eventually enable it, since at the moment the rpLidar2 device is disabled on Clang (see [here](https://github.com/robotology/yarp/blob/bb647b69e084c295d6d7e31aeb36202abe42ccf9/src/devices/rpLidar2/CMakeLists.txt#L8))
> 
> Related issue: [Slamtec/rplidar_sdk#14](https://github.com/Slamtec/rplidar_sdk/issues/14)

I think there are no updates on this issue

**Review by drdanz — APPROVED** [review]
LGTM now

**Pull request merged**
