### PR TITLE
Import yarpmotorgui (a.k.a. robotMotorGui)

### PR DESCRIPTION
**Pull request by drdanz**
Import `yarpmotorgui-gtk` (`robotMotorGui`) from robotology/icub-main (preserving history) and first import of `yarpmotorgui-qt`

### CODE REVIEW

**Comment by drdanz** [comment]
Appveyor failed getting wget, I'm not sure how to restart it...

**Comment by alecive** [comment]
@drdanz the server at http://users.ugent.be/ is up and running. Apparently, though, there is no http://users.ugent.be/~bpuype/wget/wget.exe any more.

**Comment by drdanz** [comment]
We'll have to fix appveyour.yml then...
Anyway, that's not related to the patch, and the 2nd travis build is failing somewhere with opencv

**Comment by pattacini** [comment]
Try to give `Appveyor` more time: similar issues related to `wget` already occurred in the past...

Perhaps we could replace `wget` with a different downloading tool available through `chocolatey`.

**Comment by alecive** [comment]
@pattacini  ..or a different mirror.

**Comment by pattacini** [comment]
This is the [page](http://www.appveyor.com/docs/how-to/download-file)!
Doing attempts with wysiwyd...

**Comment by pattacini** [comment]
@drdanz now appveyor should work

**Comment by drdanz** [comment]
Rebased over latest master. let's see if it works now...

**Comment by drdanz** [comment]
Cool, appveyor iss happy now, travis still fails for some unrelated reason... I'll go on and merge this.

**Pull request merged**
