### PR TITLE
Add controlboardremapper device 

### PR DESCRIPTION
**Pull request by traversaro**
This PR adds a `controlboardremapper` device, that is a state-less and thread-less YARP device that takes axes belonging to several controlboards and expose them as a unique controlboard device. 

Documentation for this device is available in https://github.com/robotology/yarp/compare/master...traversaro:controlBoardRemapper?expand=1#diff-0cc49905f15eea067f04dd71974ce899R32 . 

## Device rationale 
The rationale for this device is that is a that a typical estimation/control application may want to read/write data regarding certain list of joints, that are exposed in different controlboard devices. 

Examples of this pattern include: 
  * The [`controlboardwrapper2`](http://www.yarp.it/classyarp_1_1dev_1_1ControlBoardWrapper.html)  class , that permits to expose several controlboard device in a unique part (like `right_leg`, `left_leg`, etc etc) on the YARP network using the `networks` parameters. 

* The [Cartesian Controller](http://wiki.icub.org/brain/icub_anyrobot_cartesian_interface.html) that support the control of several controlboard belonging to a unique kinematic chain using the `DRIVER` groups. 

* The [yarp-wholeBodyInterface](https://github.com/robotology/yarp-wholebodyinterface/blob/master/examples/yarpWholeBodyInterfaceExample/main.cpp) that permit to control/read data from a set of joints in several controlboards of the robot for whole-body control, but using  a yarp independent C++ interface than the classical YARP controlboards.  

* The [idynutils](https://github.com/robotology-playground/idynutils/blob/e3c3b1b066f9f3c3de9b51243c3dc7782d3d1546/include/idynutils/idynutils.h) that permit to automatically load a kinematic and dynamic model of the robot using [iDynTree](https://github.com/robotology/idyntree) and to automatically read its state using YARP `remote_controlboard`s.

## Device use 
The `controlboardremapper` can be easily used by just specifying the names of the axes that the user wants to control, and by then attaching the controlboard device containing this axes to the `controlboardremapper`. Note that actually attaching the device is tipically done by the `yarprobotinterface`, rather then explicitly in the code, and the `axesNames` option is not hardcoded in the code but passed by a configuration file, but for the sake of the example we assume that everything is hardcoded in the code:
~~~
/ Let's control the root_link --> head 6DOF torso/neck chain of iCub 
Property options;
options.put("device","controlboardremapper");
Bottle axesNames;
Bottle & axesList = axesNames.addList();
axesList.addString("torso_pitch");
axesList.addString("torso_roll");
axesList.addString("torso_yaw");
axesList.addString("neck_pitch");
axesList.addString("neck_roll");
axesList.addString("neck_yaw");
options.put("axesNames",axesNames.get(0))

// Actually open the device 
PolyDriver robotDevice(options);

PolyDriverList p;
// fill the PolyDriverList with the torso/head devices
// ...

// Attach the controlboards to the remapper 
robotDevice.attachAll(p);

// Use it as  you would use any controlboard device
// ...
~~~

The main idea behind this device is that it can easily used to implement a `remapped_remote_controlboard` device, that I still need to write but would be trivial to write with the `controlboardremapper`, but would be used in the following way: 
~~~
/ Let's control the root_link --> head 6DOF torso/neck chain of iCub 
Property options;
options.put("device","remapped_remote_controlboard");
Bottle axesNames;
Bottle & axesList = axesNames.addList();
axesList.addString("torso_pitch");
axesList.addString("torso_roll");
axesList.addString("torso_yaw");
axesList.addString("neck_pitch");
axesList.addString("neck_roll");
axesList.addString("neck_yaw");
options.put("axesNames",axesNames.get(0))

Bottle remotePorts;
Bottle & remotePortsList = remotePorts.addList();
remotePortsList.addString("/icub/torso");
remotePortsList.addString("/icub/head");
options.put("remotePorts",remotePorts.get(0));

// Actually open the device 
PolyDriver robotDevice(options);

// Use it as  you would use any controlboard device
// ...
~~~

Furthermore the `controlboardremapper` can be used to easily implement control/estimation loops that use the wholebody model of the robot directly in a YARP device, without using any network communication. An example is the experimental `wholeBodyDynamics` device for torque estimation implemented in https://github.com/robotology/codyco-modules/pull/180 (actual class code: https://github.com/robotology/codyco-modules/blob/wholeBodyDynamicsDevice/src/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp and https://github.com/robotology/codyco-modules/blob/wholeBodyDynamicsDevice/src/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.h ). Preliminary test show that (rather unexpectedly) the computational burden on the iCub PC104 decreases by  using the wholeBodyDynamicsDevice directly in the `yarprobotinterface` rather then having a `wholeBodyDynamics(Tree)` module running on the external computer. This is due to the fact that the YARP communication involved in publishing the robot state on the network to an external module are much more computational expensive then doing the (relatively computational inexpensive) dynamics computations onboard. 

## Device implementation details 
The idea is to provide a pure YARP device (no network communication involved!) to permit to easily implement this pattern using just YARP and no external dependencies. The code is based on the `controlboadwrapper2` device, but was modified to achieve a cleaner design,. 
The main differences include: 
* The remapping is based on just a list of `axesNames` that the user wants to control, that are matched with the underling controlboards using the [IAxisInfo::getAxisName](http://www.yarp.it/classyarp_1_1dev_1_1IAxisInfo.html#a2838e373c8d69fb5770d11c885061836). This permits a easier configuration of the device.
* The new interfaces with multi-axis methods (`IPositionControl2`, `IVelocityControl2`, etc etc) and the `IAxisInfo` interface are required.
* No thread is running associated with this device. All the calls to the `controlboardremapper` device as simply remapped in the subcontrolboards calls. Some convenience buffers are present in the class to simplify this "remapping", but not state information is saved in the class.
* If a method as a multi-axis version available (the one with the `(const int n_joint, const int * joints, double * refs)` signature, such as [1]) then all the methods in the controlboardremapper are using the multiaxis  methods, ensuring efficiency if for example the method is using the network interface (for example if the `controlboardremapper` is wrapping several `remote_controlboard`s). 
* If a method has no multi-axis version (as for example [`setPIDs`](http://www.yarp.it/classyarp_1_1dev_1_1IPidControl.html#a955fcd226a397f39ffd323a2e54e2364) method) then the single axis method is always called. This may result in a small inefficiency, but given that most of the methods that don't have multiaxis methods are not mean to be used in control/estimation loops, this should not be a problem. 
* The [`IRemoteVariables`](http://www.yarp.it/classyarp_1_1dev_1_1IRemoteVariables.html) is not remapped, but given that is just used for debugging it should not be a big problem. 
* Some calibrator-specific code was removed, but it could be added later. 

[1] : [`virtual bool yarp::dev::IPositionDirect::setPositions(const int n_joint, const int * joints, double *  	refs)`](http://www.yarp.it/classyarp_1_1dev_1_1IPositionDirect.html#a9eb093e4ab1e2684d9059981b8e0519c)

## Device testing 
Not complete tests for the `controlboardremapper` have been added in https://github.com/robotology/codyco-modules/pull/180 . This test use the `fakeMotionControl` device, that I  moved to the devices that are compiled directly in YARP as I was unable to make the test work with `fakeMotionControl` as an external dynamically compiled plugin.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/746%23issuecomment-215954920%22%2C%20%22https%3A//github.com/robotology/yarp/pull/746%23issuecomment-215955373%22%2C%20%22https%3A//github.com/robotology/yarp/pull/746%23issuecomment-216167158%22%2C%20%22https%3A//github.com/robotology/yarp/pull/746%23issuecomment-216567642%22%2C%20%22https%3A//github.com/robotology/yarp/pull/746%23issuecomment-216583860%22%2C%20%22https%3A//github.com/robotology/yarp/pull/746%23issuecomment-216872548%22%2C%20%22https%3A//github.com/robotology/yarp/pull/746%23issuecomment-217304450%22%2C%20%22https%3A//github.com/robotology/yarp/pull/746%23issuecomment-219277420%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/746%23issuecomment-215954920%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Slightly%20unrelated%20question%20for%20YARP%20experts.%20I%20find%20that%20the%20way%20of%20adding%20a%20vector%20of%20strings%20to%20a%20%60yarp%3A%3Aos%3A%3AProperty%60%20is%20rather%20counterintuitive%3A%20%5Cr%5Cn%7E%7E%7E%5Cr%5Cnoptions.addGroup%28%5C%22axesNames%5C%22%29%3B%5Cr%5CnBottle%20%26%20axesList%20%3D%20options.findGroup%28%5C%22axesNames%5C%22%29.addList%28%29%3B%5Cr%5CnaxesList.addString%28%5C%22torso_pitch%5C%22%29%3B%5Cr%5CnaxesList.addString%28%5C%22torso_roll%5C%22%29%3B%5Cr%5CnaxesList.addString%28%5C%22torso_yaw%5C%22%29%3B%5Cr%5CnaxesList.addString%28%5C%22neck_pitch%5C%22%29%3B%5Cr%5CnaxesList.addString%28%5C%22neck_roll%5C%22%29%3B%5Cr%5CnaxesList.addString%28%5C%22neck_yaw%5C%22%29%3B%5Cr%5Cn%7E%7E%7E%5Cr%5CnAnyone%20has%20a%20better%20alternative%3F%20Perhaps%20we%20could%20implement%20a%20specific%20function%20in%20%60yarp%3A%3Aos%3A%3AProperties%60%3F%22%2C%20%22created_at%22%3A%20%222016-04-30T10%3A56%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40traversaro%20%5Cr%5Cn%5Cr%5CnI%20usually%20do%20something%20like%20the%20following%3A%5Cr%5Cn%5Cr%5Cn%60%60%60cpp%5Cr%5CnBottle%20axesNames%3B%5Cr%5CnBottle%20%26axesList%3DaxesNames.addList%28%29%3B%5Cr%5CnaxesList.addString%28%5C%22torso_pitch%5C%22%29%3B%5Cr%5Cn//%20...%5Cr%5CnProperty%20prop%3B%5Cr%5Cnprop.put%28%5C%22axesNames%5C%22%2CaxesNames.get%280%29%29%3B%5Cr%5Cn%60%60%60%22%2C%20%22created_at%22%3A%20%222016-04-30T11%3A05%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%20useful%20device%22%2C%20%22created_at%22%3A%20%222016-05-02T09%3A18%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4137836%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/iron76%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40traversaro%20I%20was%20able%20to%20get%20the%20test%20working%20as%20a%20plugin%2C%20so%20I%20don%27t%20see%20a%20very%20good%20reason%20for%20moving%20the%20fakeMotionControl...%20There%20is%20some%20bug%20in%20the%20fakeMotionControl%20device%20that%20you%20fixed%20while%20moving%20it%21%20Please%20make%20sure%20you%20do%20it%20in%202%20separate%20commits%20next%20time%2C%20as%20it%20will%20make%20it%20a%20lot%20easier%20to%20debug%21%5Cr%5Cn%5Cr%5CnThis%20commit%20reverts%20the%20device%20move%2C%20but%20imports%20your%20changes%20to%20the%20device%3A%20https%3A//github.com/drdanz/yarp/commit/bb4986c3cc9396ea58a9f9bd92c04fc29118f85b.%20I%20suggest%20you%20to%20squash%20this%20commit%20to%20https%3A//github.com/robotology/yarp/pull/746/commits/827fb2aeac279bb5fef85366d8e0d818fb535293%2C%20and%20to%20add%20some%20check%20to%20enable%20the%20test%20only%20when%20the%20fakeMotionControl%20device%20is%20enabled.%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-05-03T15%3A32%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40drdanz%20thanks%20a%20lot%2C%20sorry%20for%20the%20change%20hidden%20in%20the%20move%2C%20that%20was%20definitely%20evil%21%22%2C%20%22created_at%22%3A%20%222016-05-03T16%3A23%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40drdanz%20done.%20%22%2C%20%22created_at%22%3A%20%222016-05-04T13%3A56%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22Added%20more%20tests%20and%20fixed%20some%20bugs.%20CI%20is%20currently%20failing%20because%20YARP%20is%20enable%20to%20find%20its%20own%20plugin%20without%20setting%20the%20YARP_DATA_DIRS%2C%20I%20don%27t%20have%20a%20clear%20idea%20on%20how%20to%20achieve%20this%20automatically%20%28I%20assume%20that%20requiring%20an%20enviromental%20variable%20to%20be%20set%20to%20have%20the%20tests%20to%20pass%20would%20be%20undesirable%2C%20right%3F%29%22%2C%20%22created_at%22%3A%20%222016-05-05T23%3A00%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40drdanz%20should%20I%20retarget%20this%20to%20%60devel%60%3F%20%22%2C%20%22created_at%22%3A%20%222016-05-15T10%3A28%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/746#issuecomment-215954920'>General Comment</a></b>
- <a href='https://github.com/traversaro'></a> Slightly unrelated question for YARP experts. I find that the way of adding a vector of strings to a `yarp::os::Property` is rather counterintuitive:
~~~
options.addGroup("axesNames");
Bottle & axesList = options.findGroup("axesNames").addList();
axesList.addString("torso_pitch");
axesList.addString("torso_roll");
axesList.addString("torso_yaw");
axesList.addString("neck_pitch");
axesList.addString("neck_roll");
axesList.addString("neck_yaw");
~~~
Anyone has a better alternative? Perhaps we could implement a specific function in `yarp::os::Properties`?
- <a href='https://github.com/pattacini'></a> @traversaro
I usually do something like the following:
```cpp
Bottle axesNames;
Bottle &axesList=axesNames.addList();
axesList.addString("torso_pitch");
// ...
Property prop;
prop.put("axesNames",axesNames.get(0));
```
- <a href='https://github.com/iron76'></a> :+1 useful device
- <a href='https://github.com/drdanz'></a> @traversaro I was able to get the test working as a plugin, so I don't see a very good reason for moving the fakeMotionControl... There is some bug in the fakeMotionControl device that you fixed while moving it! Please make sure you do it in 2 separate commits next time, as it will make it a lot easier to debug!
This commit reverts the device move, but imports your changes to the device: https://github.com/drdanz/yarp/commit/bb4986c3cc9396ea58a9f9bd92c04fc29118f85b. I suggest you to squash this commit to https://github.com/robotology/yarp/pull/746/commits/827fb2aeac279bb5fef85366d8e0d818fb535293, and to add some check to enable the test only when the fakeMotionControl device is enabled.
- <a href='https://github.com/traversaro'></a> @drdanz thanks a lot, sorry for the change hidden in the move, that was definitely evil!
- <a href='https://github.com/traversaro'></a> @drdanz done.
- <a href='https://github.com/traversaro'></a> Added more tests and fixed some bugs. CI is currently failing because YARP is enable to find its own plugin without setting the YARP_DATA_DIRS, I don't have a clear idea on how to achieve this automatically (I assume that requiring an enviromental variable to be set to have the tests to pass would be undesirable, right?)
- <a href='https://github.com/traversaro'></a> @drdanz should I retarget this to `devel`?

<a href='https://www.codereviewhub.com/robotology/yarp/pull/746?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/746?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/746'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/746'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by traversaro** [comment]
Slightly unrelated question for YARP experts. I find that the way of adding a vector of strings to a `yarp::os::Property` is rather counterintuitive: 
~~~
options.addGroup("axesNames");
Bottle & axesList = options.findGroup("axesNames").addList();
axesList.addString("torso_pitch");
axesList.addString("torso_roll");
axesList.addString("torso_yaw");
axesList.addString("neck_pitch");
axesList.addString("neck_roll");
axesList.addString("neck_yaw");
~~~
Anyone has a better alternative? Perhaps we could implement a specific function in `yarp::os::Properties`?

**Comment by pattacini** [comment]
@traversaro 

I usually do something like the following:

```cpp
Bottle axesNames;
Bottle &axesList=axesNames.addList();
axesList.addString("torso_pitch");
// ...
Property prop;
prop.put("axesNames",axesNames.get(0));
```

**Comment by traversaro** [comment]
@pattacini , thanks, I prefer your way as it avoids the use of `addGroup`,  I am modifying the examples to match your style.

**Comment by iron76** [comment]
:+1 useful device

**Comment by drdanz** [comment]
@traversaro I was able to get the test working as a plugin, so I don't see a very good reason for moving the fakeMotionControl... There is some bug in the fakeMotionControl device that you fixed while moving it! Please make sure you do it in 2 separate commits next time, as it will make it a lot easier to debug!

This commit reverts the device move, but imports your changes to the device: https://github.com/drdanz/yarp/commit/bb4986c3cc9396ea58a9f9bd92c04fc29118f85b. I suggest you to squash this commit to https://github.com/robotology/yarp/pull/746/commits/827fb2aeac279bb5fef85366d8e0d818fb535293, and to add some check to enable the test only when the fakeMotionControl device is enabled.

**Comment by traversaro** [comment]
@drdanz thanks a lot, sorry for the change hidden in the move, that was definitely evil!

**Comment by traversaro** [comment]
@drdanz done.

**Comment by traversaro** [comment]
Added more tests and fixed some bugs. CI is currently failing because YARP is enable to find its own plugin without setting the YARP_DATA_DIRS, I don't have a clear idea on how to achieve this automatically (I assume that requiring an enviromental variable to be set to have the tests to pass would be undesirable, right?)

**Comment by traversaro** [comment]
@drdanz should I retarget this to `devel`?

**Pull request closed without merging**
