### PR TITLE
More CMake fixes

### PR DESCRIPTION
**Pull request by drdanz**
Should fix the issues caused by #1976 (CC @PeterBowman)

Important changes:

* The `yarp/conf/options.h` header file is deprecated.
* The `CREATE_LIB_MATH` CMake option was renamed `YARP_COMPILE_libYARP_math`.
* The `CREATE_GUIS` CMake option was renamed `YARP_COMPILE_GUIS`.
* All the `CREATE_<UPPERCASE_EXECUTABLE>` were renamed
  `YARP_COMPILE_<lowercase-executable>`
* All the `YARP_USE_<UPPERCASEPACKAGENAME>` were renamed
  `YARP_USE_<PackageName>`
* All the `YARP_USE_SYSTEM_<UPPERCASEPACKAGENAME>` were renamed
  `YARP_USE_SYSTEM_<PackageName>`
* All the internal CMake variables related to packages now use the same case
  as the relative CMake module (i.e. `YARP_HAS_OpenCV` instead of
  `YARP_HAS_OPENCV`)

### CODE REVIEW

**Comment by PeterBowman** [comment]
Regarding my comment at https://github.com/robotology/yarp/pull/1976#issuecomment-474934125, Travis suddenly stops showing CMake configure output before it reaches the previously erroring lines ([devel](https://travis-ci.org/roboticslab-uc3m/kinematics-dynamics/builds/509382038), [devel+fix](https://travis-ci.org/roboticslab-uc3m/kinematics-dynamics/builds/509386963)). I tried to replicate that on my local machine (no ACE installed, math lib enabled) and YARP is successfully configured, though.

**Comment by drdanz** [comment]
The devel+fix build error looks like a bug in travis, do you mind restarting it to see if it produces the same output?

**Comment by drdanz** [comment]
@PeterBowman ^

**Comment by PeterBowman** [comment]
Got it now after applying the fix described at https://github.com/travis-ci/travis-ci/issues/6018. Error message ([Travis](https://travis-ci.org/roboticslab-uc3m/kinematics-dynamics/jobs/509417730#L1229)):

```
CMake Error at cmake/YarpFindDependencies.cmake:167 (message):
  Optional package TinyXML not found.  Please install it or disable the
  option "YARP_COMPILE_libYARP_manager" to build yarp.
Call Stack (most recent call first):
  cmake/YarpFindDependencies.cmake:527 (check_optional_dependency)
  CMakeLists.txt:76 (include)
```

**Comment by drdanz** [comment]
Ok, at least there is an error :laughing:

**Comment by drdanz** [comment]
@PeterBowman Unfortunately I don't have many clues here, but I think I found the issue (see f0a381783917f4573b696d50451f6b3175d5f142)
Can you please try once more?

**Comment by PeterBowman** [comment]
@drdanz Travis is happy now ([ref](https://travis-ci.org/roboticslab-uc3m/kinematics-dynamics/builds/509479771)), thanks!

**Comment by drdanz** [comment]
Valgrind failures are unrelated. Merging

**Comment by PeterBowman** [comment]
@drdanz sorry, didn't check these new fixes on a project that does not install Eigen. If Eigen is **not** present, YARP tries to compile its math component anyway (and fails at it): [ref](https://travis-ci.org/roboticslab-uc3m/tools/jobs/511683349). No additional CMake config options, just `-DSKIP_ACE:BOOL=ON`.

**Comment by drdanz** [comment]
@PeterBowman thanks for reporting it, I'll try tomorrow

**Comment by drdanz** [comment]
@PeterBowman Should be fixed now, see 92c3ab430e2ecac8a5a55848bb7868eee28d0fee

**Comment by PeterBowman** [comment]
@drdanz thanks, I restarted [this job](https://travis-ci.org/roboticslab-uc3m/tools/jobs/511683349). Travis is partially down right now, I'll let you know of any further failure as soon as the job is run.

**Pull request merged**
