### PR TITLE
Tests: Small refactor, return 2 when a test is not found

### PR DESCRIPTION
**Pull request by drdanz**
The result value is checked using the SKIP_RETURN_CODE CMake test property

### CODE REVIEW

**Comment by drdanz** [comment]
Thanks to this I noticed that `dev::robotDescriptionTest` is always skipped...
I enabled it in a separate commit...

**Comment by drdanz** [comment]
Enabled also `math::svdTest`, let's see if it fails.
`run::RunTest` is not executed on purpose (because it is broken).

**Comment by Nicogene** [comment]
Great improvement! :muscle: 

On `linux` fails:
```
124 - math::svdTest::Valgrind::MemCheck (Failed)
```
There is some memory leak, It shouldn't be difficult to fix it.

And on `macOS`: 
```
56 - dev::robotDescriptionTest (SEGFAULT)
```
A question not related to this PR, why `PeriodicThreadTest` is disabled on `macOS` ?

**Comment by drdanz** [comment]
> 124 - math::svdTest::Valgrind::MemCheck (Failed)

Not a leak but an invalid read, should be fixed in (b1bf61bb94651423cef390baf830332b8e74b2ac)

@traversaro Can you check if the fix looks correct to you?

**Comment by traversaro** [comment]
The fix seems correct.

**Comment by drdanz** [comment]
I cannot understand the issue with `robotDescriptionClient` apparently the `open` method returns true but the `view` as `IRobotDescription` fails

**Comment by traversaro** [comment]
> I cannot understand the issue with `robotDescriptionClient` apparently the `open` method returns true but the `view` as `IRobotDescription` fails

I had similar problems if the inheritance was not public or similar.

**Comment by drdanz** [comment]
> I had similar problems if the inheritance was not public or similar.

It does not look the issue here:

```c++
class yarp::dev::RobotDescriptionClient : public DeviceDriver,
                                          public IRobotDescription
```

Also I don't see a reason why it should work on linux and fail on macOS...

**Comment by traversaro** [comment]
`YARP_dev_API` is missing? 
See https://github.com/robotology/yarp/pull/824 .

**Comment by drdanz** [comment]
> `YARP_dev_API` is missing?

:heart: 

Thanks @traversaro, `YARP_dev_API` is actually missing in `IRobotDescription`... That's probably the reason... Let's try and see if it fixes the builds

**Comment by drdanz** [comment]
> Should we add a line in the changelog for 89f816e ?

Done

**Pull request merged**
