### PR TITLE
small fix in RGBDSensorWrapper

### PR DESCRIPTION
**Pull request by valegagge**
swapped the init strings of color and depth parameters in order to maintain their meaning

### CODE REVIEW

**Comment by drdanz** [comment]
Right, this should be on `master`... @valegagge please move your branch on master (see robotology/QA#168).
Also it's probably worth a line in the release notes.

**Comment by valegagge** [comment]
@drdanz Is it necessary update the change log also for this small change? :)

**Comment by valegagge** [comment]
I think this is not a bug fix , but only a fix to make more readable the code. The code works fine even if without this change. For this reason, I used devel branch instead of master, but if you (@drdanz  and @Nicogene ) prefer, I can move the commit on master.

**Comment by drdanz** [comment]
Merged, thanks!

**Comment by valegagge** [comment]
Ok thanks

**Pull request merged**
