### PR TITLE
Avoid timeout in travis. Partfial fix for #867

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
This should avoid timeouts in the integration::runtime test. It's not a full fix for #867, but a first step :+1:.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240053114%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240053555%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240065038%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240065244%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240067530%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240072618%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240073268%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240073457%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240074200%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240074561%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240154256%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240343128%22%2C%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240343376%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/868%23issuecomment-240053114%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40Tobias-Fischer%20Unfortunately%20osx%20builds%20are%20currently%20failing%20due%20to%20some%20issue%20with%20brew.%5Cr%5CnIf%20%23869%20builds%2C%20I%20will%20merge%20that%20first%2C%20then%20this%20one%20will%20follow.%5Cr%5Cn%5Cr%5CnAnyway%2C%20about%20the%20patch%2C%20I%20have%20a%20doubt...%20the%20%60check-runtime.sh%60%20script%20is%20executed%20by%20%60ctest%60%2C%20that%20hides%20the%20output%20of%20anything%20it%20executes%2C%20are%20you%20sure%20that%20this%20string%20is%20actually%20printed%3F%5Cr%5Cn%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-16T09%3A32%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22By%20the%20way%2C%20apparently%20there%20are%20still%20random%20test%20fails%2C%20see%20%5B2484.2%5D%28https%3A//travis-ci.org/robotology/yarp/jobs/152353997%29%20and%20%5B2484.24%5D%28https%3A//travis-ci.org/robotology/yarp/jobs/152354037%29%20%3Acry%3A%20%22%2C%20%22created_at%22%3A%20%222016-08-16T09%3A34%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22Very%20true%2C%20please%20don%27t%20merge%20this%20PR%20yet.%20Not%20sure%20whether%20the%20output%20is%20hidden%2C%20I%27ll%20check%20this.%20Maybe%20there%27s%20another%20way%20to%20enforce%20output%20only%20for%20this%20test.%22%2C%20%22created_at%22%3A%20%222016-08-16T10%3A28%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Regarding%20%5B2484.2%5D%28https%3A//travis-ci.org/robotology/yarp/jobs/152353997%29%3A%20I%20haven%27t%20seen%20this%20segfault%20before.%20Is%20there%20already%20an%20issue%20about%20this%3F%22%2C%20%22created_at%22%3A%20%222016-08-16T10%3A29%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Do%20you%20think%20moving%20%60%5B%20-n%20%5C%22%24TRAVIS%5C%22%20%5D%20%26%26%20while%20true%3B%20do%20echo%20%5C%22...%5C%22%3B%20sleep%2060%3B%20done%20%26%60%20to%20https%3A//github.com/robotology/yarp/blob/master/.travis.yml%23L245%20would%20make%20sense%3F%22%2C%20%22created_at%22%3A%20%222016-08-16T10%3A41%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3E%20Regarding%20%5B2484.2%5D%28https%3A//travis-ci.org/robotology/yarp/jobs/152353997%29%3A%20I%20haven%27t%20seen%20this%20segfault%20before.%20Is%20there%20already%20an%20issue%20about%20this%3F%5Cr%5Cn%5Cr%5CnI%27ve%20never%20seen%20it%2C%20but%20It%20happened%20again%2C%20see%20%5B2485.8%5D%28https%3A//travis-ci.org/robotology/yarp/jobs/152622262%29.%20I%27m%20afraid%20this%20was%20caused%20by%20some%20recent%20change...%22%2C%20%22created_at%22%3A%20%222016-08-16T11%3A09%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3E%20Do%20you%20think%20moving%20%5B%20-n%20%5C%22%24TRAVIS%5C%22%20%5D%20%26%26%20while%20true%3B%20do%20echo%20%5C%22...%5C%22%3B%20sleep%2060%3B%20done%20%26%20to%20https%3A//github.com/robotology/yarp/blob/master/.travis.yml%23L245%20would%20make%20sense%3F%5Cr%5Cn%5Cr%5CnI%27d%20rather%20use%20%60travis_wait%60%20instead...%22%2C%20%22created_at%22%3A%20%222016-08-16T11%3A13%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22i.e.%20something%20like%20this%2C%20perhaps%3A%5Cr%5Cn%5Cr%5Cn%60%60%60diff%5Cr%5Cn-%20-%20%28cd%20build%3B%20ctest%20--output-on-failure%20--build%20.%20-C%20%24%7BTRAVIS_BUILD_TYPE%7D%29%5Cr%5Cn%2B%20-%20%28cd%20build%3B%20travis_wait%20ctest%20--output-on-failure%20--build%20.%20-C%20%24%7BTRAVIS_BUILD_TYPE%7D%29%5Cr%5Cn%60%60%60%22%2C%20%22created_at%22%3A%20%222016-08-16T11%3A14%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20%60travis_wait%60%20only%20works%20for%20the%20paid%20service%20%28travis-ci.com%29%20%3A%28%20..%20but%20we%20can%20try.%22%2C%20%22created_at%22%3A%20%222016-08-16T11%3A18%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Seems%20like%20other%20people%20using%20travis-ci.org%20are%20using%20this%3A%20https%3A//github.com/bioconda/bioconda-recipes/pull/349/files%5Cr%5CnSo%20let%27s%20try%20%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222016-08-16T11%3A20%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22%60travis_wait%60%20seems%20to%20be%20working%20fine%3A%20https%3A//travis-ci.org/robotology/yarp/jobs/152676379%22%2C%20%22created_at%22%3A%20%222016-08-16T16%3A17%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%20%40drdanz%2C%5Cr%5CnIt%20seems%20like%20both%20the%20%60timeout%60%20for%20the%20cache%20as%20well%20as%20%60travis_wait%60%20for%20the%20tests%20are%20working%20nicely.%20%5Cr%5CnRegarding%20%60travis_wait%60%2C%20the%20log%20output%20has%20changed%2C%20so%20I%27m%20sure%20this%20is%20working.%5Cr%5CnRegarding%20the%20%60timeout%60%2C%20it%20is%20correctly%20shown%20in%20the%20config%20of%20the%20job%2C%20so%20I%20guess%20it%27s%20also%20working.%5Cr%5CnOne%20job%20still%20failed%20due%20to%20a%20failed%20%60integration%3A%3Arpc%60%20test%2C%20but%20this%20can%20be%20tackled%20separately.%5Cr%5Cn%5Cr%5CnSo%20I%20guess%20this%20is%20worth%20merging%2C%20and%20then%20we%20can%20see%20whether%20we%27ll%20see%20timeouts%20in%20the%20future.%5Cr%5Cn%5Cr%5CnBest%2C%20Tobi%22%2C%20%22created_at%22%3A%20%222016-08-17T08%3A10%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22PS%3A%20Maybe%20it%27s%20worth%20squashing%20the%20PR%20into%20one%20commit%20when%20merging.%22%2C%20%22created_at%22%3A%20%222016-08-17T08%3A11%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/868#issuecomment-240053114'>General Comment</a></b>
- <a href='https://github.com/drdanz'></a> @Tobias-Fischer Unfortunately osx builds are currently failing due to some issue with brew.
If #869 builds, I will merge that first, then this one will follow.
Anyway, about the patch, I have a doubt... the `check-runtime.sh` script is executed by `ctest`, that hides the output of anything it executes, are you sure that this string is actually printed?
- <a href='https://github.com/drdanz'></a> By the way, apparently there are still random test fails, see [2484.2](https://travis-ci.org/robotology/yarp/jobs/152353997) and [2484.24](https://travis-ci.org/robotology/yarp/jobs/152354037) :cry:
- <a href='https://github.com/Tobias-Fischer'></a> Very true, please don't merge this PR yet. Not sure whether the output is hidden, I'll check this. Maybe there's another way to enforce output only for this test.
- <a href='https://github.com/Tobias-Fischer'></a> Regarding [2484.2](https://travis-ci.org/robotology/yarp/jobs/152353997): I haven't seen this segfault before. Is there already an issue about this?
- <a href='https://github.com/Tobias-Fischer'></a> Do you think moving `[ -n "$TRAVIS" ] && while true; do echo "..."; sleep 60; done &` to https://github.com/robotology/yarp/blob/master/.travis.yml#L245 would make sense?
- <a href='https://github.com/drdanz'></a> > Regarding [2484.2](https://travis-ci.org/robotology/yarp/jobs/152353997): I haven't seen this segfault before. Is there already an issue about this?
I've never seen it, but It happened again, see [2485.8](https://travis-ci.org/robotology/yarp/jobs/152622262). I'm afraid this was caused by some recent change...
- <a href='https://github.com/drdanz'></a> > Do you think moving [ -n "$TRAVIS" ] && while true; do echo "..."; sleep 60; done & to https://github.com/robotology/yarp/blob/master/.travis.yml#L245 would make sense?
I'd rather use `travis_wait` instead...
- <a href='https://github.com/drdanz'></a> i.e. something like this, perhaps:
```diff
- - (cd build; ctest --output-on-failure --build . -C ${TRAVIS_BUILD_TYPE})
+ - (cd build; travis_wait ctest --output-on-failure --build . -C ${TRAVIS_BUILD_TYPE})
```
- <a href='https://github.com/Tobias-Fischer'></a> I think `travis_wait` only works for the paid service (travis-ci.com) :( .. but we can try.
- <a href='https://github.com/Tobias-Fischer'></a> Seems like other people using travis-ci.org are using this: https://github.com/bioconda/bioconda-recipes/pull/349/files
So let's try :+1:
- <a href='https://github.com/Tobias-Fischer'></a> `travis_wait` seems to be working fine: https://travis-ci.org/robotology/yarp/jobs/152676379
- <a href='https://github.com/Tobias-Fischer'></a> Hi @drdanz,
It seems like both the `timeout` for the cache as well as `travis_wait` for the tests are working nicely.
Regarding `travis_wait`, the log output has changed, so I'm sure this is working.
Regarding the `timeout`, it is correctly shown in the config of the job, so I guess it's also working.
One job still failed due to a failed `integration::rpc` test, but this can be tackled separately.
So I guess this is worth merging, and then we can see whether we'll see timeouts in the future.
Best, Tobi
- <a href='https://github.com/Tobias-Fischer'></a> PS: Maybe it's worth squashing the PR into one commit when merging.

<a href='https://www.codereviewhub.com/robotology/yarp/pull/868?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/868?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/868'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/868'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by drdanz** [comment]
@Tobias-Fischer Unfortunately osx builds are currently failing due to some issue with brew.
If #869 builds, I will merge that first, then this one will follow.

Anyway, about the patch, I have a doubt... the `check-runtime.sh` script is executed by `ctest`, that hides the output of anything it executes, are you sure that this string is actually printed?

**Comment by drdanz** [comment]
By the way, apparently there are still random test fails, see [2484.2](https://travis-ci.org/robotology/yarp/jobs/152353997) and [2484.24](https://travis-ci.org/robotology/yarp/jobs/152354037) :cry:

**Comment by Tobias-Fischer** [comment]
Very true, please don't merge this PR yet. Not sure whether the output is hidden, I'll check this. Maybe there's another way to enforce output only for this test.

**Comment by Tobias-Fischer** [comment]
Regarding [2484.2](https://travis-ci.org/robotology/yarp/jobs/152353997): I haven't seen this segfault before. Is there already an issue about this?

**Comment by Tobias-Fischer** [comment]
Do you think moving `[ -n "$TRAVIS" ] && while true; do echo "..."; sleep 60; done &` to https://github.com/robotology/yarp/blob/master/.travis.yml#L245 would make sense?

**Comment by drdanz** [comment]
> Regarding [2484.2](https://travis-ci.org/robotology/yarp/jobs/152353997): I haven't seen this segfault before. Is there already an issue about this?

I've never seen it, but It happened again, see [2485.8](https://travis-ci.org/robotology/yarp/jobs/152622262). I'm afraid this was caused by some recent change...

**Comment by drdanz** [comment]
> Do you think moving [ -n "$TRAVIS" ] && while true; do echo "..."; sleep 60; done & to https://github.com/robotology/yarp/blob/master/.travis.yml#L245 would make sense?

I'd rather use `travis_wait` instead...

**Comment by drdanz** [comment]
i.e. something like this, perhaps:

```diff
- - (cd build; ctest --output-on-failure --build . -C ${TRAVIS_BUILD_TYPE})
+ - (cd build; travis_wait ctest --output-on-failure --build . -C ${TRAVIS_BUILD_TYPE})
```

**Comment by Tobias-Fischer** [comment]
I think `travis_wait` only works for the paid service (travis-ci.com) :( .. but we can try.

**Comment by Tobias-Fischer** [comment]
Seems like other people using travis-ci.org are using this: https://github.com/bioconda/bioconda-recipes/pull/349/files
So let's try :+1:

**Comment by Tobias-Fischer** [comment]
`travis_wait` seems to be working fine: https://travis-ci.org/robotology/yarp/jobs/152676379

**Comment by Tobias-Fischer** [comment]
Hi @drdanz,
It seems like both the `timeout` for the cache as well as `travis_wait` for the tests are working nicely. 
Regarding `travis_wait`, the log output has changed, so I'm sure this is working.
Regarding the `timeout`, it is correctly shown in the config of the job, so I guess it's also working.
One job still failed due to a failed `integration::rpc` test, but this can be tackled separately.

So I guess this is worth merging, and then we can see whether we'll see timeouts in the future.

Best, Tobi

**Comment by Tobias-Fischer** [comment]
PS: Maybe it's worth squashing the PR into one commit when merging.

**Comment by drdanz** [comment]
I'm not sure if the cache timeout is really necessary, anyway it shouldn't do any harm!

Squashed and merged! Thanks!

**Pull request merged**
