### PR TITLE
grabber rename

### PR DESCRIPTION
**Pull request by randaz81**
Some grabber files renamed for consistency. No functional changes.

### CODE REVIEW

**Review by Nicogene — COMMENTED** [review]
Ok with that, then the `ServerGrabber` `ServerGrabberResponder` classes remain unchanged?

**Review by drdanz — APPROVED** [review]

**Comment by drdanz** [comment]
> Ok with that, then the `ServerGrabber` `ServerGrabberResponder` classes remain unchanged?

I don't have an opinion on that... I think the problem came from the fact that the folder name was really confusing.
Feel free to rename them as well, if you want, or to merge the patch.

**Comment by drdanz** [comment]
Merged, thanks.

**Pull request merged**
