### PR TITLE
Added SystemInfo implementation for macOS

### PR DESCRIPTION
**Pull request by francesco-romano**
I open the PR to track the work, otherwise it gets lost in the various branches.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/799%23issuecomment-227176154%22%2C%20%22https%3A//github.com/robotology/yarp/pull/799%23issuecomment-227247914%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/799%23issuecomment-227176154%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Ready%20to%20merge.%5Cr%5Cn%40apaikan%20can%20you%20check%20this%20PR%3F%22%2C%20%22created_at%22%3A%20%222016-06-20T15%3A26%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2189180%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/francesco-romano%22%7D%7D%2C%20%7B%22body%22%3A%20%22Any%20feedback%20from%20%40apaikan%20about%20the%20correctness%20of%20the%20info%3F%22%2C%20%22created_at%22%3A%20%222016-06-20T19%3A43%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/14168673%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/claudiofantacci%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/799#issuecomment-227176154'>General Comment</a></b>
- <a href='https://github.com/francesco-romano'></a> Ready to merge.
@apaikan can you check this PR?
- <a href='https://github.com/claudiofantacci'></a> Any feedback from @apaikan about the correctness of the info?

<a href='https://www.codereviewhub.com/robotology/yarp/pull/799?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/799?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/799'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/799'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by francesco-romano** [comment]
Ready to merge.
@apaikan can you check this PR?

**Comment by claudiofantacci** [comment]
Any feedback from @apaikan about the correctness of the info?

**Comment by drdanz** [comment]
Merged, it was touching only macOS stuff anyway...

**Pull request merged**
