### PR TITLE
Fix bug in yarp::sig::Sound append (+= operator)

### PR DESCRIPTION
**Pull request by barbalberto**
+= operator was not working correctly, this PR fix it.
A test is also been added in harness_sig

### CODE REVIEW

**Comment by drdanz** [comment]
Please add a line to the file doc/release/v2_3_72_1.md

**Comment by barbalberto** [comment]
Updated changelog

**Comment by drdanz** [comment]
Merged, thanks.

**Comment by pattacini** [comment]
Getting the following compilation error just after a pull:
```
3>c:\dev\yarp\src\libyarp_sig\src\sound.cpp(68): error C2065: 'uint': undeclared identifier
3>c:\dev\yarp\src\libyarp_sig\src\sound.cpp(68): error C2146: syntax error: missing ';' before identifier 's2'
3>c:\dev\yarp\src\libyarp_sig\src\sound.cpp(68): error C2065: 's2': undeclared identifier
3>c:\dev\yarp\src\libyarp_sig\src\sound.cpp(71): error C2065: 's2': undeclared identifier
3>Done building project "YARP_sig.vcxproj" -- FAILED.
```
Lilkely related to this PR (?)

cc @barbalberto @drdanz

**Comment by drdanz** [comment]
Thanks @pattacini

**Pull request merged**
