### PR TITLE
[WIP] Add yarp_configure_installation cmake macro in YarpInstallationHelper.cmake

### PR DESCRIPTION
**Pull request by traversaro**
It is an improved version of `yarp_configure_external_installation` that simplifies management of `YARP_DATA_DIRS` with  lot of projects.

See ChangeLog ( https://github.com/robotology/yarp/compare/devel...traversaro:yarp-configure-installation?expand=1#diff-23698b6c1d5b9ca8a7fbdd49ceca620bR32 ) for detailed discussion of the changes.

### CODE REVIEW

**Comment by traversaro** [comment]
Based on a quick github search @jgvictores is one of the biggest user of  `yarp_configure_external_installation` is @ jgvictores , so I would be happy to know his opinion on this.

**Comment by pattacini** [comment]
@traversaro, this new feature is a nice add-on but, personally, I wouldn't declare `yarp_configure_external_installation` deprecated.

**Comment by traversaro** [comment]
Sorry for the noise guys, but I think I simply got the wrong solution to the problem. `yarp_configure_external_installation` is a widely used function whose main concern is to setup the installation directory with a layout **different** from the usual yarp one (i.e. in `<prefix>/share/<package>` rather then `<prefix>/share/yarp`. 

My main objective is support the use case of installing files using the yarp layout (i.e. using the `YARP_***_INSTALL_DIR` variables ) but installing additionally a `<package>.ini` to `<prefix>/share/yarp/<package>.ini` to make sure that the plugins installed in `YARP_DYNAMIC_PLUGIN_INSTALL_DIR` are correctly found by yarp. As the code relative to the `<package>.ini` generation file is just a small part (disable by default) of `yarp_configure_external_installation` I think it makes more sense to factor out that part is a specific function and call that function from  `yarp_configure_external_installation`.

**Comment by traversaro** [comment]
@drdanz I think that https://github.com/robotology/yarp/pull/1111 is a better alternive, especially because it is much more clear from the function name (`yarp_configure_plugins_installation`) what the function is really about.

**Comment by traversaro** [comment]
I think https://github.com/robotology/yarp/pull/1111 is definitely a better solution, closing this PR.

**Pull request closed without merging**
