### PR TITLE
Add error code in attaching subdevices

### PR DESCRIPTION
**Pull request by Yeshasvitvs**
Add error code in attaching subdevices
@traversaro

### CODE REVIEW

**Comment by Yeshasvitvs** [comment]
@Nicogene yes you are right! Change the base to devel

**Comment by traversaro** [comment]
As it is just some additional debug info, I think `master` would be also ok, but I guess it is @drdanz call.

**Comment by Yeshasvitvs** [comment]
@traversaro Done

**Comment by drdanz** [comment]
Rebased and added release notes

**Comment by drdanz** [comment]
Merged, thanks.

**Pull request merged**
