### PR TITLE
Fix operator conflict

### LINKED ISSUE #2067: Collision between YARP and Casadi
**Describe the bug**
When including both YARP and Casadi there is a redefinition of the operator 
`std::ostream& std::operator<<(std::ostream& os, const std::vector<T>& t)`

here is the error that I get on compilation:

```
/home/emilio/Repositories/robotology-superbuild/build/install/include/yarp/os/LogStream.h:195:22: error: redefinition of ‘template<class T> std::ostream& std::operator<<(std::ostream&, const std::vector<T>&)’
 inline std::ostream& std::operator<<(std::ostream& os, const std::vector<T>& t)
                      ^~~
In file included from /usr/local/include/casadi/core/matrix.hpp:31:0,
                 from /usr/local/include/casadi/core/sx_elem.hpp:33,
                 from /usr/local/include/casadi/core/core.hpp:30,
                 from /usr/local/include/casadi/casadi.hpp:29,
                 from /home/emilio/Repositories/pinocchio-integration/main.cpp:5:
/usr/local/include/casadi/core/casadi_misc.hpp:323:12: note: ‘template<class T> std::ostream& std::operator<<(std::ostream&, const std::vector<T>&)’ previously declared here
   ostream& operator<<(ostream& stream, const vector<T>& v) {
```

**To Reproduce**
Compile the code:
```
#include <yarp/os/all.h>
#include "casadi/casadi.hpp"
int main(){}
```

**Expected behavior**
Correct compilation with both YARP and Casadi libraries available

**Screenshots**
 NA

**Configuration (please complete the following information):**
 - OS: Ubuntu 18.04
 - yarp version: 3.2.0+11-20190716.9+gitd484fdcba
-  compiler: cmake + g++

**Additional context**
 NA

### PR DESCRIPTION
**Pull request by Giulero**
This pull request should fix #2067.
cc @GiulioRomualdi @traversaro

### CODE REVIEW

**Comment by PeterBowman** [comment]
Does the removal of said operator affect in any way the `LogStream` counterpart, i.e. is it still correctly displaying `std::vector`s?

https://github.com/robotology/yarp/blob/13d2bc8ea92621b29055d10c6dbc43809f35c1b0/src/libYARP_os/src/yarp/os/LogStream.h#L224-L230

**Comment by GiulioRomualdi** [comment]
Hi @Giulero checking the CI seems that function you removed is widely used in yarp

**Comment by Giulero** [comment]
@PeterBowman thank you for pointing this out! @GiulioRomualdi, indeed. The removal seems quite harmful.
@traversaro @drdanz how do you suggest to proceed?

**Comment by PeterBowman** [comment]
I think that pasting the body of the deleted function into `LogStream::operator<<(const std::vector<T> &)` should make CI happy.

**Comment by drdanz** [comment]
> @drdanz how do you suggest to proceed?

@PeterBowman [suggestion](https://github.com/robotology/yarp/pull/2421#issuecomment-734517095) is probably the best option

**Comment by drdanz** [comment]
Also I believe that instead of moving the implementation in Types.h might not be needed after moving the implementation...

**Comment by traversaro** [comment]
Sorry for the late response. I totally agree with @drdanz and @PeterBowman , the problem that caused https://github.com/robotology/yarp/issues/2067 is adding new operators in the std namespace, adding new operators for the classes in YARP is totally fine.

**Comment by drdanz** [comment]
Closing this in favour of #2548

**Pull request closed without merging**
