### PR TITLE
[cmake] Properly install YarpPluginPath.cmake

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/icub-main/issues/86

### CODE REVIEW

**Comment by barbalberto** [comment]
I accepted the patch because this file is needed to generate the path.ini for the plugins, so I think is has to be visible from iCub since it is used in the icubmod cmake.

Is it phylosophical correct in your opinion? @paulfitz @lornat75

**Comment by barbalberto** [comment]
Related to this, the part in YarpPlugin.cmake that uses this template to generate the path.ini for build and install, looks like a black magic. For iCub I copied this part in the relative cmake, however I think it could be useful to provide a macro for the user to call, to simplify the creation/usage os a custom plugin library for the user.

The code I'm reffering to is the following:
 # When compiling YARP,
    # Prepare path information for the benefit of clients

    get_target_property(YARP_LIBRARY_PATH YARP_OS LOCATION)
    get_target_property(YARP_LIBRARY_TYPE YARP_OS TYPE)
    string(REPLACE "STATIC_LIBRARY" "static" YARP_LIBRARY_TYPE ${YARP_LIBRARY_TYPE})
    string(REPLACE "SHARED_LIBRARY" "shared" YARP_LIBRARY_TYPE ${YARP_LIBRARY_TYPE})
    get_filename_component(YARP_LIBRARY_EXTENSION ${YARP_LIBRARY_PATH} EXT)
    get_filename_component(YARP_LIBRARY_PREFIX ${YARP_LIBRARY_PATH} NAME_WE)
    string(REPLACE "YARP_OS" "" YARP_LIBRARY_PREFIX ${YARP_LIBRARY_PREFIX})
    get_filename_component(YARP_LIBRARY_PATH ${YARP_LIBRARY_PATH} ABSOLUTE)
    get_filename_component(YARP_LIBRARY_PATH ${YARP_LIBRARY_PATH} PATH)
    configure_file(${YARP_MODULE_DIR}/template/YarpPluginPath.cmake
        ${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_DATADIR}/yarp/plugins/path.ini @ONLY)
    set(YARP_LIBRARY_PATH ${CMAKE_INSTALL_FULL_LIBDIR})
    configure_file(${YARP_MODULE_DIR}/template/YarpPluginPath.cmake
        ${CMAKE_BINARY_DIR}/path_for_install.ini @ONLY)
    install(FILES ${CMAKE_BINARY_DIR}/path_for_install.ini RENAME path.ini COMPONENT configuration DESTINATION ${CMAKE_INSTALL_DATADIR}/yarp/plugins)

**Comment by drdanz** [comment]
In my opinion ``YarpPlugin`` should not do anything different in yarp or outside yarp, therefore that part should just be moved somewhere else, for example in ``YarpInstallationHelper``...

Moreover this part generates a cmake warning for ``get_target_property(YARP_LIBRARY_PATH YARP_OS LOCATION)``, in order to get the absolute path of the package, that cannot actually be known at cmake time. For example if you install YARP doing ``DESTDIR=/foo make install``, yarp will be installed in ``/foo/${CMAKE_INSTALL_PREFIX}``, but the path in the path.ini will be wrong and therefore YARP won't be able to load the plugins. We should aim at removing all the absolute paths and use relative path instead, in order to create a fully relocatable installation. This will also make everything it easier for the windows installer, that requires a lot of effort to keep in sync with the changes in YARP. Unfortunately I'm not sure how to handle it here.

Anyway, regarding the question if it is "phylosophical correct", I don't know... :stuck_out_tongue_winking_eye:, I'd just want to be sure that this is not used anywhere else until we are sure that the file is correct, therefore I'd rather add it to icub-main for now, and revert this patch.

Also, I just noticed that the name of this file is somehow against the philosophy of the other configured files, I'd like to rename it "path.ini.in", or something similar, the `.cmake` extension confuses the editors, anyone against this change? 

By the way, ``YarpPlugin`` does not just look like black magic, it is black magic mixed with voodoo in order to support static plugins, including redefining ``LINK_DIRECTORIES`` and ``FIND_PACKAGE``, sometimes we should get rid of those, and take some time to clean up the plugin generation when YARP is build SHARED

**Comment by paulfitz** [comment]
+1 for renaming `YarpPluginPath.cmake` to `path.ini.in` or similar

**Pull request merged**
