### PR TITLE
A Few Improvements to YarpPlugins.cmake

### PR DESCRIPTION
**Pull request by drdanz**
* ``IMPORTED`` should no longer be used anywhere when calling ``YARP_ADD_PLUGIN``, report an error if it is (preparing for removal in the future)
* Simplify the structure of the file by removing the main ``if`` and returning immediately instead
* Add ``YARP_FORCE_SHARED_PLUGINS`` option to force building plugins as ``SHARED`` even when building static libraries.
* Simplify the creation of the path.ini file and fix the ``AUTHOR_WARNING`` about the use of the ``LOCATION`` property.

### CODE REVIEW

**Comment by paulfitz** [comment]
Looks good, there's a reference to YarpPluginPath.cmake in conf/CMakeLists.txt that needs updating though? I think that is what travis is breaking on.

**Comment by drdanz** [comment]
I know I shouldn't touch YarpPlugins.cmake, it makes me anxious and make me want to change everything... :grimacing:

@paulfitz I fixed the issue and thrown in a lot more stuff...

Basically I moved the creation of the "path.ini" file in ``yarp_configure_external_installation`` to remove some YARP-only stuff in ``YarpPlugin`` so now it can be used for external projects as well...
We can now use

```cmake
yarp_configure_external_installation(foo WITH_PLUGINS)
```

to automatically generate both path.d (when needed) and plugin manifest files.

Since I was touching there, and since I needed some paths to improve the message about the path.d file printed by ``yarp_configure_external_installation`` I felt guilty about the absolute paths in YARPConfig.cmake, therefore I fixed it to have both the absolute and relative paths, but always expressed as relative to the YARPConfig.cmake file in order to make it relocatable.

Finally I cherry-picked a couple of commits from the yarp_add_idl PR (that would have caused an annoying merge conflict), fixed another couple of small issues, and cleaned up some stuff... Commit logs should be self-explanatory.

**Comment by pattacini** [comment]
Problems spotted on Windows. Here's the log:

```
C:\dev\icub-main\build>"C:\Program Files\SlickEditV19.0.1 x64\win\vsbuild" -signal 1297 -command devenv "C:\dev\icub-main\build\iCub.sln" /build "Release" /project "C:\dev\icub-main\build\ALL_BUILD.vcxproj" /projectconfig "Release|Win32"
 VSLICKERRORPATH="C:\dev\icub-main\build"
devenv C:\dev\icub-main\build\iCub.sln /build Release /project C:\dev\icub-main\build\ALL_BUILD.vcxproj /projectconfig "Release|Win32" 

Microsoft (R) Microsoft Visual Studio 2012 Version 11.0.61030.0.
Copyright (C) Microsoft Corp. All rights reserved.
1>------ Build started: Project: ZERO_CHECK, Configuration: Release Win32 ------
1>  Checking Build System
1>  CMake is re-running because C:/dev/icub-main/build/CMakeFiles/generate.stamp is out-of-date.
1>    the file 'C:/dev/yarp/build/YARPConfigVersion.cmake'
1>    is newer than 'C:/dev/icub-main/build/CMakeFiles/generate.stamp.depend'
1>    result='-1'
1>  -- Building for: Visual Studio 12 2013
1>  CMake Error at C:/dev/yarp/build/YARPConfig.cmake:26 (message):
1>    File or directory
1>    C:/dev/yarp/build/bin;C:/dev/yarp/build/bin/Debug;C:/dev/yarp/build/bin/Release
1>    referenced by variable YARP_IDL_BINARY_HINT does not exist !
1>  Call Stack (most recent call first):
1>    C:/dev/yarp/build/YARPConfig.cmake:97 (set_and_check)
1>    CMakeLists.txt:35 (find_package)
1>  
1>  
1>  -- Configuring incomplete, errors occurred!
1>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeOutput.log".
1>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeError.log".
1>  CMake Configure step failed.  Build files cannot be regenerated correctly.  Attempting to stop IDE build.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 1.
2>------ Build started: Project: icubmod, Configuration: Release Win32 ------
3>------ Build started: Project: cluster-scripts, Configuration: Release Win32 ------
4>------ Build started: Project: fingersTuner, Configuration: Release Win32 ------
3>  Copying icub-cluster scripts to C:/dev/icub-main/build/bin/Release
2>  Building Custom Rule C:/dev/icub-main/src/libraries/icubmod/CMakeLists.txt
4>  Building Custom Rule C:/dev/icub-main/src/tools/fingersTuner/CMakeLists.txt
2>  CMake is re-running because C:\dev\icub-main\build\src\libraries\icubmod\CMakeFiles\generate.stamp is out-of-date.
4>  CMake is re-running because C:\dev\icub-main\build\src\tools\fingersTuner\CMakeFiles\generate.stamp is out-of-date.
4>    the file 'C:/dev/yarp/conf/YarpIDL.cmake'
4>    is newer than 'C:\dev\icub-main\build\src\tools\fingersTuner\CMakeFiles\generate.stamp.depend'
4>    result='-1'
4>  -- Building for: Visual Studio 12 2013
4>  CMake Error at C:/dev/yarp/build/YARPConfig.cmake:26 (message):
4>    File or directory
4>    C:/dev/yarp/build/bin;C:/dev/yarp/build/bin/Debug;C:/dev/yarp/build/bin/Release
4>    referenced by variable YARP_IDL_BINARY_HINT does not exist !
4>  Call Stack (most recent call first):
4>    C:/dev/yarp/build/YARPConfig.cmake:97 (set_and_check)
4>    CMakeLists.txt:35 (find_package)
4>  
4>  
4>  -- Configuring incomplete, errors occurred!
4>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeOutput.log".
4>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeError.log".
2>    the file 'C:/dev/yarp/conf/YarpPlugin.cmake'
2>    is newer than 'C:\dev\icub-main\build\src\libraries\icubmod\CMakeFiles\generate.stamp.depend'
2>    result='-1'
2>  -- Building for: Visual Studio 12 2013
2>  CMake Error at C:/dev/yarp/build/YARPConfig.cmake:26 (message):
2>    File or directory
2>    C:/dev/yarp/build/bin;C:/dev/yarp/build/bin/Debug;C:/dev/yarp/build/bin/Release
2>    referenced by variable YARP_IDL_BINARY_HINT does not exist !
2>  Call Stack (most recent call first):
2>    C:/dev/yarp/build/YARPConfig.cmake:97 (set_and_check)
2>    CMakeLists.txt:35 (find_package)
2>  
2>  
2>  -- Configuring incomplete, errors occurred!
2>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeOutput.log".
2>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeError.log".
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 1.
4>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 1.
5>------ Build started: Project: depth2kin, Configuration: Release Win32 ------
6>------ Build started: Project: icubmoddev, Configuration: Release Win32 ------
5>  Building Custom Rule C:/dev/icub-main/src/tools/depth2kin/CMakeLists.txt
6>  Building Custom Rule C:/dev/icub-main/src/libraries/icubmod/CMakeLists.txt
5>  CMake is re-running because C:\dev\icub-main\build\src\tools\depth2kin\CMakeFiles\generate.stamp is out-of-date.
5>    the file 'C:/dev/yarp/conf/YarpIDL.cmake'
5>    is newer than 'C:\dev\icub-main\build\src\tools\depth2kin\CMakeFiles\generate.stamp.depend'
5>    result='-1'
5>  -- Building for: Visual Studio 12 2013
5>  CMake Error at C:/dev/yarp/build/YARPConfig.cmake:26 (message):
5>    File or directory
5>    C:/dev/yarp/build/bin;C:/dev/yarp/build/bin/Debug;C:/dev/yarp/build/bin/Release
5>    referenced by variable YARP_IDL_BINARY_HINT does not exist !
5>  Call Stack (most recent call first):
5>    C:/dev/yarp/build/YARPConfig.cmake:97 (set_and_check)
5>    CMakeLists.txt:35 (find_package)
5>  
5>  
5>  -- Configuring incomplete, errors occurred!
5>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeOutput.log".
5>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeError.log".
6>  CMake is re-running because C:\dev\icub-main\build\src\libraries\icubmod\CMakeFiles\generate.stamp is out-of-date.
6>    the file 'C:/dev/yarp/conf/YarpPlugin.cmake'
6>    is newer than 'C:\dev\icub-main\build\src\libraries\icubmod\CMakeFiles\generate.stamp.depend'
6>    result='-1'
6>  -- Building for: Visual Studio 12 2013
6>  CMake Error at C:/dev/yarp/build/YARPConfig.cmake:26 (message):
6>    File or directory
6>    C:/dev/yarp/build/bin;C:/dev/yarp/build/bin/Debug;C:/dev/yarp/build/bin/Release
6>    referenced by variable YARP_IDL_BINARY_HINT does not exist !
6>  Call Stack (most recent call first):
6>    C:/dev/yarp/build/YARPConfig.cmake:97 (set_and_check)
6>    CMakeLists.txt:35 (find_package)
6>  
6>  
6>  -- Configuring incomplete, errors occurred!
6>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeOutput.log".
6>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeError.log".
5>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 1.
6>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 1.
7>------ Build started: Project: python-scripts, Configuration: Release Win32 ------
8>------ Build started: Project: rpcIdl, Configuration: Release Win32 ------
7>  Building Custom Rule C:/dev/icub-main/CMakeLists.txt
7>  CMake Error at C:/dev/yarp/build/YARPConfig.cmake:26 (message):
7>    File or directory
7>    C:/dev/yarp/build/bin;C:/dev/yarp/build/bin/Debug;C:/dev/yarp/build/bin/Release
7>    referenced by variable YARP_IDL_BINARY_HINT does not exist !
7>  Call Stack (most recent call first):
7>    C:/dev/yarp/build/YARPConfig.cmake:97 (set_and_check)
7>    CMakeLists.txt:35 (find_package)
7>  
7>  
7>  CMake is re-running because C:\dev\icub-main\build\CMakeFiles\generate.stamp is out-of-date.
7>    the file 'C:/dev/yarp/build/YARPConfigVersion.cmake'
7>    is newer than 'C:\dev\icub-main\build\CMakeFiles\generate.stamp.depend'
7>    result='-1'
7>  -- Building for: Visual Studio 12 2013
7>  -- Configuring incomplete, errors occurred!
7>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeOutput.log".
7>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeError.log".
8>  Building Custom Rule C:/dev/icub-main/src/examples/rpcIdl/CMakeLists.txt
8>  CMake is re-running because C:\dev\icub-main\build\src\examples\rpcIdl\CMakeFiles\generate.stamp is out-of-date.
8>    the file 'C:/dev/yarp/conf/YarpIDL.cmake'
8>    is newer than 'C:\dev\icub-main\build\src\examples\rpcIdl\CMakeFiles\generate.stamp.depend'
8>    result='-1'
8>  -- Building for: Visual Studio 12 2013
8>  CMake Error at C:/dev/yarp/build/YARPConfig.cmake:26 (message):
8>    File or directory
8>    C:/dev/yarp/build/bin;C:/dev/yarp/build/bin/Debug;C:/dev/yarp/build/bin/Release
8>    referenced by variable YARP_IDL_BINARY_HINT does not exist !
8>  Call Stack (most recent call first):
8>    C:/dev/yarp/build/YARPConfig.cmake:97 (set_and_check)
8>    CMakeLists.txt:35 (find_package)
8>  
8>  
8>  -- Configuring incomplete, errors occurred!
8>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeOutput.log".
8>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeError.log".
7>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 1.
8>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 1.
9>------ Build started: Project: ALL_BUILD, Configuration: Release Win32 ------
9>  Building Custom Rule C:/dev/icub-main/CMakeLists.txt
9>  CMake is re-running because C:\dev\icub-main\build\CMakeFiles\generate.stamp is out-of-date.
9>    the file 'C:/dev/yarp/build/YARPConfigVersion.cmake'
9>    is newer than 'C:\dev\icub-main\build\CMakeFiles\generate.stamp.depend'
9>    result='-1'
9>  -- Building for: Visual Studio 12 2013
9>  CMake Error at C:/dev/yarp/build/YARPConfig.cmake:26 (message):
9>    File or directory
9>    C:/dev/yarp/build/bin;C:/dev/yarp/build/bin/Debug;C:/dev/yarp/build/bin/Release
9>    referenced by variable YARP_IDL_BINARY_HINT does not exist !
9>  Call Stack (most recent call first):
9>    C:/dev/yarp/build/YARPConfig.cmake:97 (set_and_check)
9>    CMakeLists.txt:35 (find_package)
9>  
9>  
9>  -- Configuring incomplete, errors occurred!
9>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeOutput.log".
9>  See also "C:/dev/icub-main/build/CMakeFiles/CMakeError.log".
9>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 1.
========== Build: 1 succeeded, 8 failed, 85 up-to-date, 0 skipped ==========
```

**Comment by traversaro** [comment]
There are also problems in Linux, travis CI is now failing for the codyco-superbuild: 
https://travis-ci.org/robotology/codyco-superbuild/builds/50459912

**Comment by drdanz** [comment]
@traversaro's issue was expected and was the main reason why I bumped the tweak number. iCub that using ``YarpPluginPath.cmake`` that in my opinion should have never been installed, I had the commit ready, but I wasn't expecting that the patch would be merged ad 4AM :smile:

@pattacini's issue was not expected, but should be fixed now, it was caused by an ``if(MSVC)`` in ``YarpDescribe.cmake`` that I didn't notice.

**Comment by drdanz** [comment]
Let me know if you still have problems...

**Comment by pattacini** [comment]
Fixed in Windows, thanks @drdanz

**Comment by pattacini** [comment]
I've noticed the print of strange numbers during cmaking:

192
205

**Comment by drdanz** [comment]
@pattacini ooops, I forgot to remove some debug, thanks...

**Comment by traversaro** [comment]
@drdanz Thx, everything is working now!

**Pull request merged**
