### PR TITLE
Fix RFModuleTest

### PR DESCRIPTION
**Pull request by claudiofantacci**
Fixes ModuleTest name in RFModuleTest and add new tests for the new threaded-mode functionalities.

### CODE REVIEW

**Comment by drdanz** [comment]
@claudiofantacci appveyor build fails with this error:
```
C:\projects\yarp\tests\libYARP_OS\RFModuleTest.cpp(47): error C2864: 'MyModule::a_local_bool_' : only static const integral data members can be initialized within a class
```

All C++11 builds on travis fail in this way:
```
yarp: 0 | RFModuleTest:   [[Test] Module threaded] passed ok
[INFO]RFModule closing.
[INFO]RFModule finished.
[WARNING]RFModule joinModule() timed out.
yarp: 1 | RFModuleTest:   FAILURE in file /home/travis/build/robotology/yarp/tests/libYARP_OS/RFModuleTest.cpp:83 [[Test] Module threaded finished] mm.joinModule() (0) == true (1)
```

Also travis valgrind tests fail
```
==25653== Mismatched free() / delete / delete []
==25653==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25653==    by 0x5AAABA3: yarp::os::RFModule::joinModule(double) (in /home/travis/build/robotology/yarp/build/lib/libYARP_OS.so.2.3.67.3)
==25653==    by 0x43937A: RFModuleTest::testPort() (in /home/travis/build/robotology/yarp/build/bin/harness_os)
==25653==    by 0x439755: RFModuleTest::runTests() (in /home/travis/build/robotology/yarp/build/bin/harness_os)
==25653==    by 0x5AE25E8: yarp::os::impl::UnitTest::run(int, char**) (in /home/travis/build/robotology/yarp/build/lib/libYARP_OS.so.2.3.67.3)
==25653==    by 0x5AE1C42: yarp::os::impl::UnitTest::runSubTests(int, char**) (in /home/travis/build/robotology/yarp/build/lib/libYARP_OS.so.2.3.67.3)
==25653==    by 0x5AE25C5: yarp::os::impl::UnitTest::run(int, char**) (in /home/travis/build/robotology/yarp/build/lib/libYARP_OS.so.2.3.67.3)
==25653==    by 0x437C58: main (in /home/travis/build/robotology/yarp/build/bin/harness_os)
==25653==  Address 0x7516a30 is 0 bytes inside a block of size 32 alloc'd
==25653==    at 0x4C2B3B0: operator new(unsigned long, std::nothrow_t const&) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25653==    by 0x5AAA900: yarp::os::RFModule::runModuleThreaded() (in /home/travis/build/robotology/yarp/build/lib/libYARP_OS.so.2.3.67.3)
==25653==    by 0x43932C: RFModuleTest::testPort() (in /home/travis/build/robotology/yarp/build/bin/harness_os)
==25653==    by 0x439755: RFModuleTest::runTests() (in /home/travis/build/robotology/yarp/build/bin/harness_os)
==25653==    by 0x5AE25E8: yarp::os::impl::UnitTest::run(int, char**) (in /home/travis/build/robotology/yarp/build/lib/libYARP_OS.so.2.3.67.3)
==25653==    by 0x5AE1C42: yarp::os::impl::UnitTest::runSubTests(int, char**) (in /home/travis/build/robotology/yarp/build/lib/libYARP_OS.so.2.3.67.3)
==25653==    by 0x5AE25C5: yarp::os::impl::UnitTest::run(int, char**) (in /home/travis/build/robotology/yarp/build/lib/libYARP_OS.so.2.3.67.3)
==25653==    by 0x437C58: main (in /home/travis/build/robotology/yarp/build/bin/harness_os)
==25653== 
```


I'm not sure if these errors are due to the changes you made, to the new tests or to the test that was actually never executed.

As a first step, you could force-push just the first commit (the file renaming) so that we can restrict the origin of these problem. `git push --force claudiofantacci fix/rfmoduletest~:fix/rfmoduletest` should do the trick (assuming you named your remote `claudiofantacci` in your local clone).

Meanwhile I'm adding the WIP tag to the title

**Comment by claudiofantacci** [comment]
I did the `git push -force` for the renaming commit.

I'm modifying the test to address the issue raised by both AppVeyor and Travis.

**Comment by claudiofantacci** [comment]
I think I fixed the problem with AppVeyor. I was doing a simple, yet useless, operation that I now deleted. I also modified the test, adding a small delay between a particular test check to help the thread deallocation process to take place. Hope it helps.

Meanwhile, I also found a an error in the documentation. I will push different commit, but all together in this PR branch. Is it ok for you?

**Comment by claudiofantacci** [comment]
By the way, all C++11 Trevis tests are still failing.

**Comment by drdanz** [comment]
Valgrind tests are still failing with the `Mismatched free() / delete / delete []` error. Anyway I don't see the problem reported, and on my computer (with valgrind 3.12) the test passes. On travis there is valgrind 3.10. I'm quite sure that this is an issue with this version valgrind, but on another system running ubuntu trusty and the same version of valgrind I had even worse errors (no valgrind test passes on my system).

I don't want to disable all valgrind tests just for this false positive. Maybe we can suppress this error, @traversaro what do you think?

**Comment by claudiofantacci** [comment]
I found out why tests are failing with c++11.

When C++11 is **disabled**, ACE thread is used.
Ace thread join() function returns
- 0 on success
- -1 on error/timeout

When C++11 is **enabled**, std::thread is are used.
std::thread do not have a join() return value, it's a void function.
Thus in YARP PlatformThread.h the following line defines a return value for join:
`#  define PLATFORM_THREAD_JOIN(x) ([](std::thread& y) { if (!y.joinable()) return false; y.join(); return true; }(x))`
which returns
- 1 on success
- 0 on error/timeout

This mismatch clearly invalidates all the tests using a check on the return value.

Taking into account this issue, we should discuss a _policy_ to undertake for YARP.
For the sake of logic, I would say that we should have a return value which is the same of the one used by ACE, also for any possible legacy software developed so far.
My suggestion is to change the `#define` as follow:
`#  define PLATFORM_THREAD_JOIN(x) ([](std::thread& y) { if (!y.joinable()) return -1; y.join(); return 0; }(x))`

Let me know.

cc: @lornat75 @pattacini @vtikha @francesco-romano @traversaro

**Comment by gsaponaro** [comment]
Related issue: https://github.com/robotology/yarp/issues/395

**Comment by drdanz** [comment]
Merged. Thanks!

**Pull request merged**
