### PR TITLE
Fix yarp IDL for Xcode

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Thanks to @drdanz  for the correct cmake commands. This should fix https://github.com/robotology/yarp/issues/872
If it all works, we should not allow the failure of the corresponding test in Travis anymore.

I also increased the `travis_wait` time for the tests, even 30 minutes might not be long enough.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/874%23issuecomment-240425486%22%2C%20%22https%3A//github.com/robotology/yarp/pull/874%23issuecomment-240426277%22%2C%20%22https%3A//github.com/robotology/yarp/pull/874%23issuecomment-240471500%22%2C%20%22https%3A//github.com/robotology/yarp/pull/874%23issuecomment-240651410%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/874%23issuecomment-240425486%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40Tobias-Fischer%20Let%27s%20wait%20to%20see%20if%20the%20XCode%20test%20is%20fixed%20and%20eventually%20remove%20it%20from%20%60allow_failures%60%20before%20merging...%22%2C%20%22created_at%22%3A%20%222016-08-17T14%3A17%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yes%2C%20agree%21%22%2C%20%22created_at%22%3A%20%222016-08-17T14%3A19%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22There%20was%20another%20error%2C%20I%20think%20I%20fixed%20it%20..%20let%27s%20see%20what%20Travis%20says.%22%2C%20%22created_at%22%3A%20%222016-08-17T16%3A41%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Looks%20like%20travis%20was%20happy%20with%20the%20last%20build%2C%20I%27ll%20just%20merge%20it%20without%20waiting%20for%20the%20build%20to%20end...%22%2C%20%22created_at%22%3A%20%222016-08-18T07%3A59%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/874#issuecomment-240425486'>General Comment</a></b>
- <a href='https://github.com/drdanz'></a> @Tobias-Fischer Let's wait to see if the XCode test is fixed and eventually remove it from `allow_failures` before merging...
- <a href='https://github.com/Tobias-Fischer'></a> Yes, agree!
- <a href='https://github.com/Tobias-Fischer'></a> There was another error, I think I fixed it .. let's see what Travis says.
- <a href='https://github.com/drdanz'></a> Looks like travis was happy with the last build, I'll just merge it without waiting for the build to end...

<a href='https://www.codereviewhub.com/robotology/yarp/pull/874?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/874?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/874'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/874'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by drdanz** [comment]
@Tobias-Fischer Let's wait to see if the XCode test is fixed and eventually remove it from `allow_failures` before merging...

**Comment by Tobias-Fischer** [comment]
Yes, agree!

**Comment by Tobias-Fischer** [comment]
There was another error, I think I fixed it .. let's see what Travis says.

**Comment by drdanz** [comment]
Looks like travis was happy with the last build, I'll just merge it without waiting for the build to end...

**Pull request merged**
