### PR TITLE
Fix contact compilation

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Was broken due to recent changes.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/829%23issuecomment-233029170%22%2C%20%22https%3A//github.com/robotology/yarp/pull/829%23issuecomment-233029587%22%2C%20%22https%3A//github.com/robotology/yarp/pull/829%23issuecomment-233030025%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/829%23issuecomment-233029170%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40drdanz%20%22%2C%20%22created_at%22%3A%20%222016-07-15T18%3A22%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-07-15T18%3A24%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks%2C%20i%20renamed%20the%20method%20at%20the%20last%20second%2C%20I%27m%20not%20sure%20how%20I%20didn%27t%20notice%20this%21%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-15T18%3A25%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/drdanz%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/drdanz'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/829#issuecomment-233029170'>General Comment</a></b>
- <a href='https://github.com/Tobias-Fischer'></a> @drdanz
- <a href='https://github.com/drdanz'></a> :shipit:
- <a href='https://github.com/drdanz'></a> Thanks, i renamed the method at the last second, I'm not sure how I didn't notice this!

<a href='https://www.codereviewhub.com/robotology/yarp/pull/829?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/829?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/829?approve=0'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/829'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/829'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Tobias-Fischer** [comment]
@drdanz

**Comment by drdanz** [comment]
:shipit:

**Comment by drdanz** [comment]
Thanks, i renamed the method at the last second, I'm not sure how I didn't notice this!

**Pull request merged**
