### PR TITLE
Fix rateThread example

### PR DESCRIPTION
**Pull request by barbalberto**
Fix segfault in the rateThread example

### CODE REVIEW

**Comment by jgvictores** [comment]
Cool, tested and works.

@barbalberto Could you please apply the same on [example/os/threads.cpp](https://github.com/robotology/yarp/blob/45ec3a37ed717592bc512638be6073e26a23fd0b/example/os/threads.cpp)?
(I do not have push permissions; while forking for this is overkill, it is required to patch this to avoid segfaults)

**Comment by drdanz** [comment]
@barbalberto Let me know if you want me to merge this, or if you want to fix example/os/threads.cpp as well, as suggested by @jgvictores

**Comment by barbalberto** [comment]
ok, I'll fix also thread

**Comment by barbalberto** [comment]
Updated all `os` examples

**Comment by jgvictores** [comment]
@barbalberto Thanks a lot!

**Comment by drdanz** [comment]
@barbalberto Awesome, thanks!

**Pull request merged**
