### PR TITLE
xmlrpcpp: Remove unused test directory

### PR DESCRIPTION
**Pull request by traversaro**
The `extern/xmlrpcpp/xmlrpcpp/test/pngnow.png` file that is a monster of a rare beauty. It used to be a .png file used in the xmlrpcpp test suite, but due to a CVS corruption (according to https://github.com/nega0/xmlrpcpp/commit/af326586333050658916b9871c0e033ecc12fbf3) it became a 6 byte `.png` file composed by the non-ascii byte `0x89`, followed by the three ASCII characters `PNG`, and ended by `CR LF`. However, it used to be registered as a binary file for `.git` due to the `*.png                           binary` line in the `.gitattributes` file.

This file, combined with the modifications in the `.gitattributes` file in https://github.com/robotology/yarp/commit/56db2113b1074bad359b35f27465aa916dbde8b8, triggered an extremely non-deterministic git bug/misbehavior described in https://github.com/robotology/robotology-superbuild/issues/469 . As those file and the test directory that contains it is not actually used, the most convenient solution is just to remove them.

Fix https://github.com/robotology/robotology-superbuild/issues/469 .

### CODE REVIEW

**Comment by traversaro** [comment]
> 
> 
> Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update the release notes by adding a file in `doc/release/<target_branch>`, based on your changes.

Hi @update-docs ! I don't want to brag but a YARP mantainer told me that this change is not affecting the users, so it is ok not to mention it in the release notes.

**Comment by traversaro** [comment]
Hi @drdanz, are the test failures related to the change?

**Review by drdanz — APPROVED** [review]

**Comment by drdanz** [comment]
> Hi @drdanz, are the test failures related to the change?

No, unfortunately the builds on mac and on vs2017 started to go in timeout recently

**Comment by drdanz** [comment]
For some reason the automatic rebase failed with this error:
>error: Your local changes to the following files would be overwritten by checkout:
>	extern/xmlrpcpp/xmlrpcpp/test/pngnow.png
I had to rebase it manually...

**Comment by traversaro** [comment]
> For some reason the automatic rebase failed with this error:
> 
> > error: Your local changes to the following files would be overwritten by checkout:
> > extern/xmlrpcpp/xmlrpcpp/test/pngnow.png
> 
> I had to rebase it manually...

That is exactly the same problem that we experienced in https://github.com/robotology/robotology-superbuild/issues/469 .

**Comment by drdanz** [comment]
Merged, thanks.

**Comment by traversaro** [comment]
It seems that the `pngnow.png` bug is also affecting the Nightly job that forward merges from `yarp-3.4` to `master`, see : https://github.com/robotology/yarp/runs/1109623055 .

**Comment by drdanz** [comment]
I merged it manually, we should not have any other issues with this file from now on...

**Pull request merged**
