### PR TITLE
Enable Eigen backend of libYARP_math by default

### PR DESCRIPTION
**Pull request by traversaro**
See https://github.com/robotology/yarp/issues/840#issuecomment-259072222 .

### CODE REVIEW

**Comment by traversaro** [comment]
It is worth noting that the old value of `CREATE_LIB_MATH_USING_GSL` is cached, so if you want to test it in your installation you have to manually change it to `OFF`.

**Comment by frank-foerster** [comment]
@traversaro 
Very stupid question: I just updated YARP on one of our machines and tried to compile Eigen "into it", but get a `Eigen3_DIR-NOTFOUND` in ccmake when activating `CREATE_LIB_MATH`.

Prior to compiling I installed `libeigen3-dev` via apt-get (OS is Debian8).

I also had a look into [FindEigen3.cmake](https://github.com/robotology/yarp/blob/master/cmake/ycm-0.2/3rdparty/FindEigen3.cmake) to see how I could make it find Eigen and set `EIGEN3_ROOT` to `/usr/include/eigen3` and `/usr/include/eigen3/EIGEN` respectively (tried both), but none of that helped. 

What's the trick?

**Comment by traversaro** [comment]
There is a problem in the `FindEigen3.cmake` : basically even if Eigen is found (and `EIGEN3_INCLUDE_DIR` is set) `Eigen3_DIR` is set to `Eigen3_DIR-NOTFOUND`. This is inconvenient (because user tend to believe that Eigen was not found) but everything should work if you try to compile. 

Note: this should be fixed by this Eigen3 PR : https://bitbucket.org/eigen/eigen/pull-requests/281/improve-findeigen3cmake/diff . See in particular this line :  https://bitbucket.org/eigen/eigen/pull-requests/281/improve-findeigen3cmake/diff#Lcmake/FindEigen3.cmakeT90 .

**Comment by frank-foerster** [comment]
Thanks for the hint. I'll ignore the error then for the time being.

**Pull request merged**
