### PR TITLE
Replace deprecated `set-output`

### PR DESCRIPTION
**Pull request by pattacini**
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

### CODE REVIEW

**Comment by pattacini** [comment]
> Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update the release notes by adding a file in `doc/release/<target_branch>`, based on your changes.

This fix concerns just CI, so most likely we don't need a release note.

**Review by Nicogene — APPROVED** [review]

**Review by randaz81 — DISMISSED** [review]

**Comment by randaz81** [comment]
Some jobs failed. I'm re-running all checks before merging.

**Comment by pattacini** [comment]
Hi @randaz81 

As agreed, I've just reinstated the old handling when dealing w/ `yarp_version`.
It may be the cause of the CI failures.

**Review by randaz81 — CHANGES_REQUESTED** [review]
Some CI issues. Requires additional investigation before merging.

**Comment by pattacini** [comment]
Converted to draft to indicate that this PR acts like a memo for when `set-output` will be deprecated.

**Comment by randaz81** [comment]
Fixed.

**Pull request closed without merging**
