### PR TITLE
Drop support for OpenCV < 3

### PR DESCRIPTION
**Pull request by drdanz**
As discussed in #2360 

CC @pattacini, @PeterBowman, @Nicogene

### CODE REVIEW

**Review by pattacini — APPROVED** [review]

**Comment by alecive** [comment]
Good riddance to OpenCV 3!!

**Review by randaz81 — APPROVED** [review]

**Review by Nicogene — APPROVED** [review]

**Review by traversaro — APPROVED** [review]

**Comment by drdanz** [comment]
The build is failing with [this error](https://travis-ci.com/github/robotology/yarp/jobs/385873867#L10078-L10104):
```
Scanning dependencies of target yarpdatadumper
make[2]: Leaving directory '/home/travis/build/robotology/yarp/build'
/usr/bin/make -f src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/build.make src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/build
make[2]: Entering directory '/home/travis/build/robotology/yarp/build'
[ 74%] Building CXX object src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/main.cpp.o
cd /home/travis/build/robotology/yarp/build/src/yarpdatadumper && /home/travis/lib/ccache/clang++-8  -DADD_VIDEO -DBUILDING_YARP -I/home/travis/build/robotology/yarp/src/libYARP_os/src -I/home/travis/build/robotology/yarp/src/libYARP_conf/src -I/home/travis/build/robotology/yarp/build/src/libYARP_conf/src -I/home/travis/build/robotology/yarp/src/libYARP_sig/src -I/home/travis/build/robotology/yarp/src/libYARP_cv/src -isystem /usr/include/opencv -isystem /usr/include/opencv/..  -Wall -Wextra -Wsign-compare -Wpointer-arith -Winit-self -Wnon-virtual-dtor -Wcast-align -Wunused -Wvla -Wmissing-include-dirs -Wreorder -Wsizeof-pointer-memaccess -Woverloaded-virtual -Wtautological-undefined-compare -Wmismatched-new-delete -Wparentheses-equality -Wundef -Wredundant-decls -Wunknown-pragmas -Wunused-result -Wc++17-compat -Wc++2a-compat -Wheader-guard -Wignored-attributes -Wnewline-eof -Wdangling-else -Wgcc-compat -Wmicrosoft-exists -Wstatic-inline-explicit-instantiation -Wtautological-compare -Winconsistent-missing-override -Wnull-conversion  -Wno-unused-parameter  -Wdeprecated-declarations  -O3 -DNDEBUG -fPIE -fvisibility=hidden -fvisibility-inlines-hidden   -std=c++14 -o CMakeFiles/yarpdatadumper.dir/main.cpp.o -c /home/travis/build/robotology/yarp/src/yarpdatadumper/main.cpp
In file included from /home/travis/build/robotology/yarp/src/yarpdatadumper/main.cpp:10:
In file included from /home/travis/build/robotology/yarp/src/libYARP_os/src/yarp/os/BufferedPort.h:13:
In file included from /home/travis/build/robotology/yarp/src/libYARP_os/src/yarp/os/Contactable.h:13:
In file included from /home/travis/build/robotology/yarp/src/libYARP_os/src/yarp/os/Contact.h:16:
In file included from /home/travis/build/robotology/yarp/src/libYARP_os/src/yarp/os/NestedContact.h:15:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/string:52:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/basic_string.h:6361:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/ext/string_conversions.h:41:
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/cstdlib:75:15: fatal error: 
      'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
1 error generated.
src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/build.make:62: recipe for target 'src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/main.cpp.o' failed
make[2]: *** [src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/main.cpp.o] Error 1
make[2]: Leaving directory '/home/travis/build/robotology/yarp/build'
CMakeFiles/Makefile2:8100: recipe for target 'src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/all' failed
make[1]: *** [src/yarpdatadumper/CMakeFiles/yarpdatadumper.dir/all] Error 2
make[1]: Leaving directory '/home/travis/build/robotology/yarp/build'
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

Does anyone understand what could be the reason?

**Comment by pattacini** [comment]
>Does anyone understand what could be the reason?

No clue...

It seems that the error gets triggered in the very first code line (line 10), so nothing to do with the code itself but rather with the building environment and/or building options.

**Comment by PeterBowman** [comment]
Is it correct that Clang 8 searches within GCC standard include paths? (it might be, I'm not a Clang user)

**Comment by drdanz** [comment]
> Is it correct that Clang 8 searches within GCC standard include paths? (it might be, I'm not a Clang user)

I don't know, but also gcc builds are failing with the same error :disappointed:

**Comment by drdanz** [comment]
I think I finally found the issue.
Apparently if you search for OpenCV 3 **after** searching without success for OpenCV 4, the `OpenCVConfig.cmake` file does not fully search for everything, therefore a few cache variables are `NOTFOUND`.
The opposite does not seem to happen.

Let's see if it builds now.

**Comment by Nicogene** [comment]
> Apparently if you search for OpenCV 3 after searching without success for OpenCV 4, the OpenCVConfig.cmake file does not fully search for everything, therefore a few cache variables are NOTFOUND.
The opposite does not seem to happen.

Is it the case to open an issue about it?

**Comment by drdanz** [comment]
If it works with opencv 4 (which I have on my pc and it should be used in the macos build), it probably means that the bug is already fixed in opencv4, therefore I don't think they are going to fix opencv 3...

**Comment by drdanz** [comment]
Merged! :tada:

**Pull request merged**
