### PR TITLE
Update gitignore including VS2017 files

### PR DESCRIPTION
**Pull request by claudiofantacci**
Add `CMakeSettings.json` file and `.vs` folder.

### CODE REVIEW

**Comment by Nicogene** [comment]
The failures of travis/appveyor are obviously unrelated, if for windows user it's ok we can safely merge it

**Comment by drdanz** [comment]
Are `CMakeSettings.json` and `.vs` scattered all around the code or just in the main directory?
In the latter case, please add a `/` in front, otherwise let me know, and I will merge this...

**Comment by claudiofantacci** [comment]
> Are CMakeSettings.json and .vs scattered all around the code or just in the main directory?
> In the latter case, please add a / in front, otherwise let me know, and I will merge this...

AFAICT they are only in the root dir.

**Comment by drdanz** [comment]
Rebased on master and added the initial `/`

**Comment by drdanz** [comment]
Merged, thanks.

**Pull request merged**
