### PR TITLE
Fixed memory access in NetworkClock

### PR DESCRIPTION
**Pull request by francesco-romano**
cc @traversaro @barbalberto

### CODE REVIEW

**Comment by traversaro** [comment]
:+1:

**Comment by traversaro** [comment]
@barbalberto : the problem is that the Semaphore was deleted before the `post` method was called on it.

**Comment by francesco-romano** [comment]
Sorry @traversaro. I should have explained it..

**Comment by francesco-romano** [comment]
The "success" part of travis is happy.
Merging

**Pull request merged**
