### PR TITLE
Fixed issue on yarpdataplayer when opening readonly files

### PR DESCRIPTION
**Pull request by francesco-romano**
By default `std::stream` opens a file in read and write mode.
I changed the `fstream` to open the file in read mode. Alternatively we can keep the old constructor but change the stream to `ifstream`.

cc @ChiaraBartolozzi 

@vtikha There was a reason why the file is opened in write mode?
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/vtikha%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4537987%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/875%23issuecomment-240681876%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-08-18T10%3A12%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4537987%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vtikha%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40francesco-romano%20ok%20go%20ahead%20with%20the%20merge.%22%2C%20%22created_at%22%3A%20%222016-08-18T10%3A16%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4537987%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vtikha%22%7D%7D%2C%20%7B%22body%22%3A%20%22Please%20rebase%20the%20branch%20and%20remove%20commit%20f5d3114%5Cr%5CnDo%20not%20use%20the%20%5C%22update%5C%22%20button%2C%20since%20it%20creates%20useless%20merge%20commits.%20%22%2C%20%22created_at%22%3A%20%222016-08-18T10%3A18%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40francesco-romano%20Also%20please%20add%20a%20line%20to%20the%20release%20notes%20%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222016-08-18T10%3A19%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40drdanz%20error%20from%20using%20the%20app.%20Please%20do%20it%20from%20there.%20Cheers.%22%2C%20%22created_at%22%3A%20%222016-08-18T10%3A19%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4537987%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vtikha%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40vtikha%20No%20problem%20%3Awink%3A%20%22%2C%20%22created_at%22%3A%20%222016-08-18T10%3A24%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40drdanz%20I%20added%20the%20release%20notes%20and%20I%20pushed.%5Cr%5Cn%5Cr%5CnI%27ve%20also%20tried%20%28locally%29%20to%20rebase%20on%20master%2C%20but%20I%20am%20a%20bit%20confused%20about%20the%20commit%20f5d3114e7be7ef9c0ccda94c5b43cd09f87e78cb%20and%20I%27m%20afraid%20to%20force%20push%20the%20branch%20now.%20%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-18T10%3A35%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2189180%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/francesco-romano%22%7D%7D%2C%20%7B%22body%22%3A%20%22%60git%20pull%20--rebase%20origin%20master%60%20should%20get%20rid%20of%20the%20commit...%20Then%20you%20can%20force%20push%20on%20the%20%60fix/yarpdataplayer_readlonlyfiles%60%20branch...%22%2C%20%22created_at%22%3A%20%222016-08-18T11%3A09%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/875%23issuecomment-240681876%22%2C%20%22https%3A//github.com/robotology/yarp/pull/875%23issuecomment-240682645%22%2C%20%22https%3A//github.com/robotology/yarp/pull/875%23issuecomment-240683053%22%2C%20%22https%3A//github.com/robotology/yarp/pull/875%23issuecomment-240683258%22%2C%20%22https%3A//github.com/robotology/yarp/pull/875%23issuecomment-240683278%22%2C%20%22https%3A//github.com/robotology/yarp/pull/875%23issuecomment-240684473%22%2C%20%22https%3A//github.com/robotology/yarp/pull/875%23issuecomment-240686512%22%2C%20%22https%3A//github.com/robotology/yarp/pull/875%23issuecomment-240693109%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/vtikha'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/875#issuecomment-240681876'>General Comment</a></b>
- <a href='https://github.com/vtikha'></a> :shipit:
- <a href='https://github.com/vtikha'></a> @francesco-romano ok go ahead with the merge.
- <a href='https://github.com/drdanz'></a> Please rebase the branch and remove commit f5d3114
Do not use the "update" button, since it creates useless merge commits.
- <a href='https://github.com/drdanz'></a> @francesco-romano Also please add a line to the release notes :+1:
- <a href='https://github.com/vtikha'></a> @drdanz error from using the app. Please do it from there. Cheers.
- <a href='https://github.com/drdanz'></a> @vtikha No problem :wink:
- <a href='https://github.com/francesco-romano'></a> @drdanz I added the release notes and I pushed.
I've also tried (locally) to rebase on master, but I am a bit confused about the commit f5d3114e7be7ef9c0ccda94c5b43cd09f87e78cb and I'm afraid to force push the branch now.
- <a href='https://github.com/drdanz'></a> `git pull --rebase origin master` should get rid of the commit... Then you can force push on the `fix/yarpdataplayer_readlonlyfiles` branch...

<a href='https://www.codereviewhub.com/robotology/yarp/pull/875?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/875?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/875?approve=0'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/875'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/875'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by vtikha** [comment]
:shipit:

**Comment by vtikha** [comment]
@francesco-romano ok go ahead with the merge.

**Comment by drdanz** [comment]
Please rebase the branch and remove commit f5d3114
Do not use the "update" button, since it creates useless merge commits.

**Comment by drdanz** [comment]
@francesco-romano Also please add a line to the release notes :+1:

**Comment by vtikha** [comment]
@drdanz error from using the app. Please do it from there. Cheers.

**Comment by drdanz** [comment]
@vtikha No problem :wink:

**Comment by francesco-romano** [comment]
@drdanz I added the release notes and I pushed.

I've also tried (locally) to rebase on master, but I am a bit confused about the commit f5d3114e7be7ef9c0ccda94c5b43cd09f87e78cb and I'm afraid to force push the branch now.

**Comment by drdanz** [comment]
`git pull --rebase origin master` should get rid of the commit... Then you can force push on the `fix/yarpdataplayer_readlonlyfiles` branch...

**Pull request merged**
