### PR TITLE
Add Network clock initialization value that was missing in some cases.

### PR DESCRIPTION
**Pull request by barbalberto**
Re-doing PR 'cause I mess up the previous one. Sorry

### CODE REVIEW

**Comment by drdanz** [comment]
CC: #1929

**Comment by drdanz** [comment]
A changelog entry would be appreciated though :wink:

**Comment by barbalberto** [comment]
Added changelog entry and rebased on latest master.

**Comment by Nicogene** [comment]
Merged, thanks!

**Pull request merged**
