### PR TITLE
os/impl/Storable: Use std::to_string instead of sprintf

### PR DESCRIPTION
**Pull request by drdanz**

### CODE REVIEW

**Comment by pattacini** [comment]
@traversaro `master` is the new `devel` 😉 
Sometimes, I forget it too.

**Comment by traversaro** [comment]
> 
> 
> @traversaro `master` is the new `devel` 😉
> Sometimes, I forget it too.

Ahhaha, I wonder how I could forget.

**Comment by randaz81** [comment]
> I'd replace all the `sprintf` with `std::to_string` where possibile, btw lgtm!

But I still like the compact way in which I can set the number of digits, for example, in sprintf...  ;-)

**Comment by drdanz** [comment]
It's just a small modernization of code, It shouldn't break anything, but I opened a PR just to be sure that this works on all OSs. Also, not a bugfix, therefore it belongs in master.

In this case the code did not set any number of digits or similar, therefore it doesn't change anything, except unifying the code for the 4 int types, which is good since I would like, at some point, to change this stuff into a template, instead of having duplicated code around...

**Pull request merged**
