### PR TITLE
remove dependency between GSL and libYARP_sig, add libYARP_gsl for po…

### PR DESCRIPTION
**Pull request by lornat75**
This is the first step towards removing GSL dependency. It removes dependency between libYARP_sig and GSL. Added libYARP_gsl intended to provide GSL compatibility.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/858%23issuecomment-237689570%22%2C%20%22https%3A//github.com/robotology/yarp/pull/858%23issuecomment-237812772%22%2C%20%22https%3A//github.com/robotology/yarp/pull/858%23issuecomment-244023116%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/858%23issuecomment-237689570%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40drdanz%20%5Cr%5Cn%40pattacini%20%22%2C%20%22created_at%22%3A%20%222016-08-04T21%3A30%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1403333%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lornat75%22%7D%7D%2C%20%7B%22body%22%3A%20%22Instead%20of%20using%20the%20%60GslMatrix%60%20class%20it%20would%20be%20really%20easier%20to%20have%20a%20method%20that%20returns%20a%20c%2B%2B11%20smart%20pointer%20with%20a%20custom%20deleter.%20In%20this%20way%20it%20would%20be%20a%20lot%20easier%20to%20understand%20what%20will%20happen%20to%20the%20memory%20when%20it%20goes%20out%20of%20scope.%22%2C%20%22created_at%22%3A%20%222016-08-05T10%3A03%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22Closing%2C%20will%20be%20re-opened%20after%20we%20cleanup%20also%20libYARP_math.%22%2C%20%22created_at%22%3A%20%222016-09-01T09%3A17%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1403333%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lornat75%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/858#issuecomment-237689570'>General Comment</a></b>
- <a href='https://github.com/lornat75'></a> @drdanz
@pattacini
- <a href='https://github.com/drdanz'></a> Instead of using the `GslMatrix` class it would be really easier to have a method that returns a c++11 smart pointer with a custom deleter. In this way it would be a lot easier to understand what will happen to the memory when it goes out of scope.
- <a href='https://github.com/lornat75'></a> Closing, will be re-opened after we cleanup also libYARP_math.

<a href='https://www.codereviewhub.com/robotology/yarp/pull/858?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/858?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/858'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/858'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by lornat75** [comment]
@drdanz 
@pattacini

**Comment by drdanz** [comment]
Instead of using the `GslMatrix` class it would be really easier to have a method that returns a c++11 smart pointer with a custom deleter. In this way it would be a lot easier to understand what will happen to the memory when it goes out of scope.

**Comment by lornat75** [comment]
Closing, will be re-opened after we cleanup also libYARP_math.

**Pull request closed without merging**
