### PR TITLE
CI transition from Ubuntu 20.04 to Ubuntu 22.04 [OLD]

### PR DESCRIPTION
**Pull request by randaz81**
Closed in favor of: https://github.com/robotology/yarp/pull/3020

Yarp CI on Ubuntu 22.04

### CODE REVIEW

**Comment by traversaro** [comment]
@randaz81 the idea is to drop Ubuntu 20.04 compatibility in YARP 3.9.0 ? In that case we may want to tag some more people: @pattacini @Nicogene .

**Comment by randaz81** [comment]
> @randaz81 the idea is to drop Ubuntu 20.04 compatibility in YARP 3.9.0 ? In that case we may want to tag some more people: @pattacini @Nicogene .

Well, If we are ready, yes, Ubuntu 22 has several advantages. But it is not strict, we can postpone otherwise.

**Comment by pattacini** [comment]
Our only concern is due to the jetpacks of the onboard GPU as providers (NVIDIA as well as 3rd-party HW-specific providers) tend not to be so fast to catch up.

However, there might be a way to go that can work as a good tradeoff.
We could discuss this in one of our upcoming meetups.

cc @randaz81 @Nicogene @traversaro

**Comment by randaz81** [comment]
About jetpacks, unfortunately, Ubuntu 22.04 will be supported on new upcoming hardware only, the devices we are currently employing are not expected to receive an update and will probably remain Ubuntu 20.04 forever, as announced by nvidia:
https://forums.developer.nvidia.com/t/jetson-software-roadmap-for-2023/238889

**Comment by randaz81** [comment]
Please note that this PR only refers to the CI only and it does not include anything (code/dependencies etc) that can break the usage of Yarp on Ubuntu 20.04. 
However, this could happen in future developments...

**Comment by randaz81** [comment]
Closed in favor of: https://github.com/robotology/yarp/pull/3020

**Pull request closed without merging**
