### PR TITLE
Ffmpeg fix debian testing compilation and replace some deprecated functions

### LINKED ISSUE #1849: ffmpeg plugin no longer compiles on debian testing.
After the latest system update, the ffmpeg plugin no longer compiles on debian testing.
The ffmpeg plugin has been using deprecated stuff for ages, therefore this is not a surprise.

We should decide whether to spend some time update the plugin to the latest API, or just drop it.

### PR DESCRIPTION
**Pull request by Nicogene**
It fixes #1849
Moreover it some replaces deprecated functions and some cleanup.                                                                                                                                          
                                                                                                                                                                                                                 

Please review code.

### CODE REVIEW

**Comment by traversaro** [comment]
There seems to be a lot version-dependent logic in the plugin. Just to understand, which version did we actually tested? We should at least test the version shipped in Debian Testing and in Ubuntu 18.04 .

**Comment by Nicogene** [comment]
We actually tested in Debian Testing and in Ubuntu 18.04, unfortunately we didn't tested for Ubuntu 16.04 :confused:

**Comment by traversaro** [comment]
Ok for me.

**Comment by drdanz** [comment]
My part of the changes is taken from a branch I started in 2016. There was a lot of logic supporting very old versions of ffmpeg, using deprecated methods, and complicating a lot the logic, I removed most of that, but in the end I could not get it to compile on some older ubuntu, and I had to abort the branch since I didn't have time to work on that.

Probably it will work on ubuntu 16.04 because it was the "most recent release" while I was working on that, but to be honest I don't remember and we haven't tested it. Since this is mostly abandoned and probably unused code, I don't think we should waste more time on this, unless we decide that it is worth supporting it.

I think it is worth keeping at least the `grabber` (even if some parts should be refactored and the audio part in YARP should be completely re-written). I used it in several occasions to stream a file or the webcam on a YARP port (since the `USBCamera` device is still in iCub and not in YARP) and it works quite well.
The `writer` is kind of weird, it requires the `pipe` device, I'm not sure if any of these two devices are useful.

**Comment by Nicogene** [comment]
> There was a lot of logic supporting very old versions of ffmpeg, using deprecated methods, and complicating a lot the logic

The remaining deprecated methods require such type of work, the new `avutil` API is easier to use and it seems more high level.

**Comment by drdanz** [comment]
> The remaining deprecated methods require such type of work, the new avutil API is easier to use and it seems more high level.

Actually the type of work to do in order to fix all the deprecation warnings is quite more complicated. Basically all the code was (quite simplified, but just to explain).

```c++
#if A_VERY_OLD_VERSION_OF_FFMPEG
# define yarp_method(a, b, c, d) very_old_method(d, b, c)
#else
# define yarp_method(a, b, c, d) new_method(a, b, c)
#endif

// [...]

yarp_method(a, b, c, d);
```

I changed all of that in:

```c++
new_method(a, b, c)
```

Some of the `#if` were probably wrong, and I also removed some unused stuff and updated a few calls to the new API, therefore the number of deprecation warnings was reduced.


The work to do here is quite more complicated, the logic of the calls and the objects to pass around is quite different, therefore porting is not very straight forward.

**Pull request merged**
