### PR TITLE
[yarpdatadumper] Add small python helper script to yarpdatadumper

### PR DESCRIPTION
**Pull request by traversaro**
Script to automatically generate yarpmanager applications.
It is installed only if python is found in the OS.
It should run fine also on Windows, but I did not test it.
Documentation of yarpdatadumper was also updated.

I don't know what is the policy for python scripts in yarp, but this script is definitely useful and it may be helpful for all yarp users, feel free to reject PR if we prefer not to pollute yarp with script in interpreted languages. @drdanz 

Script for helping @fjandrad data collection.

### CODE REVIEW

**Comment by pattacini** [comment]
Nice feature. I'm fine with merging this.

**Comment by traversaro** [comment]
@drdanz any comment?

**Comment by Tobias-Fischer** [comment]
This looks really useful. Would be great having this in the repository. 

@gregoire-pointeau: You might be interested in this :)

**Comment by pattacini** [comment]
@gsaponaro `tcp vs. udp` has more to do with `asynchronous vs. synchronous` communication in our framework.

**Comment by pattacini** [comment]
@gsaponaro is right about the `tag`.

@traversaro I think you can safely merge it (once you're done with the `tag` issue).

**Comment by drdanz** [comment]
@traversaro Sorry for the delay...
This looks like a useful feature. I don't think we have a policy about python scripts, but I'm not against installing them as normal executables.

Anyway, a couple of comments:

1. I think you can just install the script, I wouldn't care about Python being installed or not, since this is a runtime dependency and not a build dependency. If this is always installed, one could install yarp, try to run the script, realize that python is missing, install python and run the script again. Otherwise he will have to install yarp, try to run the script, realize that the script is missing, find out why the script is missing, install python, re-run cmake, install yarp again, and finally run the script.

2. Perhaps the `yarp_install` macro already handles this, but I can't remember, so disregard this if it already does all of it... Installing a script makes a big difference when yarp is installed, and when yarp is in the build tree because in the latter mode, the script won't be in the path. there should be a copy of the python script in the <build>/bin directory, possibly ensuring that it is copied again at build time whenever the script is modified. Also we should be sure to handle multi configuration generators (i.e. MSVC and Xcode), as the binaries will be in the Release/Debug subfolder, this is what I think is missing in `yarp_install`.

**Comment by pattacini** [comment]
@traversaro any news on this?

**Comment by traversaro** [comment]
Processing the backlog post-IROS, I am arriving also on this. : )

**Comment by traversaro** [comment]
I should have addressed all the commens. @drdanz

**Comment by drdanz** [comment]
Appveyor does not look happy... even though it seems unrelated to your patch, something else happened. I'd like to see everything working there as well, therefore I will investigate on monday

**Comment by pattacini** [comment]
It seems we are all happy now with CI's (barring `coveralls`...)

**Comment by drdanz** [comment]
I rebased it over master because I made some changes to `YarpInstallationHelpers.cmake` today.
As soon as all the builds are finished I will merge it.

**Pull request merged**
