### PR TITLE
yarp ros documentation revised (#769)

### PR DESCRIPTION
**Pull request by lornat75**
Re-organize documentation so that separate topics are in separate pages. Brought examples using Node, Subscriber and Publisher to the foreground.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/772%23issuecomment-221795320%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/772%23issuecomment-221795320%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Considered%20this%20is%20just%20a%20re-organization%20of%20the%20repository%20I%20would%20wait%20a%20little%20for%20somebody%20to%20comment%2C%20then%20proceed%20with%20merging.%22%2C%20%22created_at%22%3A%20%222016-05-26T07%3A15%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1403333%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lornat75%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/772#issuecomment-221795320'>General Comment</a></b>
- <a href='https://github.com/lornat75'></a> Considered this is just a re-organization of the repository I would wait a little for somebody to comment, then proceed with merging.

<a href='https://www.codereviewhub.com/robotology/yarp/pull/772?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/772?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/772'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/772'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by lornat75** [comment]
Considered this is just a re-organization of the repository I would wait a little for somebody to comment, then proceed with merging.

**Comment by drdanz** [comment]
@lornat75 Looks good to me, merged. Thanks

**Comment by lornat75** [comment]
Should I port it to devel?

**Comment by drdanz** [comment]
@lornat75 No thanks, I already merged `master` into `devel` after merging this pull request, see e7cf7845b7607cbfa04df3d339379bbd312b734c

**Pull request merged**
