### PR TITLE
Fix failure in compiling YARP headers in C++14 mode with GCC

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/yarp/issues/1614

### CODE REVIEW

**Comment by traversaro** [comment]
cc @S-Dafarra @gabrielenava

**Comment by S-Dafarra** [comment]
LGTM. Robotology superbuild compiles.

**Comment by traversaro** [comment]
Friendly ping @drdanz , on C++14 YARP (including master) is completely unusable due to this.

**Comment by traversaro** [comment]
Thanks, I am rebasing and merging.

**Comment by traversaro** [comment]
I think the spirit is "if `YARP_NO_DEPRECATED` is defined, do not export deprecated symbols".

**Comment by drdanz** [comment]
Hmm ok, sounds useless, since if `YARP_NO_DEPRECATED` is enabled, these parts are not compiled at all... it should probably just have been

```c++
#ifndef YARP_NO_DEPRECATED
#  define YARP_DEPRECATED_API YARP_DEPRECATED YARP_OS_API
#  define YARP_DEPRECATED_API_MSG(X) YARP_DEPRECATED_MSG(X) YARP_OS_API
#endif
```

BTW, this issue is the same I reported here: https://stackoverflow.com/questions/40886628


Also I made a very quick test, and this seems to work: `[[deprecated]] [[gnu::visibility("hidden")]]`

**Comment by drdanz** [comment]
I made even more tests, and I believe that the right way to go is to use `[[deprecated]] [[gnu::visibility("hidden")]]` (see my own reply to the stackoverflow issue in previous comment).
@traversaro If you want to merge this I have no objections, but I'd be happier with a C++14 style fix :wink:

**Comment by traversaro** [comment]
Can you link the GCC and clang docs on `[[gnu::visibility("hidden")]]` attribute style? I am unable to find it.

**Comment by traversaro** [comment]
This is also breaking compilation of `gazebo-yarp-plugins` with Gazebo 9 (see https://github.com/robotology/robotology-superbuild/issues/59). Given that C++14's style attribution are not properly documented and I am not sure if that works on clang (and on what version of clang : )). I would go for merging this in tits current form.

**Comment by drdanz** [comment]
Merged, thanks.

**Pull request merged**
