### PR TITLE
Modify libYARP_robotinterface to enable proper error propagation

### PR DESCRIPTION
**Pull request by traversaro**
This PR completes what was originally added in https://github.com/robotology/yarp/pull/2168, and finish the implementation of Part 1 of https://github.com/robotology/yarp/issues/2005 . 

In particular, the main difference w.r.t.  https://github.com/robotology/yarp/pull/2168 is that in that case, the API exposed was extremely complicated to use: as soon as there was an error in the input XML file, the whole process that called the `YARP_robotinterface` library was crashed. Clearly, this is not ideal for a library, and this PR modifies the library to ensure that the error is correctly propagated to the caller. Furthermore, to test this functionality this PR also restructure the parser to permit to load the XML configuration also from directly a string, and not from a file.

The public API changed w.r.t.  https://github.com/robotology/yarp/pull/2168, but this is not a big problem as the API was never released as part of a YARP release since the merge of   https://github.com/robotology/yarp/pull/2168 .  

Example code snippet that uses the new API:
~~~cpp
// Load the XML configuration file 
std::string pathToXmlConfigurationFile = ...;
yarp::robotinterface::XMLReader reader;
yarp::robotinterface::XMLReaderResult result = reader.getRobotFromFile(pathToXmlConfigurationFile);

if (!result.isParsingSuccessful) {
    // Handle error 
    // ...
}

// Enter the startup phase, that will open all the devices and  call attach if necessary
bool ok = result.robot.enterPhase(yarp::robotinterface::ActionPhaseStartup);

if (!ok) {
    // Handle error 
    // ...
}


// At this point, the system is running and the thread that called the 
// enterPhase methods does not need to do anything else 

// This code need to be executed when you want to close the robot
// Close robot, that will close all the devices and  call detach if necessary
ok = result.robot.enterPhase(yarp::robotinterface::ActionPhaseInterrupt1);
ok = ok && result.robot.enterPhase(yarp::robotinterface::ActionPhaseShutdown);
if (!ok) {
    // Handle error 
    // ...
}
~~~

### CODE REVIEW

**Comment by traversaro** [comment]
There is a style check failure in: 
> [NOT OK (Contains trailing white spaces)] src/yarplaserscannergui/main.cpp

As this file was not touched by this  PR, I think the check is not relevant.

**Comment by traversaro** [comment]
The test are failing  probably due to some existing memory leak in the `yarprobotinterface` that is now revealed as we call those methods in proper tests, I will investigate them.

**Comment by drdanz** [comment]
One leak is caused by a missing `delete driver->driver;` before `delete driver;` here:

https://github.com/robotology/yarp/blob/36df11c3b6162f8bebde1ed55ea8cf5518ce2e19/src/libYARP_robotinterface/src/yarp/robotinterface/Device.cpp#L64-L78

I'm not sure if there are others...

**Comment by traversaro** [comment]
I should have fixed all memory leaks with: 
* https://github.com/robotology/yarp/pull/2288/commits/f6029816e7bcbbf958d843a8ddf297c01ad7f108
* https://github.com/robotology/yarp/pull/2288/commits/7c4ad2202537114ca6aeba389ef991c0585ab28b

**Comment by drdanz** [comment]
Merged, thanks.

**Pull request merged**
