### PR TITLE
Move find_package(ZFP) from CMakeLists.txt to cmake/YarpFindDependencies.cmake

### PR DESCRIPTION
**Pull request by Nicogene**
Please review code:

### CODE REVIEW

**Comment by drdanz** [comment]
Appveyor was failing for unrelated issues. Please rebase over latest devel

**Comment by Nicogene** [comment]
@drdanz Travis CI failed in each test where `TRAVIS_WITH_CXX11` is enabled. In particular it can't find yarp:
```
 CMake Error at CMakeLists.txt:11 (FIND_PACKAGE):
  By not providing "FindYARP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "YARP", but
  CMake did not find one.
  Could not find a package configuration file provided by "YARP" with any of
  the following names:
    YARPConfig.cmake
    yarp-config.cmake
```

Is it an issue related to my modifications?

**Comment by drdanz** [comment]
rebased, let's wait and see if it still fails

**Comment by drdanz** [comment]
Merged, thanks

**Pull request merged**
