### PR TITLE
Refactor Audio Stack

### PR DESCRIPTION
**Pull request by drdanz**
Refactor a lot of the audio stack (mostly done by @randaz81)

#### `YARP_sig`

* The `yarp::sig::Sound` class was heavily refactored:
  - New data types:
    * `Sound::audio_sample` (`short int`)
  - Changed signatures:
    * ```diff
      - Sound(int bytesPerSample)
      + Sound(size_t bytesPerSample)
      ```
    * ```diff
      - int get(size_t sample, size_t channel) const
      + audio_sample get(size_t sample, size_t channel) const
      ```
    * ```diff
      - void set(int value, size_t sample, size_t channel)
      + void set(audio_sample value, size_t sample, size_t channel)
      ```
    * ```diff
      - void setSafe(int value, size_t sample, size_t channel)
      + void setSafe(audio_sample value, size_t sample, size_t channel)
      ```
    * ```diff
      - size_t getFrequency() const
      + int getFrequency() const
      ```
    * ```diff
      - void setFrequency(size_t freq)
      + void setFrequency(int freq)
      ```
  - Removed methods:
    * `unsigned char *getRawData() const`
    * `size_t getRawDataSize() const`
  - Added methods:
    * `bool operator==(const Sound& alt) const`
    * `bool clearChannel(size_t channel)`
    * `Sound extractChannelAsSound(size_t channel_id) const`
    * `std::vector<std::reference_wrapper<audio_sample>> getChannel(size_t channel_id)`
    * `bool replaceChannel(size_t id, Sound channel)`
    * `std::vector<std::reference_wrapper<audio_sample>> getInterleavedAudioRawData() const`
    * `std::vector<std::reference_wrapper<audio_sample>> getNonInterleavedAudioRawData() const`
    * `std::string toString() const`
    * `double getDuration() const`

#### `YARP_dev`
* Added `yarp::dev::CircularAudioBuffer` and `yarp::dev::AudioBufferSize`
  classes.
* IAudioRender:
  - Changed signatures:
    * ```diff
      - bool renderSound(yarp::sig::Sound& sound)
      + bool renderSound(const yarp::sig::Sound& sound)
      ```
  - Added methods:
    * `bool getPlaybackAudioBufferMaxSize(yarp::dev::AudioBufferSize& size)`
    * `bool getPlaybackAudioBufferCurrentSize(yarp::dev::AudioBufferSize& size)`
    * `bool resetPlaybackAudioBuffer()`
    * `bool getRecordingAudioBufferMaxSize(yarp::dev::AudioBufferSize& size)`
    * `bool getRecordingAudioBufferCurrentSize(yarp::dev::AudioBufferSize& size)`
    * `bool resetRecordingAudioBuffer()`
* IAudioGrabberSound:
  - Changed signatures:
    * ```diff
      - bool getSound(yarp::sig::Sound& sound)
      + bool getSound(yarp::sig::Sound& sound, size_t min_number_of_samples, size_t max_number_of_samples, double max_samples_timeout_s)
      ```
  - Added methods:
    * `bool getRecordingAudioBufferMaxSize(yarp::dev::AudioBufferSize& size)`
    * `bool getRecordingAudioBufferCurrentSize(yarp::dev::AudioBufferSize& size)`
    * `bool resetRecordingAudioBuffer()`

### Devices

* The `portaudio` and the `ServerSoundGrabber` device drivers are deprecated.
* New devices:
  - `audioRecorderWrapper`
  - `portaudioRecorder`
  - `portaudioPlayer`
  - `audioPlayerWrapper`
  - `fakeSpeaker`
  - `fakeMicrophone`

#### `ServerSoundGrabber`
* No longer implements `IAudioGrabberSound`.

#### `ServerFrameGrabber`
* No longer implements audio interfaces.

#### `yarphear`

* Use `portaudioPlayer` instead of `portaudio` device.

CC: @randaz81

### CODE REVIEW

**Comment by drdanz** [comment]
> Since `ServerFrameGrabber` no longer implements the audio interfaces, can be deprecated/removed in favour of the "new" `ServerGrabber` ?

I have no idea, you are the expert! Is there anything left using `ServerFrameGrabber`?

**Comment by Nicogene** [comment]
> Is there anything left using ServerFrameGrabber?

I think not, @barbalberto do you agree?

**Comment by drdanz** [comment]
As discussed with @Nicogene and @randaz81 we will deprecate ServerFrameGrabber in the next release

**Comment by Nicogene** [comment]
Merged, thanks!

**Pull request merged**
