### PR TITLE
move math operators outside yarp::math namespace

### LINKED ISSUE #1602: Operators should not be in the yarp::math namespace
`Vector` and `Matrix` operators are defined inside the `yarp::math` namespace.

https://github.com/robotology/yarp/blob/29e9108a52713dbe737d9a9c44a62da3adc3ce51/src/libYARP_math/include/yarp/math/Math.h#L16-L27

This means that, in order to perform an operation (for example `Vector b = a + s;`), the user has to add `using namespace yarp::math;` or to call the operator explicitly, i.e. (I think) something like this: `Vector b = yarp::math::operator+(a, s);`
The first option is considered bad practice, and the second option is just wrong.

I think we could just move them outside of the namespace, the only effect is if someone is using the second syntax, but I don't think anyone would be doing that...

### PR DESCRIPTION
**Pull request by damn1**
fixes #1602

### CODE REVIEW

**Comment by jgvictores** [comment]
Opinion on the open [proposal](https://github.com/robotology/yarp/issues/1602#issuecomment-380063350) of open issue #1602 ?

**Comment by Nicogene** [comment]
@jgvictores we discussed it internally and for the moment we are not planning to move the operators in a different `namespace`.
In the [example](http://www.cplusplus.com/reference/utility/rel_ops/) you pointed out the operators are in the `namespace rel_ops` because these are templates and this will  introduce these overloads for all types not defining their own.

**Comment by Nicogene** [comment]
Merged, thanks!

**Comment by jgvictores** [comment]
The origin of the inclusion of the operators in the namespace, cited [here](https://github.com/robotology/yarp/issues/1602#issuecomment-379692519), was `follow the strict guidelines`.

Could the `PR type: Bugfix` label be removed?

**Pull request merged**
