### PR TITLE
InstallBasicPackageFiles: Support for CMake < 3.9

### LINKED ISSUE #1727: YARP 2.3.73.5 (current devel branch) broken with CMake 3.5
Originally reported by @PeterBowman in 

> https://github.com/robotology/yarp/blob/57ed8688762e5fbaf7dfa5d202a0427e314f2ee3/cmake/template/YARPConfig.cmake.in#L142-L144
>
>This is breaking builds in YARP downstreams on Xenial (CMake 3.5.1). Support for additional parameters to `find_dependency()` was added at CMake 3.9 (which is used by Travis, hence no CI build errors).
>
> Docs:
> * https://cmake.org/cmake/help/v3.5/module/CMakeFindDependencyMacro.html
> * https://cmake.org/cmake/help/v3.9/module/CMakeFindDependencyMacro.html
> 
> cc @drdanz

### PR DESCRIPTION
**Pull request by drdanz**
This should fix #1727, but I don't have a system to test in this moment.

Can anyone with CMake 3.5 test this, please? @traversaro @PeterBowman @pattacini

### CODE REVIEW

**Comment by traversaro** [comment]
I think it is necessary only to fix https://github.com/robotology/yarp/blob/57ed8688762e5fbaf7dfa5d202a0427e314f2ee3/cmake/template/YARPConfig.cmake.in#L142-L144 .

**Comment by drdanz** [comment]
Right, I forgot about that, sorry...

**Comment by drdanz** [comment]
@traversaro last commit should fix it...

**Comment by pattacini** [comment]
@Nicogene I must have cleaned up `icub-main` by getting shot of `YARP_INCLUDE_DIRS` and `YARP_DEFINES`.

**Comment by Nicogene** [comment]
There was still one `YARP_INCLUDE_DIRS` in `embObjLib.cmake`
Fixed by robotology/icub-main@49f0f0bd76b802d5790d6d06d1e5f26d2a3618f1

**Comment by PeterBowman** [comment]
👍 Works for me, thanks.

**Comment by traversaro** [comment]
Working for me.

**Comment by Nicogene** [comment]
Since this build (https://travis-ci.org/robotology/yarp/builds/387342747?utm_source=github_status&utm_medium=notification), yarp compiled static seems broken, anyone knows why ?
BTW we can merge this PR, the fail is not related.

**Comment by lrapetti** [comment]
Can we merge this PR?

**Comment by PeterBowman** [comment]
> Since this build (https://travis-ci.org/robotology/yarp/builds/387342747?utm_source=github_status&utm_medium=notification), the thrift tests seems broken when yarp is compiled static. Anyone knows why ?

@Nicogene possibly related: https://github.com/robotology/yarp/pull/1715#issuecomment-395065930.

**Comment by PeterBowman** [comment]
> Anyone knows why ?

@Nicogene an internal `find_dependency(Eigen3)` (via YARP_eigenConfig.cmake) call expects a `Eigen3_FOUND` variable, but it's spelled differently:
https://github.com/robotology/yarp/blob/e709b46698ecb4eb335bd52b17e4163393836dca/cmake/ycm-0.7.0/3rdparty/FindEigen3.cmake#L66

I can replicate this with CMake 3.5 and static YARP at latest devel (e709b46) using own YCM modules. Downstream projects are configured once successfully (no `EIGEN3_INCLUDE_DIR` variable in cache, yet, thus we are in [this block](https://github.com/robotology/yarp/blob/e709b46698ecb4eb335bd52b17e4163393836dca/cmake/ycm-0.7.0/3rdparty/FindEigen3.cmake#L70-L94)), then fail repeatedly with the same error (missing `YARP_eigen` because Eigen3 could not be found - [here](https://github.com/robotology/yarp/blob/e709b46698ecb4eb335bd52b17e4163393836dca/cmake/ycm-0.7.0/3rdparty/FindEigen3.cmake#L64-L66) using `EIGEN3_FOUND`). See also https://github.com/PeterBowman/yarp/commit/a5500ad87c5a0c0e853f89c25860ee97b633b518, [Travis](https://travis-ci.org/PeterBowman/yarp/builds/390475342).

**Pull request merged**
