### PR TITLE
Optimize yarp::os::Stamp

### PR DESCRIPTION
**Pull request by Nicogene**
This PR optimize `Stamp::write()` and `Stamp::read()` in textMode.

Please review code.

### CODE REVIEW

**Comment by traversaro** [comment]
There are tests covering this methods?

**Comment by Nicogene** [comment]
Yes, `StampTest` test also the Stamp sent in textMode.

**Comment by drdanz** [comment]
According to the tests we performed, this reduces the impact of adding a timestamp to the envelope of about 80~90% 🎉

**Comment by drdanz** [comment]
Merged thanks

**Pull request merged**
