### PR TITLE
Fix any issue (including hardware problems)

### PR DESCRIPTION
**Pull request by drdanz**
#### `PortCore`

* Fix any issues by entrusting a Superior Entity.

### `companion`

* When logic fails, it's time to `yarp pray`. Watch out for palindrome mode.

### CODE REVIEW

**Comment by lornat75** [comment]
too much smart working on april 1st...

**Comment by randaz81** [comment]
LGTM, I'd add just a warning message if the user invokes the pray command on a non-existing portgod: this condition is currently not detected  :-)

**Comment by drdanz** [comment]
> LGTM, I'd add just a warning message if the user invokes the pray command on a non-existing portgod: this condition is currently not detected :-)

Actually I fixed it yesterday night :wink:

**Comment by drdanz** [comment]
Merged, thanks.

**Pull request merged**
