### PR TITLE
[cmake] Workaround for https://github.com/robotology/yarp/issues/1198

### PR DESCRIPTION
**Pull request by traversaro**
cc @drdanz

### CODE REVIEW

**Comment by traversaro** [comment]
Rationale: homebrew just update CMake and so yarp `devel` is broken for all users that have an updated homebrew.

**Comment by traversaro** [comment]
@claudiofantacci

**Comment by claudiofantacci** [comment]
By applying this commit I'm now able to use CMake 3.8.1 flawlessly.

**Comment by drdanz** [comment]
Merging this temporarily, but I intend to roll it back and exclude only the broken versions as soon as the bug is fixed in CMake

**Comment by drdanz** [comment]
Oops, it was merged already :joy:

**Pull request merged**
