### PR TITLE
Creation of the .msg file by yarpidl_rosmsg

### PR DESCRIPTION
**Pull request by plinioMoreno**
The "| install -D /dev/stdin " solves the problem when the .msg file is in a directory, so the directory is created properly even if the .msg file is part of a customized message created by the user
in its catkin_workspace directory.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/plinioMoreno%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3798890%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-226892770%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-06-17T22%3A05%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3798890%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/plinioMoreno%22%7D%7D%2C%20%7B%22body%22%3A%20%22Will%20this%20work%20on%20windows%3F%20cc%20%40pattacini%20%40randaz81%20%22%2C%20%22created_at%22%3A%20%222016-06-20T09%3A51%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22Of%20course%20not%20%3Awink%3A%20%22%2C%20%22created_at%22%3A%20%222016-06-20T09%3A53%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%3Agun%3A%22%2C%20%22created_at%22%3A%20%222016-06-20T10%3A05%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20command%20to%20be%20issued%20in%20that%20line%20is%20%5C%22rosmsg%20show%20....%5C%22%2C%20which%20is%20a%20ROS%20script.%20Since%20ROS%20is%20not%20supported%20for%20windows%20%28see%20%5Bhere%5D%28http%3A//wiki.ros.org/kinetic/Installation%29%29%2C%20that%20part%20of%20the%20code%20will%20not%20work%20on%20windows.%20On%20windows%20what%20you%20can%20do%20is%20to%20search%20for%20the%20message%20on%20the%20web%2C%20using%20the%20%5BfetchFromWeb%5D%28https%3A//github.com/robotology/yarp/blob/master/src/idls/rosmsg/src/RosType.cpp%23L564%29.%5Cr%5Cn%5Cr%5CnThe%20other%20OS%20where%20that%20line%20can%20be%20tested%20is%20OS%20X%2C%20but%20on%20the%20ROS%20side%20is%20experimental.%22%2C%20%22created_at%22%3A%20%222016-06-20T11%3A43%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3798890%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/plinioMoreno%22%7D%7D%2C%20%7B%22body%22%3A%20%22Right%2C%20in%20this%20case%20it%20makes%20sense.%20It%20is%20the%20whole%20fetching-from-ros%20part%20that%20should%20not%20be%20built%20on%20windows%2C%20but%20we%20can%20take%20care%20of%20that%20later.%5Cr%5Cn%40plinioMoreno%20Do%20you%20mind%20rebasing%20over%20the%20latest%20%60master%60%20and%20adding%20some%20documentation%20about%20this%20change%20in%20%60doc/release/v2_3_66_1.md%60%3F%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-20T12%3A49%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22what%20about%20leveraging%20on%20code%20from%20%60yarpidl_rosmsg%60%20when%20executed%20with%20the%20flag%3A%20%60--web%20true%60%3F%22%2C%20%22created_at%22%3A%20%222016-06-20T13%3A14%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1403333%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lornat75%22%7D%7D%2C%20%7B%22body%22%3A%20%22Sorry%2C%20%40drdanz%20I%20forgot%20to%20do%20the%20rebase%20before%20the%20commit%20of%20the%20documentation%20file.%22%2C%20%22created_at%22%3A%20%222016-06-20T13%3A51%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3798890%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/plinioMoreno%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40plinioMoreno%20Something%20went%20wrong%20in%20the%20rebase%2C%20see%20the%20%5C%22Commits%5C%22%20tab%5Cr%5Cnplease%20try%20this%3A%5Cr%5Cn%5Cr%5Cn%60%60%60%5Cr%5Cngit%20fetch%20origin%5Cr%5Cngit%20rebase%20origin/master%5Cr%5Cngit%20push%20--force%20plinioMoreno%20master%5Cr%5Cn%60%60%60%5Cr%5Cn%5Cr%5Cn%28assuming%20that%20in%20your%20local%20clone%20%60origin%60%20is%20the%20remote%20name%20for%20%60robotology/yarp%60%20and%20%60plinioMoreno%60%20is%20the%20remote%20name%20for%20%60plinioMoreno/yarp%60%29%22%2C%20%22created_at%22%3A%20%222016-06-20T13%3A53%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3E%20Sorry%2C%20%40drdanz%20I%20forgot%20to%20do%20the%20rebase%20before%20the%20commit%20of%20the%20documentation%20file.%5Cr%5Cn%5Cr%5CnNo%20problem%2C%20just%20try%20again%20%3B%29%22%2C%20%22created_at%22%3A%20%222016-06-20T13%3A54%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27m%20sorry%2C%20I%20did%20the%20same%20thing%20twice.%20What%20a%20mess.%22%2C%20%22created_at%22%3A%20%222016-06-20T14%3A10%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3798890%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/plinioMoreno%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-226892770%22%2C%20%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-227098448%22%2C%20%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-227098804%22%2C%20%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-227101432%22%2C%20%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-227120041%22%2C%20%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-227132789%22%2C%20%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-227138259%22%2C%20%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-227147838%22%2C%20%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-227148243%22%2C%20%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-227148493%22%2C%20%22https%3A//github.com/robotology/yarp/pull/804%23issuecomment-227153065%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/plinioMoreno'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/804#issuecomment-226892770'>General Comment</a></b>
- <a href='https://github.com/plinioMoreno'></a> :shipit:
- <a href='https://github.com/drdanz'></a> Will this work on windows? cc @pattacini @randaz81
- <a href='https://github.com/pattacini'></a> Of course not :wink:
- <a href='https://github.com/drdanz'></a> :shipit::gun:
- <a href='https://github.com/plinioMoreno'></a> The command to be issued in that line is "rosmsg show ....", which is a ROS script. Since ROS is not supported for windows (see [here](http://wiki.ros.org/kinetic/Installation)), that part of the code will not work on windows. On windows what you can do is to search for the message on the web, using the [fetchFromWeb](https://github.com/robotology/yarp/blob/master/src/idls/rosmsg/src/RosType.cpp#L564).
The other OS where that line can be tested is OS X, but on the ROS side is experimental.
- <a href='https://github.com/drdanz'></a> Right, in this case it makes sense. It is the whole fetching-from-ros part that should not be built on windows, but we can take care of that later.
@plinioMoreno Do you mind rebasing over the latest `master` and adding some documentation about this change in `doc/release/v2_3_66_1.md`?
- <a href='https://github.com/lornat75'></a> what about leveraging on code from `yarpidl_rosmsg` when executed with the flag: `--web true`?
- <a href='https://github.com/plinioMoreno'></a> Sorry, @drdanz I forgot to do the rebase before the commit of the documentation file.
- <a href='https://github.com/drdanz'></a> @plinioMoreno Something went wrong in the rebase, see the "Commits" tab
please try this:
```
git fetch origin
git rebase origin/master
git push --force plinioMoreno master
```
(assuming that in your local clone `origin` is the remote name for `robotology/yarp` and `plinioMoreno` is the remote name for `plinioMoreno/yarp`)
- <a href='https://github.com/drdanz'></a> > Sorry, @drdanz I forgot to do the rebase before the commit of the documentation file.
No problem, just try again ;)
- <a href='https://github.com/plinioMoreno'></a> I'm sorry, I did the same thing twice. What a mess.

<a href='https://www.codereviewhub.com/robotology/yarp/pull/804?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/804?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/804?approve=0'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/804'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/804'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by plinioMoreno** [comment]
:shipit:

**Comment by drdanz** [comment]
Will this work on windows? cc @pattacini @randaz81

**Comment by pattacini** [comment]
Of course not :wink:

**Comment by drdanz** [comment]
:shipit::gun:

**Comment by plinioMoreno** [comment]
The command to be issued in that line is "rosmsg show ....", which is a ROS script. Since ROS is not supported for windows (see [here](http://wiki.ros.org/kinetic/Installation)), that part of the code will not work on windows. On windows what you can do is to search for the message on the web, using the [fetchFromWeb](https://github.com/robotology/yarp/blob/master/src/idls/rosmsg/src/RosType.cpp#L564).

The other OS where that line can be tested is OS X, but on the ROS side is experimental.

**Comment by drdanz** [comment]
Right, in this case it makes sense. It is the whole fetching-from-ros part that should not be built on windows, but we can take care of that later.
@plinioMoreno Do you mind rebasing over the latest `master` and adding some documentation about this change in `doc/release/v2_3_66_1.md`?

**Comment by lornat75** [comment]
what about leveraging on code from `yarpidl_rosmsg` when executed with the flag: `--web true`?

**Comment by drdanz** [comment]
@plinioMoreno Something went wrong in the rebase, see the "Commits" tab
please try this:

```
git fetch origin
git rebase origin/master
git push --force plinioMoreno master
```

(assuming that in your local clone `origin` is the remote name for `robotology/yarp` and `plinioMoreno` is the remote name for `plinioMoreno/yarp`)

**Comment by drdanz** [comment]
> Sorry, @drdanz I forgot to do the rebase before the commit of the documentation file.

No problem, just try again ;)

**Comment by plinioMoreno** [comment]
I'm sorry, I did the same thing twice. What a mess.

**Comment by drdanz** [comment]
@plinioMoreno What is going on? :open_mouth: Let me know if I can help...

**Comment by plinioMoreno** [comment]
I decided to abort this because of the mess and start from scratch in a new pull request (#805)

**Comment by drdanz** [comment]
@plinioMoreno It wasn't really necessary to duplicate the pull request, you can always force push on your fork... Anyway let's move to the other ;)

**Pull request closed without merging**
