### PR TITLE
Control board remapper

### PR DESCRIPTION
**Pull request by traversaro**
New version of https://github.com/robotology/yarp/pull/746 , with the test failures fixed and opened against `devel` rather then `master`.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/757%23issuecomment-219368710%22%2C%20%22https%3A//github.com/robotology/yarp/pull/757%23issuecomment-219409909%22%2C%20%22https%3A//github.com/robotology/yarp/pull/757%23issuecomment-219694283%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/757%23issuecomment-219368710%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Apparently%20the%20test%20fails%20if%20YARP%20is%20compiled%20without%20ACE%2C%20investigating.%22%2C%20%22created_at%22%3A%20%222016-05-16T07%3A50%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22Dynamically%20loaded%20drivers%20were%20not%20working%20without%20ACE%2C%20the%20bug%20was%20fixed%20in%20https%3A//github.com/robotology/yarp/pull/757/commits/d117fffc0392a5cb13a7b0b9352b5825a0aa4785%20.%20%22%2C%20%22created_at%22%3A%20%222016-05-16T12%3A06%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40traversaro%20Looks%20good%20now%2C%20but%20you%20opened%20it%20again%20against%20master...%22%2C%20%22created_at%22%3A%20%222016-05-17T11%3A46%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/757#issuecomment-219368710'>General Comment</a></b>
- <a href='https://github.com/traversaro'></a> Apparently the test fails if YARP is compiled without ACE, investigating.
- <a href='https://github.com/traversaro'></a> Dynamically loaded drivers were not working without ACE, the bug was fixed in https://github.com/robotology/yarp/pull/757/commits/d117fffc0392a5cb13a7b0b9352b5825a0aa4785 .
- <a href='https://github.com/drdanz'></a> @traversaro Looks good now, but you opened it again against master...

<a href='https://www.codereviewhub.com/robotology/yarp/pull/757?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/757?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/757'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/757'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by traversaro** [comment]
Apparently the test fails if YARP is compiled without ACE, investigating.

**Comment by traversaro** [comment]
Dynamically loaded drivers were not working without ACE, the bug was fixed in https://github.com/robotology/yarp/pull/757/commits/d117fffc0392a5cb13a7b0b9352b5825a0aa4785 .

**Comment by drdanz** [comment]
@traversaro Looks good now, but you opened it again against master...

**Comment by traversaro** [comment]
Ahhh, my fault.

**Pull request closed without merging**
