### PR TITLE
Fix the sensors name remapping in MultipleAnalogSensorsRemapper class

### PR DESCRIPTION
**Pull request by nunoguedelha**
Fixes issue https://github.com/robotology/yarp/issues/1765. Please refer to that link for all the details on the analysis.

### CODE REVIEW

**Comment by traversaro** [comment]
Thanks @nunoguedelha .  I guess it make sense to target `master` as we will have soon the release 3.0.1 actually used in robots outside IIT.

**Comment by nunoguedelha** [comment]
Sure @traversaro . But in this case, we have to keep maintaining this branch on devel, unless they merge `master` into `devel` pretty soon.

**Comment by traversaro** [comment]
In general after any PR on `master` we forward merge on `devel`, see the `CONTRIBUTING.md` docs: https://github.com/robotology/yarp/blob/master/.github/CONTRIBUTING.md#stable-branch-master .

**Comment by nunoguedelha** [comment]
### Additional information on the run tests

The fix was tested on iCubGenova04 and iCubGenova02. The robot interface completes the startup and the sensor data are available at the defined ports.
In the test, all the MTB inertial sensors on the left leg were attached to a single remapper device (`multipleanalogsensorsremapper`), itself attached to a wrapper device (`multipleanalogsensorswrapper`).
Refer to https://github.com/robotology/icub-firmware-shared/issues/24#issuecomment-400772048 for gurther comments and plots on the tests on iCubGenova04.

FYI The iCubGenova04 configuration files changes required for using this new interfaces have been PRed to **robots-configuration** `devel` branch for now (https://github.com/robotology/robots-configuration/pull/69).

**Comment by Nicogene** [comment]
@nunoguedelha I have changed the base branch of the PR to master, please rebase your branch on latest master and push.

**Comment by traversaro** [comment]
To be honest, without this fix the `multipleanalogsensorsremapper` is totally unusable. So I think a phrase in the release notes will be beneficial I guess. : )

**Comment by drdanz** [comment]
Rebased, added release notes, and merged, thanks.

**Comment by nunoguedelha** [comment]
Thanks @drdanz !

**Pull request merged**
