### PR TITLE
Add ControlBoard_nws_yarp and ControlBoard_ros devices

### PR DESCRIPTION
**Pull request by drdanz**
### Devices

* Added `controlBoard_nws_yarp` and `controlBoard_nws_ros` devices.
  These devices, together with `controlboardremapper` can be used to replace
  `controlboardwrapper2`.
  Important differences with `controlboardwrapper2`:
  * These devices do not handle networks, use `controlboardremapper` for that.
  * All deprecated parameters were removed
  * `controlBoard_nws_ros` requires that the `yarp::dev::IAxisInfo` is
    implemented in the device
  * Periods are in seconds, and not in milliseconds.

------

`ControlBoard_nws_yarp` + `controlboardremapper` can replace `controlboardwrapper2`.

This is an example of working xml for `yarprobotinterface`:

```.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE robot PUBLIC "-//YARP//DTD yarprobotinterface 3.0//EN" "http://www.yarp.it/DTD/yarprobotinterfaceV3.0.dtd">

<robot name="test_controlboard_nws" build="2" portprefix="test" xmlns:xi="http://www.w3.org/2001/XInclude">

    <device name="mc0" type="fakeMotionControl">
        <group name="GENERAL">
            <param name="Joints">4</param>
            <param name="AxisName"> mc0j0 mc0j1 mc0j2 mc0j3 </param>
        </group>
    </device>

    <device name="mc1" type="fakeMotionControl">
        <group name="GENERAL">
            <param name="Joints">2</param>
            <param name="AxisName"> mc1j0 mc1j1 </param>
        </group>
    </device>

    <device name="mc2" type="fakeMotionControl">
        <group name="GENERAL">
            <param name="Joints">4</param>
            <param name="AxisName"> mc2j0 mc2j1 mc2j2 mc2j3 </param>
        </group>
    </device>

   <device name="cbwl" type="controlboardremapper">
        <paramlist name="networks">
            <elem name="j0">( 0  3  0  3 )</elem>
            <elem name="j1">( 4  5  0  1 )</elem>
            <elem name="j2">( 6  7  2  3 )</elem>
        </paramlist>
        <param name="joints"> 8 </param>
        <action phase="startup" level="5" type="attach">
            <paramlist name="networks">
                <elem name="j0"> mc0 </elem>
                <elem name="j1"> mc1 </elem>
                <elem name="j2"> mc2 </elem>
            </paramlist>
        </action>
        <action phase="shutdown" level="5" type="detach" />
    </device>

    <device name="cbw_yarp" type="controlBoard_nws_yarp">
        <param name="name"> /foo/head </param>
        <action phase="startup" level="5" type="attach">
            <param name="device"> cbwl </param>
        </action>
        <action phase="shutdown" level="5" type="detach" />
    </device>

    <device name="cbw_ros" type="controlBoard_nws_ros">
        <param name="nodeName"> /zot </param>
        <param name="topicName"> /top </param>
        <action phase="startup" level="5" type="attach">
            <param name="device"> cbwl </param>
        </action>
        <action phase="shutdown" level="5" type="detach" />
    </device>

</robot>
```

### CODE REVIEW

**Comment by traversaro** [comment]
To you still plan to have `controlboardwrapper3` ? I guess this would be quite useful for robots-configuration migration. fyi @pattacini

**Comment by drdanz** [comment]
> To you still plan to have `controlboardwrapper3` ? I guess this would be quite useful for robots-configuration migration. fyi @pattacini

It's not a high priority right now, but it sounds like a good idea to me.
But I'm not planning to have 100% compatibility with `controlboardwrapper2`, for example, `period` will be in seconds, all deprecated parameters will be removed and `yarp::dev::IAxisInfo` will be required. Also all the "group" calls will go through the `controlboardremapper` which has a slightly different logic.
It will still help the migration though.

**Pull request merged**
