### PR TITLE
Improvements to "yarp plugin"

### PR DESCRIPTION
**Pull request by drdanz**
* Add method "Property::fromConfigDir" to save the name of the .ini file that generated a part of the config
* Use it to retrieve the name of the .ini file that imports a plugin
* Improve plugin command. It is now able to detect broken plugins and shows a better output. Also improve the help and implement the following commands:
   * yarp plugin --help
   * yarp plugin --list
   * yarp plugin --all
   * yarp plugin --search-path
* Update bash completion for "yarp plugin"

Examples:

```
$ yarp plugin --help
Print information about installed plugins

Usage:
 * Test a specific plugin:
     yarp plugin <pluginname>
     yarp plugin /path/to/plugin/<libraryname>.(so|dll|dylib) <pluginpart>
 * Test all the plugins:
     yarp plugin --all
 * Print a list of plugins:
     yarp plugin --list
 * Print plugin search path:
     yarp plugin --search-path
 * Print this help and exit:
     yarp plugin --help
```

```
$ yarp plugin --list
bayer
cuda
dynamixelAX12Ftdi
[...]
```

```
$ yarp plugin bayer
Yes, this is a YARP plugin
  * library:        /opt/iit/lib/yarp/yarp_bayer.so
  * system version: 5
  * class name:     yarp::os::BayerCarrier
  * base class:     yarp::os::Carrier

$ yarp plugin cuda
Yes, this is a YARP plugin
  Cannot find or load shared library

$ yarp plugin dynamixelAX12Ftdi
Yes, this is a YARP plugin
  * library:        /opt/iit/lib/yarp/dynamixelAX12FtdiDriver.so
  * system version: 5
  * class name:     yarp::dev::DynamixelAX12FtdiDriver
  * base class:     yarp::dev::DeviceDriver
*** Error in `yarp': free(): invalid size: 0x0000000002501a00 ***

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X                                                     X
  X                       WARNING                       X
  X                                                     X
  X            === This plugin is BROKEN ===            X
  X                                                     X
  X                                                     X
  X  Author information: The most plausible reason is   X
  X  that the destructor is deleting some pointer that  X
  X  is not allocated in the constructor, and that is   X
  X  not initialized to a null pointer.                 X
  X                                                     X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

```

```
$ yarp plugin --all           
Runtime plugins found:

carrier bayer
  * ini file:       /opt/iit/share/yarp/plugins/bayer.ini
  * config:         bayer (type carrier) (name bayer) (subtype recv) (library yarp_bayer) (part bayer_carrier) (code "not applicable")
  * library:        /opt/iit/lib/yarp/yarp_bayer.so
  * system version: 5
  * class name:     yarp::os::BayerCarrier
  * base class:     yarp::os::Carrier

device cuda
  * ini file:       /opt/iit/share/yarp/plugins/cuda.ini
  * config:         cuda (type device) (name cuda) (library ycuda) (part cuda)
  Cannot find or load shared library

device dynamixelAX12Ftdi
  * ini file:       /opt/iit/share/yarp/plugins/dynamixelAX12Ftdi.ini
  * config:         dynamixelAX12Ftdi (type device) (name dynamixelAX12Ftdi) (library dynamixelAX12FtdiDriver) (part dynamixelAX12Ftdi)
  * library:        /opt/iit/lib/yarp/dynamixelAX12FtdiDriver.so
  * system version: 5
  * class name:     yarp::dev::DynamixelAX12FtdiDriver
  * base class:     yarp::dev::DeviceDriver

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X                                                     X
  X                       WARNING                       X
  X                                                     X
  X            === This plugin is BROKEN ===            X
  X                                                     X
  X                                                     X
  X  Author information: The most plausible reason is   X
  X  that the destructor is deleting some pointer that  X
  X  is not allocated in the constructor, and that is   X
  X  not initialized to a null pointer.                 X
  X                                                     X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

```
$ yarp plugin --search-path
Search path:
  * yarp:       /opt/iit/lib/yarp
  * iCub:       /opt/iit/lib/iCub
```

Yes, the dynamixelAX12Ftdi is actually broken, I did not fix it (yet) because it helped testing this :grin:

### CODE REVIEW

**Comment by barbalberto** [comment]
+1 Coool!!

**Comment by lornat75** [comment]
+1

**Comment by pattacini** [comment]
I didn't look into this PR, but it'd be great if plugins doc will show up [here](http://wiki.icub.org/yarpdoc/yarp.html) as well.

**Comment by pattacini** [comment]
Btw, I confirm that the experiments on Blacky with run-time plugins seem to be successful. Shall we proceed by enabling them by default?

**Pull request merged**
