### PR TITLE
Introduce const_iterator begin() and const_iterator end() methods in yarp::sig::VectorBase class

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR is related to issue #2179 

@Nicogene

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
> Please add a file `doc/release/master/introduce_begin_end_for_const_iterator.md` describing your changes

Hi @drdanz, I uploaded `introduce_begin_end_for_const_iterator.md` file in https://github.com/robotology/yarp/pull/2182/commits/07b4592e43b528494ee875bd64d5470a35d70d1c

**Comment by Nicogene** [comment]
@GiulioRomualdi the rebase action is not working

Please rebase and push, then we will merge, thanks

**Comment by GiulioRomualdi** [comment]
Done

**Comment by Nicogene** [comment]
Merged, thanks!

**Comment by drdanz** [comment]
Apparently, the merge action is no longer working :cry:

**Comment by pattacini** [comment]
Since yesterday I've been experiencing weird flaws in GH Actions...

**Comment by Nicogene** [comment]
> Apparently, the merge action is no longer working

I had the same issue trying to push to @GiulioRomualdi remote.

Probably the **Allow edit from maintainers** was un-ticked ?

**Comment by drdanz** [comment]
> Probably the **Allow edit from maintainers** was un-ticked ?

Unfortunately, the **Allow edit from maintainers** button has just disappeared. Hopefully it is temporary, because this is a big workflow breaker

**Pull request merged**
