### PR TITLE
Add bindings for Multiple Analog Sensors interfaces

### PR DESCRIPTION
**Pull request by nunoguedelha**
### Motivation
After the integration of the multiple analog sensors interfaces and respective devices (refer to https://github.com/robotology/yarp/issues/1526, https://github.com/robotology/yarp/pull/1586, https://github.com/robotology/yarp/pull/1676) we need to access those interfaces from scripting languages like Matlab, and so, create the respective bindings.
On top of that, some redundant code is cluttering the SWIG interface file `yarp.i`, which can be avoided by using the appropriate macros.

#### Added bindings for Multiple Analog Sensors interfaces : 

- [x] minor refactoring of main header `MultipleAnalogSensorsInterfaces.h` defining the interfaces
- [x] added main header to yarp/dev/all.h for a proper inclusion of the interfaces definitions in the mex source files `yarpXXX_wrap.cxx`
- [x] include main interfaces header in `yarp.i` and wrapped the cast  functions `(PolyDriver*)->view(<sensor_interface*>)` for each one  of the interfaces
- [x] extended the new interfaces for wrapping the  methods which Swig struggles to handle

#### Did some refactoring in the SWIG interface file `yarp.i` for reducing redundant code : 
- [x] all wrappers for casting from PolyDriver to specific device interfaces are now generated through a Swig macro.
- [x] all new class extensions are done using a Swig macro defined in `macrosForMultipleAnalogSensors.i`
- [x] refactored the from/toMatlab() wrappers and extended them to the classes : `std::vector<double>`, `std::vector<bool>`, `std::vector<int>`.

(`std::vector<std::string>` is a bit more tricky and was left out for now.)

- [x] Update the changelog

### CODE REVIEW

**Comment by nunoguedelha** [comment]
CC @traversaro

**Comment by nunoguedelha** [comment]
@traversaro , I'm still completing the last point (impacting [IVector_fromTo_matlab.i](https://github.com/robotology/yarp/blob/master/bindings/matlab/IVector_fromTo_matlab.i)), but you can already review the other changes in the current commits.

**Comment by Nicogene** [comment]
Please add few lines in the changelog

**Comment by nunoguedelha** [comment]
CC @fjandrad

**Comment by Nicogene** [comment]
Please rebase over the latest `devel` and resolve the conflict, thanks!

**Comment by traversaro** [comment]
By the way, the conflicts are probably due to https://github.com/robotology/yarp/pull/1757 , i.e. `CAST_POLYDRIVER_TO_INTERFACE` needs to be used also with the `IInterfaceControl`.

**Comment by jgvictores** [comment]
@nunoguedelha `CAST_POLYDRIVER_TO_INTERFACE` looks really cool, I believe it's something for which I couldn't come up with a solution within #1607. Thanks!

Regarding the files added within the PR, I'd like to share a small concern.

https://github.com/robotology/yarp/issues/698 was open due to a new file `bindings/things.i` (included by distributed `yarp.i`) being added to YARP but not distributed within the YARP Windows binary installer. This was fixed by the removal of `bindings/things.i`.

This PR adds `bindings/macrosForMultipleAnalogSensors.i` and ` bindings/matlab/vectors_fromTo_matlab.i` (both for inclusion by `yarp.i`). Does anybody (@mbrunettini @traversaro @drdanz  ?) know how/where the YARP Windows binary installer packaging is done to avoid reaching the same situation?

**Comment by traversaro** [comment]
> Regarding the files added within the PR, I'd like to share a small concern.

I am not 100% sure, but I guess it should be sufficient to add all the files that we want to install to https://github.com/robotology/yarp/blob/devel/bindings/CMakeLists.txt#L91 . All the installation logic should be there, I would expect the Windows installer to just collect what is installed by the CMake install target and put in the installer.

**Comment by PeterBowman** [comment]
> Does anybody (...) know how/where the YARP Windows binary installer packaging is done to avoid reaching the same situation?

@jgvictores see [robotology/yarp-packaging](https://github.com/robotology/yarp-packaging). Per [/windows/README.txt](https://github.com/robotology/yarp-packaging/blob/d6327912c72676111fcdbb1bef21d2bfec53966c/windows/README.txt):

> (...) Everything is built with CMake, so you can always search for the relevant *.sln file and open it to build manually.

**Comment by nunoguedelha** [comment]
@traversaro @PeterBowman Thanks for the clarifications.

**Comment by jgvictores** [comment]
Should https://github.com/nunoguedelha/yarp/blob/feature/addMultipleAnalogSensorsBindings/bindings/CMakeLists.txt#L91 be changed from:
```cmake
foreach(f CMakeLists.txt yarp.i README.md)
```
to:
```cmake
foreach(f CMakeLists.txt yarp.i README.md macrosForMultipleAnalogSensors.i matlab/vectors_fromTo_matlab.i)
```
or similar?

**Comment by Nicogene** [comment]
So it is needed an additional change in `bindings/CMakeLists.txt` before merging right?

**Comment by jgvictores** [comment]
That's what I've understood from the comments above. : )

**Comment by traversaro** [comment]
Yep, @nunoguedelha can you do the modification?

**Comment by nunoguedelha** [comment]
Sure, done.

**Comment by Nicogene** [comment]
Merged, thanks!

**Comment by jgvictores** [comment]
After some thought on #1776, pretty sure this will suffer from `matlab/vectors_fromTo_matlab.i` losing the `matlab/` path, and will therefore not be found by `yarp.i`. Commenting here as this ( `matlab/vectors_fromTo_matlab.i`) has been merged to `devel`, whereas #1776 affects `master`.

**Comment by PeterBowman** [comment]
> After some thought on #1776, pretty sure this will suffer from `matlab/vectors_fromTo_matlab.i` losing the `matlab/` path...

Confirming that `vectors_fromTo_matlab.i` is installed into `<prefix>/share/yarp/bindings/` while `<prefix>/share/yarp/bindings/matlab/` is expected.

> ...and will therefore not be found by `yarp.i`.

Can't test it by myself, but I'm curious about the following lines (introduced by this PR):

https://github.com/robotology/yarp/blob/4bca59c4f41bff16e9b4d453257878ab263745be/bindings/yarp.i#L452-L455

There is no `SWIGMATLAB` macro listed in the [SWIG docs](http://www.swig.org/Doc3.0/Preprocessor.html#Preprocessor_condition_compilation). How does it actually get defined?

**Comment by nunoguedelha** [comment]
> Confirming that vectors_fromTo_matlab.i is installed into <prefix>/share/yarp/bindings/ while <prefix>/share/yarp/bindings/matlab/ is expected

@PeterBowman @jgvictores this is indeed a real issue and is being addressed. The bindings used to be generated using directly the `yarp.i` interface file from the source directory. The generation process is being improved and will use the file from the install directory (https://github.com/robotology-playground/yarp-matlab-bindings/pull/35), and along with this, the issue on `vectors_fromTo_matlab.i` path will be fixed.



> There is no SWIGMATLAB macro listed in the SWIG docs. How does it actually get defined?

this flag is defined directly in the Mex library source file `yarp-matlab-bindings/matlab/autogenerated/yarpMATLAB_wrap.cxx` generated by SWIG.

**Comment by traversaro** [comment]
The issue mentioned by @PeterBowman is blocking https://github.com/robotology-playground/yarp-matlab-bindings/pull/35 .

**Pull request merged**
