### PR TITLE
Remove deprecated yarpserver2 and yarpserver3 tools

### PR DESCRIPTION
**Pull request by drdanz**
* Remove yarpserver2 and yarpserver3
* Remove deprecated YARP_USE_PERSISTENT_NAMESERVER option, now mandatory
* ~~Make YARP_name a static library~~
* ~~Do not export YARP_HAS_NAME_LIB~~

This will require some changes to icub-main (iCubCluster) and possibly on the iCubCluster config for some robots.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/780%23issuecomment-222680084%22%2C%20%22https%3A//github.com/robotology/yarp/pull/780%23issuecomment-224922990%22%2C%20%22https%3A//github.com/robotology/yarp/pull/780%23issuecomment-224923470%22%2C%20%22https%3A//github.com/robotology/yarp/pull/780%23issuecomment-224930410%22%2C%20%22https%3A//github.com/robotology/yarp/pull/780%23issuecomment-224930759%22%2C%20%22https%3A//github.com/robotology/yarp/pull/780%23issuecomment-224939174%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/780%23issuecomment-222680084%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Appveyor%20is%20not%20happy%20with%20something%20in%20the%20linking%2C%20probably%20related%20to%20the%20%5C%22Make%20YARP_name%20a%20static%20library%5C%22%20part%22%2C%20%22created_at%22%3A%20%222016-05-31T12%3A57%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22Apparently%20YARP_name%20as%20a%20static%20library%20is%20causing%20some%20issues%20on%20windows.%20At%20the%20moment%20I%20don%27t%20have%20a%20windows%20machine%20for%20testing%20and%20I%20cannot%20get%20it%20to%20work%20on%20appveyor%20therefore%20I%20reverted%20these%20changes%3A%5Cr%5Cn%5Cr%5Cn%2A%20Make%20YARP_name%20a%20static%20library%5Cr%5Cn%2A%20Do%20not%20export%20YARP_HAS_NAME_LIB%22%2C%20%22created_at%22%3A%20%222016-06-09T15%3A01%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-06-09T15%3A02%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40drdanz%20just%20to%20let%20you%20know%20that%20I%20didn%27t%20experience%20any%20particular%20problem%20compiling%20%60yarp/devel%60%20on%20my%20Windows%22%2C%20%22created_at%22%3A%20%222016-06-09T15%3A23%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Ok%20sorry%20I%27ve%20overlooked%20that%27s%20a%20PR...%22%2C%20%22created_at%22%3A%20%222016-06-09T15%3A24%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Still%20not%20building%20on%20appveyor%20%3A-1%3A%5Cr%5CnI%20will%20need%20a%20computer%20to%20test%20it...%22%2C%20%22created_at%22%3A%20%222016-06-09T15%3A52%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/780#issuecomment-222680084'>General Comment</a></b>
- <a href='https://github.com/drdanz'></a> Appveyor is not happy with something in the linking, probably related to the "Make YARP_name a static library" part
- <a href='https://github.com/drdanz'></a> Apparently YARP_name as a static library is causing some issues on windows. At the moment I don't have a windows machine for testing and I cannot get it to work on appveyor therefore I reverted these changes:
* Make YARP_name a static library
* Do not export YARP_HAS_NAME_LIB
- <a href='https://github.com/drdanz'></a> :+1:
- <a href='https://github.com/pattacini'></a> @drdanz just to let you know that I didn't experience any particular problem compiling `yarp/devel` on my Windows
- <a href='https://github.com/pattacini'></a> Ok sorry I've overlooked that's a PR...
- <a href='https://github.com/drdanz'></a> Still not building on appveyor :-1:
I will need a computer to test it...

<a href='https://www.codereviewhub.com/robotology/yarp/pull/780?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/780?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/780'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/780'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by drdanz** [comment]
Appveyor is not happy with something in the linking, probably related to the "Make YARP_name a static library" part

**Comment by drdanz** [comment]
Apparently YARP_name as a static library is causing some issues on windows. At the moment I don't have a windows machine for testing and I cannot get it to work on appveyor therefore I reverted these changes:

* Make YARP_name a static library
* Do not export YARP_HAS_NAME_LIB

**Comment by drdanz** [comment]
:+1:

**Comment by pattacini** [comment]
@drdanz just to let you know that I didn't experience any particular problem compiling `yarp/devel` on my Windows

**Comment by pattacini** [comment]
Ok sorry I've overlooked that's a PR...

**Comment by drdanz** [comment]
Still not building on appveyor :-1:
I will need a computer to test it...

**Pull request merged**
