### PR TITLE
Specify a different name for the node name and the yarprun server name in the yarpmanager

### PR DESCRIPTION
**Pull request by S-Dafarra**
Fix https://github.com/robotology/yarp/issues/1893

Maybe also the graphic should be modified, adding a column with the address. It would be even better if it could be modified from the GUI, but I don't really know what to touch.

### CODE REVIEW

**Comment by S-Dafarra** [comment]
Following the suggestion of @Nicogene I also modified the widget which looks like the following:
image
The fields are not editable. This probably requires some more modifications to avoid editing when the ``yarprun`` is already running.

**Comment by drdanz** [comment]
is this backwards compatible?

**Comment by S-Dafarra** [comment]
If no address is specified, it takes the name as address (see for example the ``pc104`` line in the image above and line https://github.com/robotology/yarp/pull/1894/files#diff-f3936ba50445105e6e7e5a0f8e5fc82eR141) which should correspond to the original behavior.

**Comment by S-Dafarra** [comment]
> If you successfully tested it on a real iCub cluster

Currently @hu-yue and @GiulioRomualdi are using it in the greeny cluster.

> The same thing could be also for the other entries, so if we want to make them editables (and the changes written to `cluster-config.xml`) I think we should do it in a separate PR.

Agreed.

> Only a side note, please rebase and add a line in the changelog

Done

**Comment by Nicogene** [comment]
Merged, thanks!

**Pull request merged**
