### PR TITLE
 Improve MultipleAnalogSensorInterfaces docs 

### PR DESCRIPTION
**Pull request by traversaro**
Furthermore, fix https://github.com/robotology/yarp/issues/1666 .

### CODE REVIEW

**Comment by Nicogene** [comment]
Merged, thanks!

**Comment by drdanz** [comment]
This PR broke the documentation generation...

```
Generating bitmaps for formulas in HTML...
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./_formulas.tex
LaTeX2e <2018-04-01> patch level 2
Babel <3.18> and hyphenation patterns for 3 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/graphics/epsfig.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/dvips.def))))
No file _formulas.aux.
[1]

! LaTeX Error: Environment bmatrix undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.8 \[ RotZ(\theta) = \begin{bmatrix}
                                      \cos(\theta) & -\sin(\theta) & 0 \\ \s...
```
? S
```
OK, entering \scrollmode...
! Misplaced alignment tab character &.
l.8 ...gin{bmatrix} \cos(\theta) & -\sin(\theta) &
                                                   0 \\ \sin(\theta) & \cos(...

! Misplaced alignment tab character &.
l.8 ...heta) & -\sin(\theta) & 0 \\ \sin(\theta) &
                                                   \cos(\theta) & 0 \\ 0 & 0...

! Misplaced alignment tab character &.
l.8 ...theta) & 0 \\ \sin(\theta) & \cos(\theta) &
                                                   0 \\ 0 & 0 & 1 \\ \end{bm...

! Misplaced alignment tab character &.
l.8 ...0 \\ \sin(\theta) & \cos(\theta) & 0 \\ 0 &
                                                   0 & 1 \\ \end{bmatrix} , \]
! Misplaced alignment tab character &.
l.8 ... \sin(\theta) & \cos(\theta) & 0 \\ 0 & 0 &
                                                   1 \\ \end{bmatrix} , \]
! Missing \endgroup inserted.
<inserted text> 
                \endgroup 
l.8 ...eta) & 0 \\ 0 & 0 & 1 \\ \end{bmatrix} , \]
                                                  

Overfull \hbox (972.73355pt too wide) detected at line 8
\OML/cmm/m/it/10 RotZ\OT1/cmr/m/n/10 (\OML/cmm/m/it/10 ^^R\OT1/cmr/m/n/10 ) =)0
\OMS/cmsy/m/n/10 nn []\OT1/cmr/m/n/10 (\OML/cmm/m/it/10 ^^R\OT1/cmr/m/n/10 ) []
(\OML/cmm/m/it/10 ^^R\OT1/cmr/m/n/10 )0\OMS/cmsy/m/n/10 nn\OT1/cmr/m/n/10 001\O
MS/cmsy/m/n/10 nnn\OML/cmm/m/it/10 GenericError[][][][];
[2]

! LaTeX Error: Environment bmatrix undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.11 \[ RotY(\theta) = \begin{bmatrix}
                                       \cos(\theta) & 0 & \sin(\theta) \\ 0 ...

! Misplaced alignment tab character &.
l.11 ...Y(\theta) = \begin{bmatrix} \cos(\theta) &
                                                   0 & \sin(\theta) \\ 0 & 1...

! Misplaced alignment tab character &.
l.11 ...heta) = \begin{bmatrix} \cos(\theta) & 0 &
                                                   \sin(\theta) \\ 0 & 1 & 0...

! Misplaced alignment tab character &.
l.11 ...ix} \cos(\theta) & 0 & \sin(\theta) \\ 0 &
                                                   1 & 0 \\ -\sin(\theta) & ...

! Misplaced alignment tab character &.
l.11 ...\cos(\theta) & 0 & \sin(\theta) \\ 0 & 1 &
                                                   0 \\ -\sin(\theta) & 0 & ...

! Misplaced alignment tab character &.
l.11 ...in(\theta) \\ 0 & 1 & 0 \\ -\sin(\theta) &
                                                   0 & \cos(\theta) \\ \end{...

! Misplaced alignment tab character &.
l.11 ...theta) \\ 0 & 1 & 0 \\ -\sin(\theta) & 0 &
                                                   \cos(\theta) \\ \end{bmat...


! LaTeX Error: \begin{document} ended by \end{bmatrix}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.11 ...theta) & 0 & \cos(\theta) \\ \end{bmatrix}
                                                   \]
[3]

! LaTeX Error: Environment bmatrix undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.14 \[ RotX(\theta) = \begin{bmatrix}
                                       1 & 0 & 0 \\ 0 & \cos(\theta) & - \si...

! Misplaced alignment tab character &.
l.14 \[ RotX(\theta) = \begin{bmatrix} 1 &
                                           0 & 0 \\ 0 & \cos(\theta) & - \si...

! Misplaced alignment tab character &.
l.14 \[ RotX(\theta) = \begin{bmatrix} 1 & 0 &
                                               0 \\ 0 & \cos(\theta) & - \si...

! Misplaced alignment tab character &.
l.14 ...\theta) = \begin{bmatrix} 1 & 0 & 0 \\ 0 &
                                                   \cos(\theta) & - \sin(\th...

! Misplaced alignment tab character &.
l.14 ...n{bmatrix} 1 & 0 & 0 \\ 0 & \cos(\theta) &
                                                   - \sin(\theta) \\ 0 & \si...

! Misplaced alignment tab character &.
l.14 ...\ 0 & \cos(\theta) & - \sin(\theta) \\ 0 &
                                                   \sin(\theta) & \cos(\thet...

! Misplaced alignment tab character &.
l.14 ...ta) & - \sin(\theta) \\ 0 & \sin(\theta) &
                                                   \cos(\theta) \\ \end{bmat...


! LaTeX Error: \begin{document} ended by \end{bmatrix}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.14 ...in(\theta) & \cos(\theta) \\ \end{bmatrix}
                                                   \]
[4]
! Undefined control sequence.
l.17 $\hspace{1em} {}^f R_s \in \mathbb
                                       {R}^{3 \times 3} $
[5] (./_formulas.aux) )
```

**Comment by Nicogene** [comment]
I think that the problem is here:
```
 *
    * If \f$ f \f$ is the lab or surface fixed frame, and \f$ s \f$ is the sensor-fixed
    * frame, this methods returns the angles \f$ r \in [-180, 180] , p \in [-90, 90], y \in [-180, 180]\f$
    * such that
    * \f[
    * {}^f R_s = RotZ\left(\frac{\pi}{180}y\right)*RotY\left(\frac{\pi}{180}p\right)*RotX\left(\frac{\pi}{180}r\right)
    * \f]
    * with
    * \f[
    * RotZ(\theta)
    *  =
    *  \begin{bmatrix}
    *      \cos(\theta)      & -\sin(\theta) & 0              \\
    *      \sin(\theta)      & \cos(\theta)  & 0              \\
    *      0                 & 0             & 1              \\
    *  \end{bmatrix}
    * ,
    * \f]
    * \f[
    * RotY(\theta)
    * =
    *  \begin{bmatrix}
    *      \cos(\theta)      & 0             & \sin(\theta)   \\
    *      0                 & 1             & 0              \\
    *      -\sin(\theta)     & 0             & \cos(\theta)   \\
    *  \end{bmatrix}
    *
    * \f]
    * and
    * \f[
    * RotX(\theta)
    * =
    *  \begin{bmatrix}
    *      1 & 0             & 0              \\
    *      0 & \cos(\theta)  & - \sin(\theta) \\
    *      0 & \sin(\theta)  & \cos(\theta)   \\
    *  \end{bmatrix}
    * \f]
    * where \f$\hspace{1em} {}^f R_s \in \mathbb{R}^{3 \times 3} \f$ is the rotation that left-multiplied by a 3d column vector
    * expressed in \f$ s \f$ it returns it expressed in \f$ f \f$ .
``

**Comment by drdanz** [comment]
Fixed

**Comment by traversaro** [comment]
Thanks, for local check I actually used MathJax .

**Pull request merged**
