### PR TITLE
Pwm and current control

### PR DESCRIPTION
**Pull request by randaz81**
[WIP]
two new interfaces and control modes: iPWMControl and iCurrentControl
see the comments from the individual commits

### CODE REVIEW

**Comment by traversaro** [comment]
Hi @S-Dafarra and @nunoguedelha , if you have time can you check the new interfaces `ICurrentControl` in the `ICurrentControl.h` file and `IPWMControl` in the `IPWDControl.h` file? Clearly this interfaces are critical for joint friction estimation. 

cc @DanielePucci

**Comment by randaz81** [comment]
Do not delete branch before tests completion.

**Comment by nunoguedelha** [comment]
@traversaro @randaz81  , I would have a couple of questions regarding the current/PWM interfaces:

1) I see an ICurrentControl interface with methods for setting the PID parameters. What about the PI parameters of the control loop on the torque?
2) Has there been any change in the torque low level control loop, like introducing the current measurement in the loop?
3) since `getDutyCycle` returns the PWM actually applied as an input to the motor, what role plays the RefDutyCycle returned by `getRefDutyCycle`?
4) if the loop is closed on the desired torque at some point, how do we set the reference torque in the updated interfaces?

In general I don't see how to match the updated interface with the low level control loop model presented by Dani. Is there any documentation/diagrams explaning the low torque control loop?

**Comment by traversaro** [comment]
> I see an ICurrentControl interface with methods for setting the PID parameters. What about the PI parameters of the control loop on the torque?

On ETH iCub robots, the Torque Control (running on EMS boards) output is fed as input to the Current Control loop, that is running on 2FOC boards. The output of the Current Control is then given actually the PWM sent to the motors. These methods set the parameters of the Current Control. 

> Has there been any change in the torque low level control loop, like introducing the current measurement in the loop?

Not recently, the current control loop is running on the ETH robot since the beginning.  

> since `getDutyCycle` returns the PWM actually applied as an input to the motor, what role plays the RefDutyCycle returned by `getRefDutyCycle`?

I think in all the implementations they should always be the same but they are there for consistency, but @randaz81 probably can give a more informed answer. 

> if the loop is closed on the desired torque at some point, how do we set the reference torque in the updated interfaces?

The reference torque was and is still set using the methods of the `ITorqueControl` interface. 

> In general I don't see how to match the updated interface with the low level control loop model presented by Dani. Is there any documentation/diagrams explaning the low torque control loop?

We wrote something on a GitHub issue/repo when we debugged the torque control on the ETH robots, but I can't find it. : ( 
In general, I think that Dani always presented just about the torque control loop, while this methods are related either to the Current Control or to setting directly the Motor Voltage.

**Pull request merged**
