### PR TITLE
Export as public symbols IWrapper, IMultipleWrapper and other widely used interfaces

### PR DESCRIPTION
**Pull request by traversaro**
Solves the issue in https://github.com/robotology/gazebo-yarp-plugins/issues/254
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232632795%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232636584%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232649137%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232662091%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232664695%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232665181%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232923659%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-233296203%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-233297447%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-233297944%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-233298338%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232632795%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Notice%20that%20unfortunately%20the%20test%20is%20not%20effective%20in%20highlighting%20the%20issue%20for%20two%20reasons%3A%20%5Cr%5Cn%20%2A%20There%20are%20no%20Travis%20jobs%20covering%20the%20%60YARP_CLEAN_API%60%20option%2C%20%5Cr%5Cn%20%2A%20And%20the%20option%20is%20ignored%20if%20the%20tests%20are%20build%20%28see%20https%3A//github.com/robotology/yarp/blob/31766f34f115fa77826dae3fc8e2686688fd7aef/conf/YarpOptions.cmake%23L226%29.%20%5Cr%5Cn%5Cr%5CnFor%20these%20reasons%20I%20disabled%20that%20option%20from%20being%20used%20in%20the%20superbuild%20%28%20https%3A//github.com/robotology/codyco-superbuild/commit/daa6958b42a0dd8c27995ca98afbd4108f591cbe%20%29.%20%22%2C%20%22created_at%22%3A%20%222016-07-14T10%3A57%3A37Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%20%40traversaro%20this%20PR%20is%20out%20of%20date%20with%20%60master%60.%20I%20think%20the%20current%20policy%20forces%20to%20rebase%20the%20PR%20on%20top%20of%20%60master%60...%22%2C%20%22created_at%22%3A%20%222016-07-14T11%3A15%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks%2C%20rebased.%20%22%2C%20%22created_at%22%3A%20%222016-07-14T12%3A16%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27m%20afraid%20you%20ought%20to%20rebase%20it%20again...%20given%20that%20a%20new%20PR%20has%20been%20merged%20into%20%60master%60%20right%20now.%22%2C%20%22created_at%22%3A%20%222016-07-14T13%3A16%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks%2C%20rebased%20again.%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-07-14T13%3A26%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20wish%20this%20feature%20https%3A//github.com/isaacs/github/issues/88%20was%20actually%20implemented%20by%20GitHub.%20%22%2C%20%22created_at%22%3A%20%222016-07-14T13%3A28%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40drdanz%20Let%20me%20know%20when%20you%20plan%20to%20merge%20this%20PR%2C%20I%20saw%20new%20commit%20on%20master%20but%20at%20this%20point%20it%20is%20easier%20to%20just%20rebase%20once%20before%20merging.%20%22%2C%20%22created_at%22%3A%20%222016-07-15T11%3A04%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40traversaro%20sorry%2C%20I%20didn%27t%20notice%20you%20removed%20the%20%60%5BWIP%5D%60%20from%20the%20title%5Cr%5CnThe%20patch%20looks%20good%2C%20please%20rebase%20over%20the%20latest%20master%20and%20I%27ll%20merge%20it%20%28ping%20me%20when%20you%20are%20ready%29%22%2C%20%22created_at%22%3A%20%222016-07-18T10%3A37%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40drdanz%20done.%20%22%2C%20%22created_at%22%3A%20%222016-07-18T10%3A45%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40drdanz%20actually%20apparently%20I%20lost%20a%20commit%2C%20redoing%20it.%20%22%2C%20%22created_at%22%3A%20%222016-07-18T10%3A48%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22Done.%22%2C%20%22created_at%22%3A%20%222016-07-18T10%3A50%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/824#issuecomment-232632795'>General Comment</a></b>
- <a href='https://github.com/traversaro'></a> Notice that unfortunately the test is not effective in highlighting the issue for two reasons:
* There are no Travis jobs covering the `YARP_CLEAN_API` option,
* And the option is ignored if the tests are build (see https://github.com/robotology/yarp/blob/31766f34f115fa77826dae3fc8e2686688fd7aef/conf/YarpOptions.cmake#L226).
For these reasons I disabled that option from being used in the superbuild ( https://github.com/robotology/codyco-superbuild/commit/daa6958b42a0dd8c27995ca98afbd4108f591cbe ).
- <a href='https://github.com/pattacini'></a> Hi @traversaro this PR is out of date with `master`. I think the current policy forces to rebase the PR on top of `master`...
- <a href='https://github.com/traversaro'></a> Thanks, rebased.
- <a href='https://github.com/pattacini'></a> I'm afraid you ought to rebase it again... given that a new PR has been merged into `master` right now.
- <a href='https://github.com/traversaro'></a> Thanks, rebased again.
- <a href='https://github.com/traversaro'></a> I wish this feature https://github.com/isaacs/github/issues/88 was actually implemented by GitHub.
- <a href='https://github.com/traversaro'></a> @drdanz Let me know when you plan to merge this PR, I saw new commit on master but at this point it is easier to just rebase once before merging.
- <a href='https://github.com/drdanz'></a> @traversaro sorry, I didn't notice you removed the `[WIP]` from the title
The patch looks good, please rebase over the latest master and I'll merge it (ping me when you are ready)
- <a href='https://github.com/traversaro'></a> @drdanz done.
- <a href='https://github.com/traversaro'></a> @drdanz actually apparently I lost a commit, redoing it.
- <a href='https://github.com/traversaro'></a> Done.

<a href='https://www.codereviewhub.com/robotology/yarp/pull/824?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/824?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/824'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/824'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by traversaro** [comment]
Notice that unfortunately the test is not effective in highlighting the issue for two reasons: 
 * There are no Travis jobs covering the `YARP_CLEAN_API` option, 
 * And the option is ignored if the tests are build (see https://github.com/robotology/yarp/blob/31766f34f115fa77826dae3fc8e2686688fd7aef/conf/YarpOptions.cmake#L226). 

For these reasons I disabled that option from being used in the superbuild ( https://github.com/robotology/codyco-superbuild/commit/daa6958b42a0dd8c27995ca98afbd4108f591cbe ).

**Comment by pattacini** [comment]
Hi @traversaro this PR is out of date with `master`. I think the current policy forces to rebase the PR on top of `master`...

**Comment by traversaro** [comment]
Thanks, rebased.

**Comment by pattacini** [comment]
I'm afraid you ought to rebase it again... given that a new PR has been merged into `master` right now.

**Comment by traversaro** [comment]
Thanks, rebased again.

**Comment by traversaro** [comment]
I wish this feature https://github.com/isaacs/github/issues/88 was actually implemented by GitHub.

**Comment by traversaro** [comment]
@drdanz Let me know when you plan to merge this PR, I saw new commit on master but at this point it is easier to just rebase once before merging.

**Comment by drdanz** [comment]
@traversaro sorry, I didn't notice you removed the `[WIP]` from the title
The patch looks good, please rebase over the latest master and I'll merge it (ping me when you are ready)

**Comment by traversaro** [comment]
@drdanz done.

**Comment by traversaro** [comment]
@drdanz actually apparently I lost a commit, redoing it.

**Comment by traversaro** [comment]
Done.

**Comment by drdanz** [comment]
Merged, thanks

**Pull request merged**
