### PR TITLE
Fix a couple of typos

### PR DESCRIPTION
**Pull request by drdanz**
#### `IntrinsicParams`

* Deprecate `YARP_PLUM_BOB` in favour of `YARP_PLUMB_BOB`

#### `IDepthVisualParams`

* The `retificationMatrix` parameter was renamed `rectificationMatrix`

#### `IRgbVisualParams`

* The `retificationMatrix` parameter was renamed `rectificationMatrix`

### CODE REVIEW

**Comment by drdanz** [comment]
CC @triccyx

**Review by Nicogene — APPROVED** [review]
Ok for me, we should coordinate with external repositories such as `yarp-device-realsense2` for `YARP_PLUMB_BOB` changes (https://github.com/robotology/yarp-device-realsense2/search?q=YARP_PLUM_BOB). Shall we increase the patch number here and put it required in yarp-device-realsense2?

**Comment by traversaro** [comment]
> `YARP_PLUMB_BOB`

I guess the deprecation as done now should work fine.

**Review by traversaro — APPROVED** [review]

**Comment by drdanz** [comment]
The deprecation will print a warning when used, the breaking change is the "retificationMatrix" -> "rectificationMatrix" string, which seems to be used in yarp-device-ultrapython (cc @triccyx), gazebo-yarp-plugins (cc @traversaro) and icub-main (firewire camera) (cc @Nicogene @pattacini).
I don't think that anyone is actually using it, this is just a parameter set by the cameras.

**Pull request merged**
