### PR TITLE
Allow passing a list of external devices when using the yarprobotinterface as a library

### PR DESCRIPTION
**Pull request by diegoferigo**
This PR finalizes the refactoring of the yarprobotinterface from an executable to a library as described in https://github.com/robotology/yarp/issues/2005. The previous related PRs are https://github.com/robotology/yarp/pull/2168 and  https://github.com/robotology/yarp/pull/2288.

- e586238 Only real commit
- ccc660f Applied YARP's clang-format to all the yarprobotinterface module (I can split this in another PR if needed)

This PR targets specifically the usage of `libYARP_robotinterface` as a library, modifying the method `Robot::enterPhase` to accept an optional list of external devices. For each phase, is up to the user whether to pass or not pass the list of external devices. The only relevant phase where this can be useful is the `ActionPhaseStartup`. In fact, if the user passes an external list of devices and names match:

1. if a device already exists in the list of external devices, the internal device does not get started (the external device is opened if it was not)
1. if the same device has also to be attached to another internal device, the external device is selected with higher priority
 
Note that this logic does not break the detach phase. In fact, in the detach phase all the devices can perform pre-detach operations since they still have a pointer to the device-to-detach, and detaching means only releasing the pointer (they don't own its memory, so no deallocation should happen). This fact allows avoiding to pass again the same list of external devices when `ActionPhaseShutdown` is triggered.

I'm not very familiar with the `ActionTypeCalibrate` and `ActionTypePark`, if while reviewing the code you realize that something is missing there, let me know. We can either update this PR or address the problem in a future one. These changes for sure will not break the APIs.

A caveat of this PR is that, after `ActionPhaseStartup` is called and the start of the internal device is prevented due to the presence of an external device, its corresponding `robotinterface::Device` internal object still exists. It will contain an allocated but not started `PolyDriver`. I didn't like the idea to replace it with the corresponding external device since otherwise its memory would be owned by two different `robotinterface::Robot` objects, leading probably to double frees. Should it be deleted, instead? If it's not a problem, I propose to try to get merged this PR as it is so that it can target the next YARP release (and this library is anyway experimental), and keep the discussion of this caveat in https://github.com/robotology/yarp/issues/2005.

cc @drdanz @traversaro

### CODE REVIEW

**Comment by diegoferigo** [comment]
This could be unrelated to the valgrind failures, but I'm a bit concerned by the behaviour of:

https://github.com/robotology/yarp/blob/bb16484dbf26026906ef7b7b44169ca15dca201b/src/libYARP_robotinterface/src/yarp/robotinterface/Device.cpp#L218

Right now `typedef std::vector<robotinterface::Device> DeviceList;`, so the devices are copied and not taken as references. Maybe introducing a new `using DeviceRefsList = std::vector<robotinterface::Device&>` would be more appropriate.

**Comment by traversaro** [comment]
> In fact, if the user passes an external list of devices and names match:
> 
>     1. if a device already exists in the list of external devices, the internal device does not get started (the external device is opened if it was not)
> 
>     2. if the same device has also to be attached to another internal device, the external device is selected with higher priority

Just to understand, do you have a use case for this case  of "names conflict between internal and external devices"? If there is no specific need for it, I think it may be useful to just fail in a clear way in case there is a name conflict, to avoid  creating subtle behaviors that are difficult to debug and understand to the user.

**Comment by drdanz** [comment]
Valgrind builds are failing with this error:

```
[INFO] startup phase starting...

[INFO] created device <robotinterface_test_mock_device>. See C++ class RobotInterfaceTestMockDriver for documentation.

[INFO] created device <robotinterface_test_mock_wrapper>. See C++ class RobotInterfaceTestMockWrapper for documentation.

[INFO] Entering action level 5 of phase startup

==23796== Invalid read of size 8

==23796==    at 0x4E68DBC: yarp::robotinterface::Device::driver() const (src/libYARP_robotinterface/src/yarp/robotinterface/Device.cpp:351)

==23796==    by 0x4E70342: yarp::robotinterface::Robot::Private::attach(yarp::robotinterface::Device const&, std::vector<yarp::robotinterface::Param, std::allocator<yarp::robotinterface::Param> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:325)

==23796==    by 0x4E72656: yarp::robotinterface::Robot::enterPhase(yarp::robotinterface::ActionPhase, std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:623)

==23796==    by 0x1642EC: ____C_A_T_C_H____T_E_S_T____3() (tests/libYARP_robotinterface/RobotinterfaceTest.cpp:214)

==23796==    by 0x17D727: Catch::TestInvokerAsFunction::invoke() const (extern/catch2/catch.hpp:12209)

==23796==    by 0x17CD98: Catch::TestCase::invoke() const (extern/catch2/catch.hpp:12107)

==23796==    by 0x1774BF: Catch::RunContext::invokeActiveTestCase() (extern/catch2/catch.hpp:10937)

==23796==    by 0x177212: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (extern/catch2/catch.hpp:10910)

==23796==    by 0x175C5D: Catch::RunContext::runTest(Catch::TestCase const&) (extern/catch2/catch.hpp:10680)

==23796==    by 0x1789D0: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (extern/catch2/catch.hpp:11242)

==23796==    by 0x179DC1: Catch::Session::runInternal() (extern/catch2/catch.hpp:11440)

==23796==    by 0x179B4A: Catch::Session::run() (extern/catch2/catch.hpp:11397)

==23796==  Address 0x8ce84a8 is 8 bytes inside a block of size 32 free'd

==23796==    at 0x4C3123B: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)

==23796==    by 0x167149: __gnu_cxx::new_allocator<yarp::robotinterface::Device>::deallocate(yarp::robotinterface::Device*, unsigned long) (/usr/include/c++/8/ext/new_allocator.h:125)

==23796==    by 0x1670D3: std::allocator_traits<std::allocator<yarp::robotinterface::Device> >::deallocate(std::allocator<yarp::robotinterface::Device>&, yarp::robotinterface::Device*, unsigned long) (/usr/include/c++/8/bits/alloc_traits.h:462)

==23796==    by 0x167015: std::_Vector_base<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> >::_M_deallocate(yarp::robotinterface::Device*, unsigned long) (/usr/include/c++/8/bits/stl_vector.h:304)

==23796==    by 0x166D3B: std::_Vector_base<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> >::~_Vector_base() (/usr/include/c++/8/bits/stl_vector.h:285)

==23796==    by 0x1665D6: std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> >::~vector() (/usr/include/c++/8/bits/stl_vector.h:570)

==23796==    by 0x4E6E927: yarp::robotinterface::Robot::Private::findDevice(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:143)

==23796==    by 0x4E7031A: yarp::robotinterface::Robot::Private::attach(yarp::robotinterface::Device const&, std::vector<yarp::robotinterface::Param, std::allocator<yarp::robotinterface::Param> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:322)

==23796==    by 0x4E72656: yarp::robotinterface::Robot::enterPhase(yarp::robotinterface::ActionPhase, std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:623)

==23796==    by 0x1642EC: ____C_A_T_C_H____T_E_S_T____3() (tests/libYARP_robotinterface/RobotinterfaceTest.cpp:214)

==23796==    by 0x17D727: Catch::TestInvokerAsFunction::invoke() const (extern/catch2/catch.hpp:12209)

==23796==    by 0x17CD98: Catch::TestCase::invoke() const (extern/catch2/catch.hpp:12107)

==23796==  Block was alloc'd at

==23796==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)

==23796==    by 0x4E79455: __gnu_cxx::new_allocator<yarp::robotinterface::Device>::allocate(unsigned long, void const*) (/usr/include/c++/8/ext/new_allocator.h:111)

==23796==    by 0x4E7836D: std::allocator_traits<std::allocator<yarp::robotinterface::Device> >::allocate(std::allocator<yarp::robotinterface::Device>&, unsigned long) (/usr/include/c++/8/bits/alloc_traits.h:436)

==23796==    by 0x4E76B23: std::_Vector_base<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> >::_M_allocate(unsigned long) (/usr/include/c++/8/bits/stl_vector.h:296)

==23796==    by 0x4E7525E: void std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> >::_M_realloc_insert<yarp::robotinterface::Device const&>(__gnu_cxx::__normal_iterator<yarp::robotinterface::Device*, std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> > >, yarp::robotinterface::Device const&) (/usr/include/c++/8/bits/vector.tcc:427)

==23796==    by 0x4E741BD: std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> >::push_back(yarp::robotinterface::Device const&) (/usr/include/c++/8/bits/stl_vector.h:1085)

==23796==    by 0x4E6E7DE: yarp::robotinterface::Robot::Private::allDevicesWithExternal() const (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:134)

==23796==    by 0x4E6E88A: yarp::robotinterface::Robot::Private::findDevice(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:143)

==23796==    by 0x4E7031A: yarp::robotinterface::Robot::Private::attach(yarp::robotinterface::Device const&, std::vector<yarp::robotinterface::Param, std::allocator<yarp::robotinterface::Param> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:322)

==23796==    by 0x4E72656: yarp::robotinterface::Robot::enterPhase(yarp::robotinterface::ActionPhase, std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:623)

==23796==    by 0x1642EC: ____C_A_T_C_H____T_E_S_T____3() (tests/libYARP_robotinterface/RobotinterfaceTest.cpp:214)

==23796==    by 0x17D727: Catch::TestInvokerAsFunction::invoke() const (extern/catch2/catch.hpp:12209)

==23796== 

==23796== Invalid read of size 8

==23796==    at 0x4E6A990: yarp::robotinterface::Device::Private::drv() const (src/libYARP_robotinterface/src/yarp/robotinterface/Device.cpp:81)

==23796==    by 0x4E68DC7: yarp::robotinterface::Device::driver() const (src/libYARP_robotinterface/src/yarp/robotinterface/Device.cpp:351)

==23796==    by 0x4E70342: yarp::robotinterface::Robot::Private::attach(yarp::robotinterface::Device const&, std::vector<yarp::robotinterface::Param, std::allocator<yarp::robotinterface::Param> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:325)

==23796==    by 0x4E72656: yarp::robotinterface::Robot::enterPhase(yarp::robotinterface::ActionPhase, std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:623)

==23796==    by 0x1642EC: ____C_A_T_C_H____T_E_S_T____3() (tests/libYARP_robotinterface/RobotinterfaceTest.cpp:214)

==23796==    by 0x17D727: Catch::TestInvokerAsFunction::invoke() const (extern/catch2/catch.hpp:12209)

==23796==    by 0x17CD98: Catch::TestCase::invoke() const (extern/catch2/catch.hpp:12107)

==23796==    by 0x1774BF: Catch::RunContext::invokeActiveTestCase() (extern/catch2/catch.hpp:10937)

==23796==    by 0x177212: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (extern/catch2/catch.hpp:10910)

==23796==    by 0x175C5D: Catch::RunContext::runTest(Catch::TestCase const&) (extern/catch2/catch.hpp:10680)

==23796==    by 0x1789D0: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (extern/catch2/catch.hpp:11242)

==23796==    by 0x179DC1: Catch::Session::runInternal() (extern/catch2/catch.hpp:11440)

==23796==  Address 0x8ce8b00 is 112 bytes inside a block of size 120 free'd

==23796==    at 0x4C3123B: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)

==23796==    by 0x4E68939: yarp::robotinterface::Device::~Device() (src/libYARP_robotinterface/src/yarp/robotinterface/Device.cpp:260)

==23796==    by 0x16716B: void std::_Destroy<yarp::robotinterface::Device>(yarp::robotinterface::Device*) (/usr/include/c++/8/bits/stl_construct.h:98)

==23796==    by 0x167112: void std::_Destroy_aux<false>::__destroy<yarp::robotinterface::Device*>(yarp::robotinterface::Device*, yarp::robotinterface::Device*) (/usr/include/c++/8/bits/stl_construct.h:108)

==23796==    by 0x16703B: void std::_Destroy<yarp::robotinterface::Device*>(yarp::robotinterface::Device*, yarp::robotinterface::Device*) (/usr/include/c++/8/bits/stl_construct.h:137)

==23796==    by 0x166D80: void std::_Destroy<yarp::robotinterface::Device*, yarp::robotinterface::Device>(yarp::robotinterface::Device*, yarp::robotinterface::Device*, std::allocator<yarp::robotinterface::Device>&) (/usr/include/c++/8/bits/stl_construct.h:206)

==23796==    by 0x1665CA: std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> >::~vector() (/usr/include/c++/8/bits/stl_vector.h:567)

==23796==    by 0x4E6E927: yarp::robotinterface::Robot::Private::findDevice(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:143)

==23796==    by 0x4E7031A: yarp::robotinterface::Robot::Private::attach(yarp::robotinterface::Device const&, std::vector<yarp::robotinterface::Param, std::allocator<yarp::robotinterface::Param> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:322)

==23796==    by 0x4E72656: yarp::robotinterface::Robot::enterPhase(yarp::robotinterface::ActionPhase, std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:623)

==23796==    by 0x1642EC: ____C_A_T_C_H____T_E_S_T____3() (tests/libYARP_robotinterface/RobotinterfaceTest.cpp:214)

==23796==    by 0x17D727: Catch::TestInvokerAsFunction::invoke() const (extern/catch2/catch.hpp:12209)

==23796==  Block was alloc'd at

==23796==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)

==23796==    by 0x4E68722: yarp::robotinterface::Device::Device(yarp::robotinterface::Device const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Device.cpp:232)

==23796==    by 0x4E7A5BB: void std::_Construct<yarp::robotinterface::Device, yarp::robotinterface::Device const&>(yarp::robotinterface::Device*, yarp::robotinterface::Device const&) (/usr/include/c++/8/bits/stl_construct.h:75)

==23796==    by 0x4E79DD6: yarp::robotinterface::Device* std::__uninitialized_copy<false>::__uninit_copy<yarp::robotinterface::Device const*, yarp::robotinterface::Device*>(yarp::robotinterface::Device const*, yarp::robotinterface::Device const*, yarp::robotinterface::Device*) (/usr/include/c++/8/bits/stl_uninitialized.h:83)

==23796==    by 0x4E78F3E: yarp::robotinterface::Device* std::uninitialized_copy<yarp::robotinterface::Device const*, yarp::robotinterface::Device*>(yarp::robotinterface::Device const*, yarp::robotinterface::Device const*, yarp::robotinterface::Device*) (/usr/include/c++/8/bits/stl_uninitialized.h:134)

==23796==    by 0x4E77D34: yarp::robotinterface::Device* std::__uninitialized_copy_a<yarp::robotinterface::Device const*, yarp::robotinterface::Device*, yarp::robotinterface::Device>(yarp::robotinterface::Device const*, yarp::robotinterface::Device const*, yarp::robotinterface::Device*, std::allocator<yarp::robotinterface::Device>&) (/usr/include/c++/8/bits/stl_uninitialized.h:289)

==23796==    by 0x4E76B79: yarp::robotinterface::Device* std::__uninitialized_move_if_noexcept_a<yarp::robotinterface::Device*, yarp::robotinterface::Device*, std::allocator<yarp::robotinterface::Device> >(yarp::robotinterface::Device*, yarp::robotinterface::Device*, yarp::robotinterface::Device*, std::allocator<yarp::robotinterface::Device>&) (/usr/include/c++/8/bits/stl_uninitialized.h:311)

==23796==    by 0x4E752D7: void std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> >::_M_realloc_insert<yarp::robotinterface::Device const&>(__gnu_cxx::__normal_iterator<yarp::robotinterface::Device*, std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> > >, yarp::robotinterface::Device const&) (/usr/include/c++/8/bits/vector.tcc:447)

==23796==    by 0x4E741BD: std::vector<yarp::robotinterface::Device, std::allocator<yarp::robotinterface::Device> >::push_back(yarp::robotinterface::Device const&) (/usr/include/c++/8/bits/stl_vector.h:1085)

==23796==    by 0x4E6E7DE: yarp::robotinterface::Robot::Private::allDevicesWithExternal() const (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:134)

==23796==    by 0x4E6E88A: yarp::robotinterface::Robot::Private::findDevice(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:143)

==23796==    by 0x4E7031A: yarp::robotinterface::Robot::Private::attach(yarp::robotinterface::Device const&, std::vector<yarp::robotinterface::Param, std::allocator<yarp::robotinterface::Param> > const&) (src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp:322)

==23796== 

[INFO] All actions for action level 5 of startup phase started. Waiting for unfinished actions.

[INFO] All actions for action level 5 of startup phase finished.

[INFO] startup phase finished.
```

**Comment by diegoferigo** [comment]
Due to how objects copy of yarprobotinterfaces classes are handled, I had to resort to raw pointer for passing devices of a Robot object to another without encountering problems. It is not a solution I like (in general, all raw pointers from my point of view should be banned :smile:) but without a refactoring of the classes with modern memory management techniques, it is the quickest workaround.

Anyhow, I found a strange behaviour:

- load a first xml with a `remotecontrolboardremapper`
- load a second xml with:
  - many devices
  - another `remotecontrolboardremapper`
  - a device that attaches to the `remotecontrolboardremapper`

While loading the second xml, the fist list of devices (only containing a pointer to the first rcbr) is passed, and the second one is correctly not started. However, when the last devices that performs the attach is started, I see that the ports of the external rcbr get closed. This happens also when I comment out the attach phase xml section. I'm not yet sure if the problem is in the YARP side, or downstream in the device code.

I wanted this feature in for a downstream project I'm developing but due to a deadline I can no longer dedicate enough time to debug and polish this PR. I already spent few days for it and I have to move on with other tasks. I switched it back to draft and I will resume it the first week of August.

**Comment by traversaro** [comment]
> 
> 
> > In fact, if the user passes an external list of devices and names match:
> > ```
> > 1. if a device already exists in the list of external devices, the internal device does not get started (the external device is opened if it was not)
> > 
> > 2. if the same device has also to be attached to another internal device, the external device is selected with higher priority
> > ```
> 
> Just to understand, do you have a use case for this case of "names conflict between internal and external devices"? If there is no specific need for it, I think it may be useful to just fail in a clear way in case there is a name conflict, to avoid creating subtle behaviors that are difficult to debug and understand to the user.

Hi @diegoferigo, I will be happy to complete the work on this PR, but I am afraid I need an answer on the question quoted in this message to proceed.

**Comment by diegoferigo** [comment]
> Just to understand, do you have a use case for this case of "names conflict between internal and external devices"? If there is no specific need for it, I think it may be useful to just fail in a clear way in case there is a name conflict, to avoid creating subtle behaviors that are difficult to debug and understand to the user.

I want to recap the different stages before providing a reply.

1. A first `robotinterface::Robot` object is created from xml1 with
   - deviceA
   - deviceB that also attaches to deviceA
1. A second `robotinterface::Robot` object is created from xml2 with
   - deviceA
   - deviceC that also attaches to deviceA

Let's assume that the first `Robot` is up and running, i.e. deviceA and deviceB are running.

After creating the second `Robot` object, I want to pass as external devices to it `ActionPhaseStartup` the devices of xml1, so that the following three operations are performed:

1. deviceA is found in the list of external devices, so the internal one does not get started
1. deviceC is not found in the list of external devices, so it is started
1. deviceC has to attach with deviceA. Since deviceA is part of the external devices, deviceC gets attached to that.

With this being said, in this moment the second `Robot` object detects that deviceA is part of the passed list of external devices only by checking its name [1]. This is what you mention as "name conflict". It is actually not a conflict, it's the logic that prevents the start of the internal device in lieu of the external one. I hope I clarified what I originally meant.

[1] Be careful that this simple logic can introduce a caveat. The name of the device is not enough to be sure that the two devices are actually the same. In fact, the two devices with the same name could have different parameters. We still do not check that, I think that comparison operator are not overloaded for the object that stores the properties inside a `Device`. It's not a problem for me if we proceed with this PR anyway, just let's keep in mind that this could cause problem if forgotten.

**Comment by traversaro** [comment]
But can't you simple remove `deviceA` from `xml2`? In this way everything is more clear to the user, that is explicitly passing a xml that is only containing the devices that are actually opened by the robotinterface, and gets a clear error if `deviceA` is not found in the `xml1`, otherwise as soon as `deviceA` name is changed in `xml1` to `deviceAnew`, loading the `xml2` will now (silently) start the device `deviceA`.

**Comment by diegoferigo** [comment]
Yes, this is the caveat I described in the first post. Deleting deviceA from xml2 looks good to me.

> otherwise as soon as deviceA name is changed in xml1 to deviceAnew, loading the xml2 will now (silently) start the device deviceA

Well, in this situation since there would be no name that matches, even with the delete logic you proposed both devices would be started, right?

I would extend the logging system in any case to avoid silent operations. In the case the user decides to pass the external list of devices, there should be a logging output that informs any operation that involves the external devices. It would be nice having a DEBUG that lists all the devices with internal / external (or attached to external). I have something similar active right now even if not committed. I think it's useful having a similar recap also in this PR:

Screenshot_20200710_192114

**Comment by traversaro** [comment]
>Yes, this is the caveat I described in the first post. Deleting deviceA from xml2 looks good to me.

Sorry, I was  not clear. I meant that as far as I can see, we already prepare `xml2` without `deviceA` in the first place (like manually deleting from the `xml2` file), but probably I am missing something of what you are proposing.

**Comment by diegoferigo** [comment]
Ow ok if you delete the device from the xml file, that's ok. 

I was proposing a workaround that could avoid that. Often using the existing full xmls could be less error prone, and together with a clear output I think is a sound use-case. And what I mean is having the same xml for both cases: 1) loading it through yarprobotinterface as standalone, and 2) loading it with the logic of this PR having already an existing `Robot` object with some devices open.

For the moment, requiring to prepare properly the xmls looks a good option. It can be improved in the future.

**Comment by drdanz** [comment]
Closing this in favour of #2319

**Pull request closed without merging**
