### PR TITLE
qos for yarp

### PR DESCRIPTION
**Pull request by apaikan**
seems to be ready!

### CODE REVIEW

**Comment by lornat75** [comment]
We should first check why travis is failing?

**Comment by apaikan** [comment]
why all the #ifdef YARP_HAS_ACE are removed from DgramTwoWayStream.cpp? :o

**Comment by drdanz** [comment]
Should be fixed now... Probably a failed rebase

**Comment by paulfitz** [comment]
Nice clean patch, really interesting feature!

**Pull request merged**
