### PR TITLE
[libYARP_dev Modules] Call interrupt and destructor of rosNode

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
As otherwise port is not closed
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/814%23issuecomment-229437940%22%2C%20%22https%3A//github.com/robotology/yarp/pull/814%23issuecomment-229992098%22%2C%20%22https%3A//github.com/robotology/yarp/pull/814%23issuecomment-230253910%22%2C%20%22https%3A//github.com/robotology/yarp/pull/814%23issuecomment-231426246%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/814%23issuecomment-229437940%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20%40randaz81%20%40drdanz%2C%5Cr%5CnWould%20be%20great%20if%20you%20review%20and%20merge.%5Cr%5CnThanks%2C%20Tobi%22%2C%20%22created_at%22%3A%20%222016-06-29T18%3A01%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%20%40drdanz%20%40randaz81%2C%5Cr%5CnThis%20PR%20now%20includes%20several%20crucial%20fixes%20when%20working%20with%20ROS/Gazebo.%20Without%20the%20changes%2C%20segfaults%20occur%20as%20some%20ports%20are%20not%20closed%20properly%20when%20trying%20to%20reopen%20these%20ports.%20Also%20the%20double%20%60RateThread%3A%3Astop%28%29%60%20leads%20randomly%20to%20segfaults.%5Cr%5Cn%5Cr%5CnTobi%22%2C%20%22created_at%22%3A%20%222016-07-01T16%3A36%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Looks%20good%20to%20me%2C%20but%20I%27m%20not%20familiar%20with%20Rangefinder2DWrapper%20code%20so%20I%27ll%20let%20%40randaz81%20review%20it...%22%2C%20%22created_at%22%3A%20%222016-07-04T10%3A01%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22thank%20you%21%20%40Tobias-Fischer%22%2C%20%22created_at%22%3A%20%222016-07-08T17%3A48%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2869969%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/randaz81%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/yarp/pull/814#issuecomment-229437940'>General Comment</a></b>
- <a href='https://github.com/Tobias-Fischer'></a> Hi @randaz81 @drdanz,
Would be great if you review and merge.
Thanks, Tobi
- <a href='https://github.com/Tobias-Fischer'></a> Hi @drdanz @randaz81,
This PR now includes several crucial fixes when working with ROS/Gazebo. Without the changes, segfaults occur as some ports are not closed properly when trying to reopen these ports. Also the double `RateThread::stop()` leads randomly to segfaults.
Tobi
- <a href='https://github.com/drdanz'></a> Looks good to me, but I'm not familiar with Rangefinder2DWrapper code so I'll let @randaz81 review it...
- <a href='https://github.com/randaz81'></a> thank you! @Tobias-Fischer

<a href='https://www.codereviewhub.com/robotology/yarp/pull/814?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/yarp/pull/814?approve=1'></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/814'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/yarp/pull/814'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Tobias-Fischer** [comment]
Hi @randaz81 @drdanz,
Would be great if you review and merge.
Thanks, Tobi

**Comment by Tobias-Fischer** [comment]
Hi @drdanz @randaz81,
This PR now includes several crucial fixes when working with ROS/Gazebo. Without the changes, segfaults occur as some ports are not closed properly when trying to reopen these ports. Also the double `RateThread::stop()` leads randomly to segfaults.

Tobi

**Comment by drdanz** [comment]
Looks good to me, but I'm not familiar with Rangefinder2DWrapper code so I'll let @randaz81 review it...

**Comment by randaz81** [comment]
thank you! @Tobias-Fischer

**Pull request merged**
